import { EventEmitter } from 'node:events';
import { randomUUID } from 'node:crypto';
import { fork } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { createProductStore } from '../product-store.mjs';
import { join } from 'node:path';
const active=s=>['starting','running','stopping'].includes(s);
export function createProcessService({dataDir,spawnHost=()=>fork(fileURLToPath(new URL('./process-host.mjs',import.meta.url)),[],{stdio:['ignore','ignore','ignore','ipc'],execArgv:[]})}){
 const events=new EventEmitter();const store=createProductStore(join(dataDir,'executions.json'),{version:1,records:[]});
 const records=new Map();const requests=new Map();const pendingStarts=new Map();const generations=new Map();let host;let ready;let persistTimer;let closed=false;
 function publicRecord(r,logs=false){const {log,...value}=r;return {...value,...(logs?{log}:{} )};}
 async function init(){ready ||= (async()=>{const s=await store.read();if(s.version!==1)throw new Error('不支持的 Release 执行记录版本。');for(const r of s.records){if(active(r.status)){r.status='interrupted';r.ended_at=new Date().toISOString();}records.set(r.id,r);}await persist();})();return ready;}
 async function persist(){const values=[...records.values()];const retained=[...values.filter(r=>active(r.status)),...values.filter(r=>!active(r.status)).slice(-200)];const keep=new Set(retained.map(r=>r.id));for(const id of records.keys())if(!keep.has(id))records.delete(id);await store.update(s=>{s.records=retained;});}
 function schedule(){if(!persistTimer)persistTimer=setTimeout(()=>{persistTimer=null;persist().catch(e=>events.emit('event',{type:'storage-error',message:e.message}));},1000);}
 function changed(r){events.emit('event',{type:'execution',scope:r.scope,project_id:r.project_id,id:r.id,record:publicRecord(r)});schedule();}
 function ensureHost(){if(host)return;host=spawnHost();host.on('error',e=>events.emit('event',{type:'host-error',message:e.message}));host.on('message',message=>{
   if(message.request){const pending=requests.get(message.request);if(pending){clearTimeout(pending.timer);requests.delete(message.request);message.error?pending.reject(new Error(message.error)):pending.resolve(message.result);}return;}
   const r=records.get(message.id);if(!r)return;
   if(message.type==='data'){r.log_truncated ||= r.log.length+message.data.length>524288;r.log=(r.log+message.data).slice(-524288);r.sequence=(r.sequence||0)+1;events.emit('event',{type:'output',scope:r.scope,project_id:r.project_id,id:r.id,data:message.data,sequence:r.sequence});schedule();}
   if(message.type==='exit'){r.status=r.status==='stopping'?'stopped':message.code===0?'completed':'failed';r.exit_code=message.code;r.signal=message.signal;r.ended_at=new Date().toISOString();changed(r);}
  });host.on('exit',()=>{host=null;for(const p of requests.values()){clearTimeout(p.timer);p.reject(new Error('终端宿主已退出。'));}requests.clear();for(const r of records.values())if(active(r.status)){r.status='interrupted';r.ended_at=new Date().toISOString();changed(r);}});}
 function request(action,id,input={}){if(closed&&action!=='stop')return Promise.reject(new Error('执行服务已关闭。'));ensureHost();return new Promise((resolve,reject)=>{const request=randomUUID();const timer=setTimeout(()=>{requests.delete(request);reject(new Error('执行宿主响应超时。'));},15000);requests.set(request,{resolve,reject,timer});const message={request,action,id,input};if(host.postMessage)host.postMessage(message);else host.send(message);});}
 async function start(owner,input,generation){await init();if(generation!==(generations.get(owner.scope)||0))throw new Error("账号作用域已关闭。");if(closed)throw new Error('执行服务已关闭。');if([...records.values()].filter(r=>active(r.status)).length>=24)throw new Error('同时运行的终端/任务已达到 24 个。');
  const r={id:randomUUID(),scope:owner.scope,project_id:owner.id,workspace:owner.path,kind:input.kind||'task',title:input.title||input.command||'Shell',command:input.command||'',status:'starting',created_at:new Date().toISOString(),log:'',sequence:0,source:input.source||null};records.set(r.id,r);await persist();changed(r);
  try{if(generation!==(generations.get(owner.scope)||0))throw new Error('账号作用域已关闭。');const result=await request('start',r.id,{...input,cwd:owner.path});r.pid=result.pid;if(r.status==='starting')r.status='running';changed(r);}catch(e){r.status='failed';r.log+=e.message;r.ended_at=new Date().toISOString();changed(r);}return publicRecord(r,true);
 }
 async function owned(owner,id){await init();const r=records.get(id);if(!r||r.scope!==owner.scope||r.project_id!==owner.id||r.workspace!==owner.path)throw new Error('执行不属于当前项目工作区。');return r;}
 async function control(owner,id,action,input={}){const r=await owned(owner,id);if(!['write','resize','interrupt','stop'].includes(action))throw new Error('不支持的执行控制。');if(!active(r.status))throw new Error('执行已经结束。');if(action==='write'&&(typeof input.data!=='string'||input.data.length>65536))throw new Error('终端输入过大。');if(action==='resize'&&(!Number.isInteger(input.cols)||!Number.isInteger(input.rows)||input.cols<2||input.cols>500||input.rows<1||input.rows>300))throw new Error('终端尺寸无效。');if(action==='stop'){r.status='stopping';changed(r);}await request(action,id,input);return publicRecord(r);}
 return {start(owner,input){const promise=start(owner,input,generations.get(owner.scope)||0);pendingStarts.set(promise,owner.scope);promise.finally(()=>pendingStarts.delete(promise)).catch(()=>{});return promise;},control,async list(scope){await init();return [...records.values()].filter(r=>r.scope===scope).reverse().map(r=>publicRecord(r));},async read(owner,id,options={}){const record=publicRecord(await owned(owner,id),true);if(options.limit!==undefined){const limit=Math.max(1,Math.min(65536,Number(options.limit)||32768));const offset=options.offset===undefined?Math.max(0,record.log.length-limit):Math.max(0,Math.min(record.log.length,Number(options.offset)||0));const length=record.log.length;record.log=record.log.slice(offset,offset+limit);record.log_offset=offset;record.next_offset=offset+record.log.length;record.has_more=record.next_offset<length;}return record;},onEvent(fn){events.on('event',fn);return()=>events.off('event',fn);},async stopScope(scope){generations.set(scope,(generations.get(scope)||0)+1);await Promise.allSettled([...pendingStarts].filter(([,s])=>s===scope).map(([p])=>p));await init();await Promise.allSettled([...records.values()].filter(r=>r.scope===scope&&active(r.status)).map(r=>control({scope,id:r.project_id,path:r.workspace},r.id,'stop')));},async close(){closed=true;await Promise.allSettled([...pendingStarts.keys()]);await init();clearTimeout(persistTimer);await Promise.allSettled([...records.values()].filter(r=>active(r.status)).map(r=>control({scope:r.scope,id:r.project_id,path:r.workspace},r.id,'stop')));await new Promise(r=>setTimeout(r,950));host?.kill();await persist();}};
}
