(() => {
 const M=window.WorkModel;
 const esc = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const icons={plus:'M12 5v14M5 12h14',arrow:'M5 12h14m-6-6 6 6-6 6',chevron:'m9 5 7 7-7 7',chat:'M20 11.5a8 8 0 0 1-8 8H5l-3 2v-10a9 9 0 0 1 18 0Z',mic:'M9 5a3 3 0 0 1 6 0v7a3 3 0 0 1-6 0ZM5 10v2a7 7 0 0 0 14 0v-2M12 19v3m-4 0h8',play:'m8 5 11 7-11 7Z',pause:'M8 5v14M16 5v14',close:'m6 6 12 12M18 6 6 18',check:'m5 12 4 4L19 6',grid:'M3 3h7v7H3ZM14 3h7v7h-7ZM3 14h7v7H3ZM14 14h7v7h-7Z',list:'M9 5h12M9 12h12M9 19h12M3 5h1M3 12h1M3 19h1',clock:'M12 8v5l3 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z',settings:'M4 7h16M4 17h16M8 4v6M16 14v6',external:'M14 3h7v7m0-7-11 11M10 3H3v18h18v-7',search:'M16 16l5 5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z'};
 const icon=(name)=>`<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round">${`<path d="${icons[name]||icons.grid}"/>`}</svg>`;
 const button=(action,text,cls='',extra='')=>`<button type="button" data-action="${action}" class="${cls}" ${extra}>${text}</button>`;
 const tag=t=>`<span class="status status-${esc(t.mode)}"><i></i>${esc(t.mode==='manual'?M.states[t.status]:M.modes[t.mode]||M.states[t.status])}</span>`;
 const taskMeta=t=>`<span>${esc(M.project(t.project).name)}</span><span>#${t.id}</span><span>执行人 ${esc(t.assignee)}</span>`;
 const scopeName=()=>M.state.scope==='all'?'所有项目':M.project(M.state.scope).name;
 const modeNames={list:'A · 项目事情台',focus:'B · 事情工作现场',attention:'C · 关注与接力'};
 function nav(){return `<aside class="sidebar"><a class="brand" href="index.html"><span class="brand-mark">a</span><strong>ArcOrbit</strong></a><div class="side-workspace"><span class="avatar">G</span><div><strong>Glare 的工作空间</strong><small>个人与团队项目</small></div></div><div class="nav-group"><p>工作</p>${button('scope-all',icon('grid')+'需要我关注','nav-item '+(M.state.scope==='all'?'selected':''))}${button('all-tasks',icon('list')+'所有事情','nav-item')}</div><div class="nav-group"><p>项目 <span>${M.projects.length}</span></p>${M.projects.map(p=>button('project',`<span class="project-initial">${p.initial}</span><span>${p.name}</span><small>${M.state.tasks.filter(t=>t.project===p.id&&!['accepted','cancelled'].includes(t.status)).length}</small>`,'nav-item '+(M.state.scope===p.id?'selected':''),`data-project="${p.id}"`)).join('')}</div><div class="nav-group secondary-nav"><p>项目资源</p>${button('resources',icon('grid')+'资料与专业视图','nav-item')}${button('settings',icon('settings')+'执行与连接','nav-item')}</div><div class="sidebar-bottom"><div class="connection"><i class="${M.state.offline?'offline':''}"></i>${M.state.offline?'离线演示 · 保留本机内容':'本机演示 · 内容已保存'}</div><a href="index.html">${icon('external')} 返回方案比较</a></div></aside>`;}
 function header(){return `<header class="topbar"><div class="breadcrumb">项目空间 <span>/</span> <strong>${scopeName()}</strong></div><div class="top-actions"><label class="view-picker"><span class="sr-only">切换探索方案</span><select id="view-picker">${Object.entries(modeNames).map(([id,name])=>`<option value="${id}" ${M.view===id?'selected':''}>${name}</option>`).join('')}</select></label>${button('demo','演示控制','quiet')}${button('new',icon('plus')+'发起事情','primary')}</div></header>`;}
 function filters(){return `<div class="query-bar"><div class="search-field">${icon('search')}<input id="search" aria-label="搜索事情" placeholder="搜索事情…" value="${esc(M.state.query)}"></div><select id="state-filter" aria-label="事情状态"><option value="all">全部状态</option><option value="attention" ${M.state.filter==='attention'?'selected':''}>需要我关注</option>${Object.entries(M.states).map(([id,name])=>`<option value="${id}" ${M.state.filter===id?'selected':''}>${name}</option>`).join('')}</select>${button('filters',icon('settings'),'icon-button','aria-label="更多筛选" title="更多筛选"')}</div>`;}
 function row(t){return `<button type="button" class="task-row ${M.state.selected===t.id?'active':''}" data-action="select" data-task="${t.id}"><div class="row-title"><span class="task-symbol ${t.status==='accepted'?'complete':''}">${t.status==='accepted'?icon('check'):icon(t.mode==='auto'?'play':'list')}</span><strong>${esc(t.title)}</strong></div><div class="row-meta"><span>${esc(M.project(t.project).name)} · #${t.id}</span>${tag(t)}</div></button>`;}
 function empty(){return `<div class="empty-state">${icon('search')}<h3>这里暂时没有事情</h3><p>调整筛选，或从一句话开始新的工作。</p>${button('clear-filters','清除筛选')}${button('new','发起事情','primary')}</div>`;}
 function listView(){return `<section class="list-layout"><div class="task-browser"><div class="section-heading"><h1>${M.state.scope==='all'?'所有事情':'项目事情'}</h1><span>${M.visible().length} 件</span></div>${filters()}<div class="task-rows">${M.visible().map(row).join('')||empty()}</div><div class="list-footer">七种事情状态 · Chat / Auto 共用同一件事情</div></div><div class="detail-host">${M.current()?detail(M.current()):emptyDetail()}</div></section>`;}
 function focusView(){const t=M.current();return `<section class="focus-layout"><div class="focus-rail"><div class="rail-head"><span>${scopeName()}</span>${button('choose-task',icon('list')+'切换事情','quiet')}</div><div class="task-chips">${M.visible().map(x=>button('select',`<i class="dot dot-${x.mode}"></i><span>${esc(x.title)}</span>`,'task-chip '+(t?.id===x.id?'active':''),`data-task="${x.id}"`)).join('')}</div></div><div class="focus-stage">${t?detail(t,true):emptyDetail()}</div></section>`;}
 function attentionCard(t,important=false){return `<article class="attention-card ${important?'important':''}"><div class="card-meta">${taskMeta(t)}</div><div class="card-heading"><h3>${esc(t.title)}</h3>${tag(t)}</div><p>${esc(t.decision||t.external||t.pending.length&&'有补充要求将在下一步生效'||t.activity.at(-1))}</p><div class="card-actions">${button('select',important?'进入处理':'打开现场',important?'primary':'',`data-task="${t.id}"`)}${button('chat','交流','quiet',`data-task="${t.id}"`)}</div></article>`;}
 function attentionView(){
  const tasks=M.visible(),important=tasks.filter(t=>['decision','paused','failed'].includes(t.mode)),running=tasks.filter(t=>['auto','queued','external'].includes(t.mode)),done=tasks.filter(t=>t.status==='completed'),other=tasks.filter(t=>!important.includes(t)&&!running.includes(t)&&!done.includes(t));
  return `<section class="attention-layout ${M.current()?'has-detail':''}"><div class="attention-main"><div class="attention-intro"><p class="eyebrow">YOUR ATTENTION, WHERE IT MATTERS</p><h1>${important.length?`${important.length} 件事情，等你接一棒。`:'工作正在有序推进。'}</h1><p>${scopeName()} · 自动执行与人工决定各有位置。</p></div><div class="attention-board"><section class="attention-group attention-priority"><div class="attention-heading"><h2>需要你决定</h2><span>${important.length}</span></div><div class="attention-cards">${important.map(t=>attentionCard(t,true)).join('')||'<p class="subtle">当前没有需要你决定的事情。</p>'}</div></section><section class="attention-group"><div class="attention-heading"><h2>正在推进</h2><span>${running.length}</span>${button('settings','执行设置','quiet')}</div><div class="attention-cards">${running.map(t=>attentionCard(t)).join('')||'<p class="subtle">没有正在进行的 Auto。</p>'}</div></section><section class="attention-group"><div class="attention-heading"><h2>结果待检查</h2><span>${done.length}</span></div><div class="attention-cards">${done.map(t=>attentionCard(t)).join('')||'<p class="subtle">新的完成结果会出现在这里。</p>'}</div></section></div><details class="other-tasks"><summary>其他事情 · ${other.length}</summary>${other.map(row).join('')}</details></div>${M.current()?`<div class="attention-detail"><div class="detail-back">${button('close-detail',icon('close')+'收起现场','quiet')}</div>${detail(M.current())}</div>`:''}</section>`;
 }
 function emptyDetail(){return `<div class="empty-state large">${icon('spark')}<h2>选择一件事情，继续推进。</h2><p>目标、成果和协作记录，会一起留在这里。</p>${button('new','从一句话开始','primary')}</div>`;}
 function actions(t){
  if(t.mode==='auto')return button('chat',icon('chat')+'交流','')+button('pause',icon('pause')+'暂停并讨论','')+button('stop','停止执行','quiet');
  if(t.mode==='queued')return button('chat','补充要求')+button('unqueue','撤回 Auto','quiet');
  if(t.mode==='paused')return button('resume',icon('play')+'继续 Auto','primary')+button('chat','继续讨论')+button('stop','停止执行','quiet');
  if(t.mode==='decision')return button('decision','处理决定','primary')+button('chat','先讨论');
  if(t.mode==='external')return button('recheck','条件已就绪，重新检查','primary')+button('chat','补充说明');
  if(['failed','stopped'].includes(t.mode))return button('recover','恢复本次执行','primary')+button('chat','说明情况');
  if(t.status==='completed')return button('accept','验收通过','primary',t.issues.some(i=>!i.resolved)?'disabled title="仍有未解决的验收问题"':'')+button('issue','提出验收问题');
  if(t.status==='accepted')return '<span class="subtle">验收已完成，结果保留可查</span>';
  if(t.status==='cancelled')return '<span class="subtle">事情已取消，可在属性中纠偏</span>';
  if(t.status==='blocked')return button('unblock','恢复为待处理','primary')+button('chat','补充信息');
  return button('auto',icon('play')+'开始 Auto','primary')+button('analyze',icon('spark')+'先分析');
 }
 function scene(t){
  let special='';
  if(t.mode==='decision')special=`<section class="decision-block"><p class="eyebrow">需要你的决定</p><h3>${esc(t.decision)}</h3><p>已有分析与记录已保留。你可以直接选择，也可以先讨论。</p>${button('decision','查看选项并决定','primary')}${button('chat','和 Agent 讨论','quiet')}</section>`;
  if(t.mode==='external')special=`<section class="notice"><strong>等待外部条件</strong><p>${esc(t.external)}</p><p>当前执行保持等待；补充消息不会自动解除等待。</p></section>`;
  if(t.mode==='failed')special='<section class="notice"><strong>执行中断，现场已保留</strong><p>保留事情身份、协作记录与已完成步骤。恢复后继续核对当前事实。</p></section>';
  if(t.mode==='queued')special='<section class="notice"><strong>已进入 Auto 队列</strong><p>同一项目工作区串行推进；当前位置释放后继续。列表排序不会改变实际执行顺序。</p></section>';
  if(t.mode==='paused')special='<section class="notice"><strong>当前执行已暂停</strong><p>现在可以讨论和调整方向。准备好后，显式选择“继续 Auto”。</p></section>';
  if(t.pending.length)special+=`<section class="notice pending"><strong>${t.pending.length} 条说明待生效</strong><p>${esc(t.pending.join('；'))}</p><small>已接收，下一执行边界采用；不会启动第二条并行对话执行。</small></section>`;
  return `${special}<section class="goal-block"><div class="block-heading"><h3>这件事要完成什么</h3>${button('edit','编辑目标','text-button')}</div><p class="preserve">${esc(t.body)}</p></section>${t.analysis?`<section class="analysis-block"><p class="eyebrow">当前分析</p><h3>先明确范围，再形成可检查的结果。</h3><p>${esc(t.analysis)}</p><div class="inline-links">${button('edit','调整目标','text-button')}${button('chat','继续讨论','text-button')}</div></section>`:''}${t.plan.length?`<section class="plan-block"><div class="block-heading"><h3>${['auto','queued','paused','decision','done','external','failed'].includes(t.mode)?'推进情况':'建议的推进步骤'}</h3><span class="subtle">${Math.min(t.step,t.plan.length)} / ${t.plan.length}</span></div><ol class="steps">${t.plan.map((p,i)=>`<li class="${i<t.step?'done':i===t.step?'current':''}"><span class="step-index">${i<t.step?icon('check'):i+1}</span><div><strong>${esc(p)}</strong><small>${i<t.step?'已完成':i===t.step?(t.mode==='auto'?'正在推进':'当前步骤'):'后续步骤'}</small></div></li>`).join('')}</ol></section>`:['review','ready'].includes(t.status)?`<section class="start-options"><div><span class="option-icon">${icon('spark')}</span><h3>先一起想清楚</h3><p>分析目标、方案与验收口径，决定下一步。</p>${button('analyze','开始分析','text-button')}</div><div><span class="option-icon">${icon('play')}</span><h3>目标明确，交给 Auto</h3><p>查看执行范围，沿用这件事情持续推进。</p>${button('auto','开始 Auto','text-button')}</div></section>`:''}${['completed','accepted'].includes(t.status)?results(t):''}<section class="context-links"><span>相关内容</span>${button('resources','产品资料','quiet')}${button('evidence','证据与运行详情','quiet')}${button('chat',`协作记录 · ${t.messages.length}`,'quiet')}</section>`;
 }
 function attributes(t){return `<section><div class="block-heading"><h3>事情属性</h3>${button('edit','编辑属性','text-button')}</div><dl class="attributes"><dt>产品</dt><dd>${esc(M.project(t.project).name)}</dd><dt>执行人</dt><dd>${esc(t.assignee)}</dd><dt>事情状态</dt><dd>${M.states[t.status]}</dd><dt>推进方式</dt><dd>${M.modes[t.mode]}</dd><dt>优先级</dt><dd>${esc(t.priority)}</dd><dt>标签</dt><dd>${esc(t.tag)}</dd><dt>本机执行</dt><dd>${M.state.config[t.project]?'已准备':'需要配置'}</dd></dl><p class="subtle">执行人表示责任归属。开始 Auto 后，执行人保持不变。</p><div class="capability-box"><h3>团队协作</h3><p>现有父子关系、评论、附件与标签管理在事情属性中保留。探索稿仅演示下面的评论。</p>${button('comment','添加示例评论')}${t.comments?.map(c=>`<p class="comment">我：${esc(c)}</p>`).join('')||''}</div></section>`;}
 function results(t){return `<section class="results-block"><div class="block-heading"><h3>成果与验收</h3>${tag(t)}</div>${['completed','accepted'].includes(t.status)?`<div class="artifact">${icon('check')}<div><strong>工作结果摘要</strong><p>目标已按示例步骤完成；请检查结果与原始要求是否一致。</p></div>${button('artifact','查看','quiet')}</div><div class="artifact">${icon('list')}<div><strong>验证与变更记录</strong><p>示例：检查通过，关联变更保留。</p></div>${button('evidence','查看','quiet')}</div>${t.issues.length?`<h4>独立验收问题</h4>${t.issues.map((i,n)=>`<div class="issue"><span>${esc(i.text)}<small>${i.resolved?'已解决':'等待验证修复'}</small></span>${!i.resolved?button('resolve-issue','模拟解决','quiet',`data-index="${n}"`):''}</div>`).join('')}`:'<p class="subtle">当前没有未解决的验收问题。</p>'}`:'<p class="subtle">工作形成结果后，在这里检查。执行日志与未完成的分析不自动代表完成。</p>'}</section>`;}
 function activity(t){return `<section><h3>工作活动</h3><p class="subtle">本次模拟的操作记录；完整交流由“查看消息”主动打开。</p><ol class="activity-list">${t.activity.toReversed().map(x=>`<li>${esc(x)}</li>`).join('')}</ol>${button('chat',`查看消息（${t.messages.length}）`)}</section>`;}
 function composer(t,inDialog=false){let placeholder=t.mode==='auto'?'补充要求，下一执行边界生效…':t.mode==='paused'?'讨论调整方向，准备好后再继续 Auto…':'补充目标、询问进展或改变方向…';const disabled=['completed','accepted','cancelled'].includes(t.status);return `<form class="composer" data-form="message" data-owner="${t.id}"><div class="composer-context"><span>${icon('spark')} ${esc(t.title)}</span>${!inDialog?button('chat',icon('chat')+`查看消息${t.messages.length?' · '+t.messages.length:''}`,'text-button'):''}</div><div class="composer-input"><textarea aria-label="向当前事情补充要求" name="message" rows="2" placeholder="${placeholder}" ${disabled?'disabled':''}>${esc(t.draft)}</textarea><div class="send-actions">${button('voice',icon('mic'),'icon-button','aria-label="语音交流预留说明" title="语音入口 · 本轮仅预留"')}<button type="submit" class="send-button" ${disabled?'disabled':''} aria-label="发送要求">${icon('arrow')}</button></div></div><div class="composer-foot"><span>${disabled?'已收束 · 可查看记录，或从验收入口继续':t.mode==='auto'?'追加说明不会暂停 Auto':'文字与未来语音共用当前事情上下文'}</span>${button('model',`${esc(t.model)} / ${esc(t.level)}`,'text-button')}</div></form>`;}
 function detail(t,focus=false){return `<article class="work-detail ${focus?'immersive':''}" data-current-task="${t.id}"><header class="work-header"><div class="work-meta">${taskMeta(t)}<span class="state-label">${M.states[t.status]}</span></div><h${focus?'1':'2'}>${esc(t.title)}</h${focus?'1':'2'}><div class="work-action-bar">${tag(t)}<div class="work-actions">${actions(t)}</div></div></header><nav class="detail-tabs" aria-label="事情内容">${[['scene','工作现场'],['attributes','属性与协作'],['results','成果与验收'],['activity','工作活动']].map(([id,label])=>button('tab',label,M.state.tab===id?'active':'',`data-tab="${id}"`)).join('')}</nav><div class="work-scroll">${({scene,attributes,results,activity}[M.state.tab]||scene)(t)}</div>${composer(t)}</article>`;}
 function render(){const app=document.getElementById('app');app.className='app-shell view-'+M.view;app.innerHTML=`<div class="prototype-strip"><span>探索稿 ${M.view.toUpperCase()} · 所有 Agent 与执行均为模拟</span><span>${M.storageAvailable?'进度仅保存在此浏览器':'浏览器未允许存储，刷新后可能丢失进度'}</span></div>${nav()}<main class="main-shell">${header()}<div class="workspace">${({list:listView,focus:focusView,attention:attentionView}[M.view])()}</div></main>`;}
 window.WorkViews={esc,icon,button,tag,render,composer,modeNames,scopeName};
})();
