const {app, BrowserWindow} = require('electron');
const assert = require('node:assert/strict');
const fs = require('node:fs'), path = require('node:path'), os = require('node:os');
const output = process.env.ARCORBIT_TEST_OUTPUT || fs.mkdtempSync(path.join(os.tmpdir(), 'chat-files-evidence-'));
fs.mkdirSync(output, {recursive: true});
app.setPath('userData', fs.mkdtempSync(path.join(os.tmpdir(), 'chat-files-browser-')));
app.disableHardwareAcceleration();
app.whenReady().then(async () => {
  const w = new BrowserWindow({width: 1500, height: 1000, show: false, webPreferences: {sandbox: true, contextIsolation: true}});
  const errors = [], requests = [], checks = [];
  w.webContents.on('console-message', (_e, level, text) => {if (level >= 3 && !text.includes('Content Security Policy')) errors.push(text);});
  w.webContents.session.webRequest.onBeforeRequest((d, cb) => {if (/^https?:/.test(d.url)) requests.push(d.url); cb({cancel: /^https?:/.test(d.url)});});
  const run = text => w.webContents.executeJavaScript(text);
  const pause = () => new Promise(resolve => setTimeout(resolve, 120));
  const state = text => run(`(()=>{const F=ChatFilesModel,s=F.current(),t=F.tab(s);return (${text})})()`);
  const click = async selector => {await run(`(()=>{const b=document.querySelector(${JSON.stringify(selector)});if(!b||b.disabled)throw Error('missing/disabled '+${JSON.stringify(selector)});b.focus();b.click()})()`); await pause();};
  const open = p => click(`[data-file-action="open"][data-path="${p}"]`);
  const edit = async text => {await run(`(()=>{const e=document.querySelector('.file-text');e.focus();e.value=${JSON.stringify(text)};e.dispatchEvent(new Event('input',{bubbles:true}))})()`); await pause();};
  const submitName = async name => {await run(`document.querySelector('#file-dialog input').value=${JSON.stringify(name)};document.querySelector('#file-dialog form').requestSubmit()`);await pause();};
  const menu = async p => {await run(`document.querySelector('[data-file-row="${p}"]').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}))`);await pause();};
  const menuAction = name => click(`#file-menu [data-file-action="${name}"]`);
  const shot = async name => fs.writeFileSync(path.join(output, name+'.png'), (await w.webContents.capturePage()).toPNG());
  function record(name) {checks.push(name);console.log(name);}
  try {
    await w.loadFile(path.join(__dirname, 'default.html'), {query: {autoplay: 'off'}}); await pause();
    await run('document.documentElement.dataset.theme="light"');
    await click('[data-detail-mode="files"]');
    for (const p of ['.git','.env','node_modules','linked']) assert(await run(`!!document.querySelector('[data-file-row="${p}"]')`));
    await open('many'); assert.equal(await run('document.querySelectorAll("[data-file-row^=\\"many/\\"]").length'), 50);
    await click('[data-file-action="more"][data-path="many"]'); await click('[data-file-action="more"][data-path="many"]');
    assert.equal(await run('document.querySelectorAll("[data-file-row^=\\"many/\\"]").length'), 125);
    await open('many');
    await open('.git'); assert(await run('!!document.querySelector("[data-file-row=\\".git/config\\"]")'));
    await open('restricted'); assert.match(await run('document.querySelector(".file-tree").textContent'), /没有读取/);
    await run('ChatFileUI.scenario("files-recover")'); await click('[data-file-action="refresh"]');
    assert(!await run('document.querySelector(".file-tree").textContent.includes("没有读取")'));
    record('hidden items, ignored directories, pagination, permission failure/recovery');
    await run('document.querySelector("#chat-input").value="前 后";document.querySelector("#chat-input").dispatchEvent(new Event("input",{bubbles:true}));document.querySelector("#chat-input").setSelectionRange(1,1);document.querySelector("#chat-input").dispatchEvent(new Event("select",{bubbles:true}))');
    const originalMessages = await run('ChatModel.current().messages.length');
    await menu('.env'); await menuAction('reference');
    assert.equal(await run('ChatModel.owner().draft'), '前 .env 后');
    assert.equal(await run('ChatModel.current().messages.length'), originalMessages);
    assert.equal(await run('document.activeElement.id'), 'chat-input');
    await menu('node_modules'); await menuAction('reference'); assert.match(await run('ChatModel.owner().draft'), /node_modules\//);
    record('right-click relative references inserted at cursor; no send or content read');
    await open('src'); await open('src/app.js'); await edit('local draft\nsecond line');
    await run('document.querySelector(".file-text").setSelectionRange(5,5);ChatPrototype.render()');
    assert.equal(await state('t.text'), 'local draft\nsecond line');
    assert.equal(await run('document.querySelector(".file-text").selectionStart'), 5);
    await open('src/nested'); await open('src/nested/app.js');
    assert.equal(await state('s.tabs.length'), 2);
    assert.match(await run('document.querySelector(".file-tabs").textContent'), /src\/nested/);
    await open('src/app.js'); assert.equal(await state('s.tabs.length'), 2);
    await click('[data-file-action="close"][data-path="src/app.js"]');
    assert(await run('document.querySelector("#file-dialog").open')); await click('#file-dialog [data-file-action="cancel"]');
    assert(await state('F.dirty(t)')); await run('ChatFileUI.scenario("files-save-failure")');
    await click('[data-file-action="close"][data-path="src/app.js"]');await click('#file-dialog [type="submit"]');
    assert.match(await run('document.querySelector("#file-dialog [role=alert]").textContent'), /失败/);
    assert(await state('s.tabs.some(t=>t.path==="src/app.js")')); await click('#file-dialog [data-file-action="cancel"]');
    await click('.file-editor-tools [data-file-action="save"]'); assert.equal(await state('F.dirty(t)'), false);
    await edit('conflicting local');await run('ChatFileUI.scenario("files-conflict")');
    await click('.file-editor-tools [data-file-action="save"]');assert.match(await state('t.error'), /磁盘已变化/);
    assert.equal(await state('t.text'), 'conflicting local');
    await click('.file-editor-tools [data-file-action="disk"]');assert.match(await run('document.querySelector(".file-disk").textContent'), /磁盘上的新内容/);await click('#file-dialog [type="submit"]');
    await click('.file-editor-tools [data-file-action="reload"]');await click('#file-dialog [type="submit"]');assert.equal(await state('F.dirty(t)'), false);
    record('deduplicated file tabs, cursor preservation, dirty close cancel, save failure, conflict and explicit reload');
    await edit('rename draft');await menu('src');await menuAction('rename');await submitName('source');
    assert.equal(await state('t.path'),'source/app.js');assert.equal(await state('t.text'),'rename draft');
    await menu('source');await menuAction('new-file');await submitName('../invalid');
    assert.match(await run('document.querySelector("#file-dialog [role=alert]").textContent'), /名称/);
    await submitName('app.js');assert.match(await run('document.querySelector("#file-dialog [role=alert]").textContent'), /已存在/);
    await submitName('created.txt');assert.equal(await state('t.path'),'source/created.txt');
    await menu('source');await menuAction('new-directory');await submitName('new-folder');assert(await state('s.disk.has("source/new-folder")'));
    await edit('unsaved create');await menu('source/created.txt');await menuAction('trash');await click('#file-dialog [data-file-action="cancel"]');assert(await state('s.disk.has("source/created.txt")'));
    await run('ChatFileUI.scenario("files-delete-failure")');await menu('source/created.txt');await menuAction('trash');await click('#file-dialog [data-file-action="alternate"]');
    assert.match(await run('document.querySelector("#file-dialog [role=alert]").textContent'), /失败/);assert(await state('s.disk.has("source/created.txt")'));
    await click('#file-dialog [data-file-action="alternate"]');assert.equal(await state('s.disk.has("source/created.txt")'),false);
    record('create validation, collision rejection, directory rename with dirty children, confirmed trash and failure retention');
    for(const p of ['image.png','large.log','legacy.txt','linked']){await open(p);assert(await run('document.querySelector(".file-editor-tools [data-file-action=save]").disabled'));assert.equal(await run('document.querySelectorAll(".file-text").length'),0);}
    await click('[data-file-action="tab"][data-path="source/app.js"]');
    const draft=await state('t.text');await run('ChatPrototype.select("b1")');assert.equal(await state('s.tabs.length'),0);
    await run('ChatPrototype.select("a1")');assert.equal(await state('t.text'),draft);
    await run('ChatFileUI.scenario("files-deleted")');await click('.file-editor-tools [data-file-action="save"]');assert.match(await state('t.error'),/删除/);assert.equal(await state('t.text'),draft);
    record('unsupported files visible/read-only; project isolation; external deletion keeps draft');
    await click('[data-file-action="chat"]');
    await run('ChatModel.owner().draft="继续讨论";ChatPrototype.render();document.querySelector("#chat-compose").requestSubmit()');
    await open('README.md');await edit('typing during chat');await run('ChatPrototype.tick();ChatPrototype.tick();ChatPrototype.tick()');
    assert.equal(await state('t.text'),'typing during chat');assert.equal(await run('ChatModel.current().status'),'completed');assert(await run('!!document.querySelector(".file-text")'));
    await run('ChatFileUI.scenario("files-slow")');await run('document.querySelector("[data-file-action=open][data-path=\\".env\\"]").click();ChatPrototype.select("b1")');await new Promise(r=>setTimeout(r,420));assert.equal(await state('s.tabs.length'),0);
    await run('ChatPrototype.select("a1")');assert.equal(await state('t.path'),'README.md');
    record('background Chat completes without replacing editor; late file response cannot select another project');
    await run('ChatFileUI.scenario("files-recover")');
    // Actual keyboard events through Chromium input.
    await run('document.querySelector("[data-file-row=\\".env\\"]").focus()');
    w.webContents.sendInputEvent({type:'keyDown',keyCode:'F10',modifiers:['shift']});await pause();assert.equal(await run('document.querySelector("#file-menu").hidden'),false);
    w.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});await pause();assert.equal(await run('document.activeElement.dataset.fileRow'),'.env');
    w.webContents.sendInputEvent({type:'keyDown',keyCode:'Down'});await pause();assert.notEqual(await run('document.activeElement.dataset.fileRow'),'.env');
    await run('document.querySelector("[data-file-action=chat]").focus()');w.webContents.sendInputEvent({type:'keyDown',keyCode:'Right'});await pause();assert(await state('Boolean(s.active)'));
    assert.equal(await run('document.activeElement.getAttribute("role")'),'tab');
    record('keyboard tree navigation, menu activation/Escape focus, tab arrow switching');
    for(const width of [1500,760,390]) {
      w.setContentSize(width,800);await pause();
      if(width<=760){await click('[data-chat-action="toggle-list"]');assert(await run('document.querySelector(".chat-center").inert'));}
      await menu('.env');const geometry=await run('(()=>{const r=document.querySelector("#file-menu").getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:innerWidth,height:innerHeight}})()');
      assert(geometry.left>=0&&geometry.right<=geometry.width&&geometry.top>=0&&geometry.bottom<=geometry.height,JSON.stringify(geometry));
      await shot('files-menu-'+width);await menuAction('open');
      assert.equal(await run('ChatModel.state.listOpen'),false);assert.equal(await run('document.querySelector(".chat-center").inert'),false);
      assert(await run('document.documentElement.scrollWidth<=innerWidth'));console.log('geometry',width,await run('JSON.stringify([...document.querySelectorAll(".chat-center,.file-editor-pane,.file-text")].map(n=>({c:n.className,x:n.getBoundingClientRect().x,w:n.getBoundingClientRect().width})))'));await shot('files-editor-'+width);
    }
    await run('document.documentElement.dataset.theme="dark"');await shot('files-dark-390');
    w.setContentSize(1500,1000);w.webContents.setZoomFactor(2);await pause();assert(await run('document.documentElement.scrollWidth<=innerWidth'));await shot('files-zoom-200');
    record('1500/760/390px menu bounds, drawer focus/inert recovery, dark theme and 200% zoom');
    assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
    const report={ok:true,checks,errors,externalRequests:requests,scope:'Browser-only file and editor samples; no native filesystem, trash, Monaco worker, IPC, real account switch or OS shutdown verification.'};
    fs.writeFileSync(path.join(output,'verification.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({output,...report}));w.destroy();app.exit(0);
  }catch(e){await shot('failure');fs.writeFileSync(path.join(output,'failure.json'),JSON.stringify({error:e.stack,checks,errors,requests},null,2));console.error(e,errors);w.destroy();app.exit(1);}
});
