import { createConversationSurface } from './conversation-surface.mjs';
import { createConversationComposer } from './conversation-composer.mjs';
import { createChatStateCoordinator } from './chat-state-coordinator.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(action,label,extra='')=>`<button type="button" class="secondary-button" data-release="${action}" ${extra}>${esc(label)}</button>`;
const active=s=>['starting','running','stopping'].includes(s);
const labels={starting:'准备中',running:'运行中',stopping:'正在停止',stopped:'已停止',completed:'已完成',failed:'失败',interrupted:'已中断'};
let vendorPromise;
const vendor=()=>vendorPromise ||= import('./vendor/release-vendor.js');
export function createReleaseSurface({api,normalizeChatSnapshot,formatTime,performAction,navigateSetup=()=>{}}){
 const root=document.getElementById('releaseView');
 root.innerHTML=`<div class="release-shell"><header class="release-toolbar"><div><p class="eyebrow">RELEASE</p><h1>本地交付工作台</h1></div><div class="release-actions">${button('activities','本机活动')}${button('refresh','刷新')}${button('terminal','终端')}${button('agent','Agent')}</div></header><div id="releaseError" class="release-error hidden" role="alert"></div><div id="releaseContext" class="release-context"></div><div class="release-body"><div class="release-workspace"><nav id="releaseTabs" class="release-tabs"></nav><main id="releaseMain" class="release-main"></main><div id="releaseResize" class="release-resize" tabindex="0" role="separator" aria-label="调整终端高度" aria-orientation="horizontal"></div><section id="releaseTerminal" class="release-terminal hidden"><header><div id="releaseTerminalTabs"></div><div>${button('split','分屏')}${button('search-terminal','搜索')}${button('clear-terminal','清屏')}${button('terminal','＋')}${button('hide-terminal','收起')}</div></header><div id="releaseTerminalPanes" class="release-terminal-panes"></div></section></div><aside id="releaseAgent" class="release-agent hidden"><header><strong id="releaseAgentTitle">Agent</strong>${button('agent','收起')}</header><div id="releaseChatStatus" class="release-chat-status"></div><div id="releaseTranscript" class="release-transcript"></div><button id="releaseJump" class="secondary-button hidden">回到最新</button><div class="release-composer"><textarea id="releaseChatInput" disabled placeholder="说明你希望 Agent 完成什么…"></textarea><div><span id="releaseChatHint"></span><button id="releaseChatSend" class="primary-button" disabled>发送</button><button id="releaseChatStop" class="secondary-button hidden">停止</button></div></div></aside></div></div>`;
 const el=id=>document.getElementById(id);const cache=new Map();const terminals=new Map();const chats=new Map();let selected='';let tab='tasks';let visible=false;let contextKey='';let selectionEpoch=0;let editorRequest=0;let all={projects:[],records:[]};let scopeIds=[];let scopeId='all';let detail=null;let terminalId='';let split=false;let editor=null;let diffEditor=null;let currentFile=null;let filesPath='';let refreshTimer;let chat=null;let updating=false;
 const drafts=new Map();const commitDrafts=new Map();let gitStaged=false;let gitFile='';let gitDiff=null;
 function error(message='',kind='error'){el('releaseError').dataset.kind=kind;el('releaseError').textContent=message;el('releaseError').classList.toggle('hidden',!message);}
 async function action(fn){try{error();return await fn();}catch(e){error(e.message);throw e;}}
 const run=fn=>performAction(()=>action(fn));
 const command=(action,input={},projectId=selected)=>api.releaseCommand(action,{expected_workspace:cache.get(projectId)?.project.path,...input,project_id:projectId});
 function saveEditor(){if(editor&&currentFile){drafts.set(currentFile.key,{...currentFile,text:editor.getValue()});}}
 function clearDiffModel(){const models=diffEditor?.getModel();diffEditor?.setModel(null);models?.original.dispose();models?.modified.dispose();}
 function disposeEditors(){saveEditor();const model=editor?.getModel();editor?.dispose();model?.dispose();editor=null;clearDiffModel();diffEditor?.dispose();diffEditor=null;currentFile=null;}

 async function refresh(){if(updating)return;updating=true;const token=selectionEpoch;const id=selected;try{all=await api.releaseSnapshot();if(id){const value=await api.releaseDetail(id);cache.set(id,value);if(token!==selectionEpoch)return;const rebound=detail?.project.path&&detail.project.path!==value.project.path;detail=value;if(rebound){selectionEpoch++;disposeEditors();chat=null;renderMain();if(!el('releaseAgent').classList.contains('hidden'))await loadChat();}}renderContext();if(editor&&currentFile){const f=currentFile;const disk=await command('files.read',{path:f.path,expected_workspace:f.expected_workspace},f.project).catch(()=>null);if(currentFile===f&&disk&&disk.revision!==f.revision){const title=el(tab==='git'?'releaseDiffActions':'releaseFileActions')?.querySelector('strong');if(title)title.textContent=f.path+' · 磁盘已变化，请对比后保存';}}if(!id||tab==='history'||tab==='publish')renderMain();else if(tab==='tasks'){const list=el('releaseTaskRecords');if(list)list.innerHTML=recordsHtml((detail.records||[]).slice(0,12));else renderMain();}else if(tab==='git'&&!editor&&!diffEditor)renderMain();renderTerminalTabs();}finally{updating=false;}}
 async function select(projectId){saveEditor();disposeEditors();selected=String(projectId||'');selectionEpoch++;detail=cache.get(selected)||null;gitFile='';gitDiff=null;filesPath='';chat=null;renderChat();el('releaseTranscript').textContent='';const token=selectionEpoch,id=selected;if(id){const value=await api.releaseDetail(id);if(token!==selectionEpoch)return;detail=value;cache.set(id,value);}await refresh();if(token!==selectionEpoch)return;if(selected&&!el('releaseAgent').classList.contains('hidden'))await loadChat();renderMain();renderTerminalTabs();}
 function renderContext(){const p=detail?.project;el('releaseContext').innerHTML=selected?`<strong>${esc(p?.name||'项目')}</strong><code>${esc(p?.path||'')}</code>${detail?.repository?`<span>⑂ ${esc(detail.repository.branch)}</span>`:''}${scopeId==='all'?button('back','返回全部'):''}`:'使用顶部已有产品范围，或选择下面的项目。';el('releaseTabs').innerHTML=selected?[['tasks','本地运行'],['git','Git 变更'],['files','源码'],['history','执行记录'],['publish','发布与维护']].map(([key,label])=>button(`tab:${key}`,label,`data-active="${tab===key}"`)).join(''):'';}
 const projectName=id=>all.projects.find(p=>p.id===id)?.name||id;
 function recordsHtml(records){return records.length?records.map(r=>`<article class="release-record"><div><strong>${esc(r.title)}</strong><small>${esc(projectName(r.project_id))} · ${esc(formatTime(r.created_at))} · ${esc(r.source?.commit?.slice(0,7)||'本机')}${r.source?.dirty?' · 未提交修改':''}</small></div><span class="release-state ${esc(r.status)}">${labels[r.status]||r.status}</span><div>${button('logs','日志',`data-id="${r.id}" data-project="${r.project_id}"`)}${active(r.status)?button('stop','停止',`data-id="${r.id}" data-project="${r.project_id}"`):r.kind==='task'?button('retry','重试',`data-id="${r.id}" data-project="${r.project_id}"`):''}${r.status==='failed'?button('analyze','分析失败',`data-id="${r.id}" data-project="${r.project_id}"`):''}</div></article>`).join(''):'<div class="release-empty">还没有执行记录。运行项目命令后，结果会保存在这里。</div>';}
 function renderMain(){editorRequest++;disposeEditors();const main=el('releaseMain');renderContext();
  if(!selected){main.innerHTML=`<div class="release-section-title"><h2>当前产品集</h2><span>${scopeIds.length} 个项目</span></div><div class="release-projects">${all.projects.filter(p=>scopeIds.includes(p.id)).map(p=>`<article><h2>${esc(p.name)}</h2><code>${esc(p.path||'尚未关联本地目录')}</code>${button(p.path?'project':'setup',p.path?'进入工作台':'打开已有项目设置',`data-project="${p.id}"`)}</article>`).join('')||'<div class="release-empty">当前范围没有项目，请使用顶部已有的产品集管理。</div>'}</div><h2>最近执行</h2>${recordsHtml(all.records.filter(r=>scopeIds.includes(r.project_id)).slice(0,15))}`;return;}
  if(!detail){main.innerHTML='<p>正在读取工作区…</p>';return;}
  if(tab==='tasks')main.innerHTML=`<div class="release-section-title"><h2>运行项目命令</h2>${button('lazygit',detail.tools?.lazygit.available?'高级 Git · Lazygit':'Lazygit · 未安装')}</div><div class="release-scripts">${Object.entries(detail.scripts).map(([name,value])=>`<button data-release="script" data-script="${esc(name)}"><strong>${esc(name)}</strong><code>${esc(value)}</code><span>运行 →</span></button>`).join('')||'<p>当前目录没有 package scripts，可以直接输入项目命令。</p>'}</div><form id="releaseCommandForm" class="release-command-form"><input id="releaseCommandInput" placeholder="输入本机命令，例如 npm run build" value="${esc(drafts.get('command:'+selected)||'')}"><button class="primary-button">运行</button></form><h2>执行与运行实例</h2><div id="releaseTaskRecords">${recordsHtml((detail.records||[]).slice(0,12))}</div>`;
  if(tab==='history')main.innerHTML=`<h2>执行记录</h2>${recordsHtml(detail.records||[])}`;
  if(tab==='publish')main.innerHTML=`<h2>发布与维护</h2><p>在终端执行项目已有的发布、部署与运维命令。执行日志保留真实结果；渠道、健康监控和自动回滚尚未接入。</p><div class="release-actions">${button('terminal','打开终端')}${button('tab:tasks','项目命令')}${button('open-artifact','打开本地产物')}</div><p>本地打包成功、Git 推送和正式渠道发布分别记录，不自动视为同一结果。</p>`;
  if(tab==='git')renderGit();if(tab==='files')renderFiles().catch(e=>error(e.message));
  const form=el('releaseCommandForm');if(form){el('releaseCommandInput').oninput=e=>drafts.set('command:'+selected,e.target.value);form.onsubmit=e=>{e.preventDefault();const id=selected;const cmd=el('releaseCommandInput').value;run(()=>startTask(cmd,id));};}
 }
 function renderGit(){const repo=detail.repository;const main=el('releaseMain');if(!repo){main.innerHTML=`<p>${esc(detail.gitError||'当前目录不是 Git 仓库。')}</p>${button('terminal','打开终端')}`;return;}
  main.innerHTML=`<div class="release-git-toolbar"><strong>⑂ ${esc(repo.branch||'未提交')}</strong><span>↑${repo.ahead} ↓${repo.behind}</span>${button('git:fetch','Fetch')}${button('git:pull','Pull')}${button('git:push','Push')}${button('lazygit','Lazygit')}<select id="releaseGitAction"><option value="">更多 Git 操作…</option>${['switch','branch','delete-branch','tag','delete-tag','stash','stash-pop','merge','rebase','cherry-pick','revert','reset','continue','abort'].map(x=>`<option>${x}</option>`).join('')}</select></div><small class="release-repo-root">仓库 ${esc(repo.root)}</small>${repo.conflicted.length?`<p class="release-warning">${repo.conflicted.length} 个冲突。选择文件比较和编辑，保存后暂存，再继续整合。</p>`:''}<div class="release-git-layout"><aside><div class="release-actions">${button('git-mode:work','工作区')}${button('git-mode:index','已暂存')}</div><div id="releaseFileChanges">${repo.files.filter(f=>gitStaged?f.index!==' '&&f.index!=='?':f.working_dir!==' '||f.index==='?').map(f=>`<div class="release-file-row"><button data-release="diff" data-path="${esc(f.path)}"><b>${esc(f.index+f.working_dir)}</b> ${esc(f.path)}</button>${button(gitStaged?'unstage-file':'stage-file',gitStaged?'－':'＋',`data-path="${esc(f.path)}"`)}</div>`).join('')||'<p>没有相应变更。</p>'}</div><textarea id="releaseCommitMessage" placeholder="提交说明">${esc(commitDrafts.get(selected)||'')}</textarea><div class="release-actions">${button('commit','提交暂存区')}${button('amend','Amend')}</div><details><summary>分支 · Tag · Stash · 历史</summary><p>${esc(repo.branches.join(' · '))}</p><p>${esc(repo.tags.join(' · '))}</p>${repo.stashes.map(s=>`<p>${esc(s.message)}</p>`).join('')}${repo.log.slice(0,30).map(c=>`<p><code>${esc(c.hash.slice(0,7))}</code> ${esc(c.message)}</p>`).join('')}</details></aside><section><div id="releaseDiffActions"></div><div id="releaseEditor" class="release-editor"><div class="release-empty">选择文件查看差异。</div></div><div id="releaseHunks"></div></section></div>`;
  el('releaseCommitMessage').oninput=e=>commitDrafts.set(selected,e.target.value);el('releaseGitAction').onchange=e=>{const value=e.target.value;e.target.value='';if(value)run(()=>gitAction(value));};
 }
 async function gitAction(action,input={}){const id=selected,repository=detail.repository,workspace=detail.project.path;if(['switch','branch','delete-branch','tag','delete-tag','merge','rebase','cherry-pick','revert'].includes(action)){const value=await ask('Git '+action,'分支、标签或提交引用');if(value===null)return;input.ref=value;}
  if(action==='reset'){const ref=await ask('Reset','目标提交');if(ref===null)return;const mode=await ask('Reset 模式','soft / mixed / hard','mixed');if(mode===null)return;input={ref,mode};}
  if(['continue','abort'].includes(action)){const operation=await ask('整合操作','merge / rebase / cherry-pick / revert',repository.state.some(s=>s.startsWith('rebase'))?'rebase':repository.state.includes('CHERRY_PICK_HEAD')?'cherry-pick':'merge');if(operation===null)return;input.operation=operation;}
  const result=await command('git.execute',{expected_workspace:workspace,action,input:{revision:repository.revision,...input}},id);if(result.snapshot){cache.set(id,{...cache.get(id),repository:result.snapshot});if(selected===id)detail=cache.get(id);}if(selected===id){renderMain();if(!result.ok)error(result.error);}return result;
 }
 async function showDiff(path){const request=++editorRequest,id=selected,token=selectionEpoch;gitFile=path;const value=await command('git.diff',{path,staged:gitStaged,conflict:detail.repository.conflicted.includes(path)},id);if(token!==selectionEpoch||request!==editorRequest||tab!=='git')return;const v=await vendor();if(token!==selectionEpoch||request!==editorRequest)return;gitDiff=value;disposeEditors();const host=el('releaseEditor');host.innerHTML='';diffEditor=v.monaco.editor.createDiffEditor(host,{automaticLayout:true,readOnly:true,renderSideBySide:true,minimap:{enabled:false},fontSize:13,scrollBeyondLastLine:false});diffEditor.setModel({original:v.monaco.editor.createModel(gitDiff.base||'',language(path)),modified:v.monaco.editor.createModel(gitDiff.modified||'',language(path))});el('releaseDiffActions').innerHTML=`<strong>${esc(path)}</strong>${Object.keys(gitDiff.conflicts||{}).length?button('conflict-sides','对比双方')+button('conflict-base','基线 / 当前') : ''}${button('file-history','文件历史')}${button('edit-git-file','编辑文件')}${!gitStaged?button('discard-file','放弃工作区修改'):''}`;
  if(gitDiff.binary){host.innerHTML='<div class="release-empty">二进制或过大文件不按文本显示。可以暂存文件，或使用终端处理。</div>';}const hunks=splitPatch(gitDiff.patch);el('releaseHunks').innerHTML=hunks.map((h,i)=>`<details><summary>${esc(h.label)} ${button('patch-hunk',gitStaged?'撤销暂存此块':'暂存此块',`data-hunk="${i}"`)}</summary><pre>${esc(h.patch)}</pre></details>`).join('');
 }
 async function renderFiles(){const request=++editorRequest;disposeEditors();const id=selected,token=selectionEpoch;const files=await command('files.list',{path:filesPath},id);if(token!==selectionEpoch||request!==editorRequest||tab!=='files')return;el('releaseMain').innerHTML=`<div class="release-files-toolbar"><strong>${esc(filesPath||'工作区')}</strong>${button('parent-dir','上级')}<input id="releaseSourceQuery" placeholder="搜索文件名或内容"><button data-release="search-files" class="secondary-button">搜索</button></div><div class="release-git-layout"><aside id="releaseSourceTree">${files.map(f=>button(f.directory?'directory':'file',`${f.directory?'▸':'·'} ${f.name}`,`data-path="${esc(f.path)}"`)).join('')}</aside><section><div id="releaseFileActions"></div><div id="releaseEditor" class="release-editor"><div class="release-empty">选择文件阅读或编辑。</div></div></section></div>`;}
 async function openFile(path,{repoFile=false}={}){const request=++editorRequest,id=selected,token=selectionEpoch;let relativePath=path;if(repoFile){const repo=detail.repository.root;const root=detail.project.path;if(repo!==root){if(!path.startsWith(root.slice(repo.length+1)+'/'))throw new Error('文件在当前项目目录之外，请在终端或对应项目中编辑。');relativePath=path.slice(root.length-repo.length);}}
  const value=await command('files.read',{path:relativePath},id);const v=await vendor();if(token!==selectionEpoch||request!==editorRequest)return;disposeEditors();const key=id+':'+detail.project.path+':'+relativePath;const draft=drafts.get(key);currentFile={...value,key,project:id,expected_workspace:detail.project.path};const host=el('releaseEditor');host.innerHTML='';editor=v.monaco.editor.create(host,{model:v.monaco.editor.createModel(draft?.text??value.text,language(path),v.monaco.Uri.parse('arcorbit://workspace/'+encodeURIComponent(id+':'+detail.project.path)+'/'+relativePath.split('/').map(encodeURIComponent).join('/'))),automaticLayout:true,minimap:{enabled:false},fontSize:13,scrollBeyondLastLine:false});currentFile.revision=draft?.revision||value.revision;
  const actions=el(tab==='git'?'releaseDiffActions':'releaseFileActions');actions.innerHTML=`<strong>${esc(relativePath)}</strong>${button('save-file','保存')}${button('compare-file','对比磁盘')}${button('reload-file','重新读取')}`;editor.onDidChangeModelContent(()=>{saveEditor();actions.querySelector('strong').textContent=relativePath+(editor.getValue()!==value.text?' · 未保存':'');});
 }
 async function loadChat(){const id=selected;if(!id)return;const workspace=detail.project.path;const key=id+':'+workspace;if(!chats.has(key)){const call=(action,input={})=>api.releaseChat({...input,project_id:id,action,expected_workspace:workspace});const coordinator=createChatStateCoordinator({api:{createChat:i=>call('draft',i),selectChat:i=>call('snapshot',i),deleteChat:()=>Promise.reject(new Error('场景会话保留')),renameChat:()=>Promise.reject(new Error('场景使用项目名称')),interruptChat:i=>call('stop',i),decideChatApproval:i=>call('approval',i),sendChatMessage:i=>call('send',i),chatSnapshot:i=>call('snapshot',i)},normalizeSnapshot:normalizeChatSnapshot,createRequestId:()=>crypto.randomUUID()});await coordinator.initialize(await call('snapshot'));chats.set(key,coordinator);}if(selected!==id)return;chat=chats.get(key);await chat.refresh();renderChat();}
 const conversation=createConversationSurface({element:el('releaseTranscript'),jumpButton:el('releaseJump'),formatTime,performAction,onApproval:(message,decision)=>run(async()=>{const c=chat;await c.decideApproval(message.approval_request_id,decision);renderChat();}),onExternalLink:url=>api.openWorkExternalLink(url)});
 const composer=createConversationComposer({input:el('releaseChatInput'),sendButton:el('releaseChatSend'),stopButton:el('releaseChatStop'),hint:el('releaseChatHint'),performAction:run,onInput:value=>{chat?.setDraft(value);renderChat();},onSend:async()=>{const c=chat;try{await c.send();}finally{renderChat();}},onStop:async()=>{await chat.interruptCurrentSession();renderChat();}});
 function renderChat(){const state=chat?.getState();const session=state?.snapshot.sessions.find(s=>s.id===state.owner.session_id);el('releaseAgentTitle').textContent=`${detail?.project.name||'项目'} · Agent`;el('releaseChatStatus').textContent=state?.error||session?.error||session?.status||'独立项目会话';conversation.render({contextId:session?.id||selected,messages:state?.snapshot.messages||[],emptyHtml:'<div class="release-empty">让 Agent 解释构建失败、检查源码或处理 Git。工具结果与左侧工作台同步。</div>'});composer.render({draft:state?.draft||'',available:!!chat,active:['starting','running','waiting_approval','interrupting'].includes(session?.status),sending:state?.sending,stopping:session?.status==='interrupting',waiting:session?.status==='waiting_approval'});}
 async function startTask(cmd,id=selected){const r=await command('task.start',{command:cmd},id);await refresh();if(selected===id)await openTerminal(r);}
 async function openTerminal(record){const v=await vendor();let item=terminals.get(record.id);if(!item){const node=document.createElement('div');node.className='release-terminal-pane';node.dataset.id=record.id;el('releaseTerminalPanes').append(node);const term=new v.Terminal({convertEol:record.kind!=='terminal',cursorBlink:true,disableStdin:record.kind!=='terminal',scrollback:5000,fontSize:13,fontFamily:'Menlo, monospace',theme:{background:'#101420',foreground:'#d9deeb'}});const fit=new v.FitAddon(),search=new v.SearchAddon();term.loadAddon(fit);term.loadAddon(search);term.loadAddon(new v.WebLinksAddon((_e,url)=>api.openWorkExternalLink(url)));term.open(node);item={record,node,term,fit,search,sequence:record.sequence||0};term.write(record.log||'');term.onData(data=>command('execution.control',{id:record.id,expected_workspace:record.workspace,action:'write',data},record.project_id).catch(e=>error(e.message)));term.onResize(({cols,rows})=>{if(record.kind==='terminal'&&active(item.record.status))command('execution.control',{id:record.id,expected_workspace:record.workspace,action:'resize',cols,rows},record.project_id).catch(()=>{});});terminals.set(record.id,item);item.pending=[];const latest=await command('execution.read',{id:record.id},record.project_id);term.reset();term.write(latest.log||'');item.sequence=latest.sequence||0;item.record=latest;for(const e of item.pending)if(e.sequence>item.sequence){term.write(e.data);item.sequence=e.sequence;}item.pending=null;}terminalId=record.id;el('releaseTerminal').classList.remove('hidden');renderTerminalTabs();setTimeout(()=>fitTerminals(),0);}
 function renderTerminalTabs(){const items=[...terminals.values()].filter(t=>t.record.project_id===selected);if(!items.some(t=>t.record.id===terminalId))terminalId=items.at(-1)?.record.id||'';el('releaseTerminalTabs').innerHTML=items.map(t=>`<span class="${t.record.id===terminalId?'is-active':''}">${button('terminal-tab',t.record.kind==='terminal'?t.record.title:t.record.title.slice(0,25),`data-id="${t.record.id}"`)}${button('terminal-close','×',`data-id="${t.record.id}" aria-label="关闭终端"`)}</span>`).join('');const shown=split?items.slice(-2):items.filter(t=>t.record.id===terminalId);for(const t of terminals.values())t.node.classList.toggle('hidden',!shown.includes(t));el('releaseTerminalPanes').classList.toggle('is-split',split);fitTerminals();}
 function fitTerminals(){for(const t of terminals.values())if(!t.node.classList.contains('hidden')&&visible&&!el('releaseTerminal').classList.contains('hidden')){try{t.fit.fit();}catch{}}}
 async function requireProject(){if(selected)return true;const options=all.projects.filter(p=>scopeIds.includes(p.id)&&p.path);if(!options.length){error('当前范围没有已关联工作区。');return false;}const id=await chooseProject(options);if(!id)return false;await select(id);return true;}
 async function activities(){all=await api.releaseSnapshot();el('releaseMain').innerHTML=`<div class="release-section-title"><h2>本机活动 · 全部可访问项目</h2>${button('return','返回工作台')}</div>${recordsHtml(all.records.filter(r=>active(r.status)))}`;}
 async function handle(b){const name=b.dataset.release;
  if(name==='project')return select(b.dataset.project);if(name==='back')return select('');if(name==='setup')return navigateSetup();if(name==='activities')return activities();if(name==='refresh'){await refresh();return renderMain();}if(name==='return')return renderMain();
  if(name.startsWith('tab:')){tab=name.slice(4);renderMain();return;}if(name==='agent'){if(!await requireProject())return;el('releaseAgent').classList.toggle('hidden');if(!el('releaseAgent').classList.contains('hidden'))await loadChat();fitTerminals();return;}
  if(['terminal','lazygit'].includes(name)){if(!await requireProject())return;const r=await command('terminal.start',{lazygit:name==='lazygit'});await openTerminal(r);return;}
  if(name==='script'){if(navigator.platform.startsWith('Win')){if(!/^[a-zA-Z0-9:._-]+$/.test(b.dataset.script))throw new Error('这个脚本名需要通过终端运行。');return startTask('npm run '+b.dataset.script);}const shellQuote=v=>"'"+v.replaceAll("'","'\\''")+"'";return startTask('npm run '+shellQuote(b.dataset.script));}
  if(['logs','stop','retry','analyze'].includes(name)){const id=b.dataset.project;const r=await command('execution.read',{id:b.dataset.id},id);if(name==='stop'){await command('execution.control',{id:r.id,action:'stop'},id);return refresh();}if(name==='retry'){if(cache.get(id)?.project.path&&cache.get(id).project.path!==r.workspace)throw new Error('原工作区绑定已变化，不能自动重试旧任务。');const fresh=await api.releaseDetail(id);if(fresh.project.path!==r.workspace)throw new Error('原工作区绑定已变化，不能自动重试旧任务。');return startTask(r.command,id);}if(selected!==id)await select(id);if(name==='logs')return openTerminal(r);el('releaseAgent').classList.remove('hidden');await loadChat();chat.setDraft(`请分析并修复这次执行失败。任务 ID：${r.id}\n项目：${projectName(id)}\n目录：${r.workspace}\n命令：${r.command}\n退出码：${r.exit_code}\n请通过 release_task 读取真实日志，检查源码后修改，并重新验证。`);renderChat();return;}
  if(name==='hide-terminal'){el('releaseTerminal').classList.add('hidden');return;}if(name==='split'){split=!split;renderTerminalTabs();return;}if(name==='terminal-tab'){terminalId=b.dataset.id;renderTerminalTabs();return;}
  if(name==='terminal-close'){const item=terminals.get(b.dataset.id);if(active(item.record.status)){if(!await confirmDialog('关闭终端','仍有程序运行。关闭会停止该会话。'))return;await command('execution.control',{id:item.record.id,action:'stop'},item.record.project_id);}item.term.dispose();item.node.remove();terminals.delete(item.record.id);renderTerminalTabs();return;}
  if(name==='clear-terminal'){terminals.get(terminalId)?.term.clear();return;}if(name==='search-terminal'){const q=await ask('搜索终端','搜索文本');if(q)terminals.get(terminalId)?.search.findNext(q);return;}
  if(name==='open-artifact'){const path=await ask('打开本地产物','工作区内相对路径');if(path)return command('artifact.open',{path});return;}
  if(name.startsWith('git:'))return gitAction(name.slice(4));if(name.startsWith('git-mode:')){gitStaged=name.endsWith('index');renderMain();return;}
  if(name==='diff')return showDiff(b.dataset.path);if(['stage-file','unstage-file'].includes(name))return gitAction(name==='stage-file'?'stage':'unstage',{paths:[b.dataset.path]});
  if(['commit','amend'].includes(name)){const result=await gitAction('commit',{message:commitDrafts.get(selected)||'',amend:name==='amend'});if(result?.ok){commitDrafts.set(selected,'');renderMain();}return;}
  if(name==='patch-hunk'){const h=splitPatch(gitDiff.patch)[Number(b.dataset.hunk)];return gitAction('patch',{patch:h.patch,reverse:gitStaged,revision:gitDiff.revision});}
  if(name==='conflict-sides'||name==='conflict-base'){const v=await vendor();const original=name==='conflict-sides'?gitDiff.conflicts.ours:gitDiff.conflicts.base;const modified=name==='conflict-sides'?gitDiff.conflicts.theirs:gitDiff.modified;clearDiffModel();diffEditor?.setModel({original:v.monaco.editor.createModel(original||'',language(gitFile)),modified:v.monaco.editor.createModel(modified||'',language(gitFile))});el('releaseDiffActions').querySelector('strong').textContent=gitFile+(name==='conflict-sides'?' · 左：当前分支 / 右：合入分支':' · 左：基线 / 右：工作区');return;}
  if(name==='file-history'){const id=selected,path=gitFile;const history=await command('git.history',{path},id);if(selected!==id)return;el('releaseHunks').innerHTML='<h3>文件历史</h3>'+history.map(c=>button('history-diff',c.hash.slice(0,7)+' '+c.message,`data-ref="${c.hash}" data-path="${esc(path)}"`)).join('');return;}
  if(name==='history-diff'){const value=await command('git.diff',{path:b.dataset.path,ref:b.dataset.ref});const v=await vendor();if(!diffEditor)return;clearDiffModel();diffEditor.setModel({original:v.monaco.editor.createModel(value.base||'',language(b.dataset.path)),modified:v.monaco.editor.createModel(value.modified||'',language(b.dataset.path))});el('releaseDiffActions').querySelector('strong').textContent=b.dataset.path+' · '+b.dataset.ref.slice(0,7);return;}
  if(name==='compare-file'){saveEditor();const file={...drafts.get(currentFile.key)};const value=await command('files.read',{path:file.path,expected_workspace:file.expected_workspace},file.project);const v=await vendor();if(currentFile?.key!==file.key)return;disposeEditors();const host=el('releaseEditor');host.innerHTML='';diffEditor=v.monaco.editor.createDiffEditor(host,{automaticLayout:true,readOnly:true,minimap:{enabled:false}});diffEditor.setModel({original:v.monaco.editor.createModel(value.text,language(file.path)),modified:v.monaco.editor.createModel(file.text,language(file.path))});el(tab==='git'?'releaseDiffActions':'releaseFileActions').innerHTML=`<strong>左：当前磁盘 / 右：保留草稿</strong>${button('file','返回编辑',`data-path="${esc(file.path)}"`)}`;return;}
  if(name==='discard-file')return gitAction('discard',{paths:[gitFile]});if(name==='edit-git-file')return openFile(gitFile,{repoFile:true});
  if(name==='directory'){filesPath=b.dataset.path;return renderFiles();}if(name==='parent-dir'){filesPath=filesPath.split('/').slice(0,-1).join('/');return renderFiles();}if(name==='file')return openFile(b.dataset.path);
  if(name==='search-files'){const result=await command('files.search',{query:el('releaseSourceQuery').value});el('releaseSourceTree').innerHTML=result.results.map(r=>button('file',`${r.path}:${r.line} ${r.text}`,`data-path="${esc(r.path)}"`)).join('')||'<p>没有匹配项。</p>';return;}
  if(name==='save-file'){saveEditor();const file={...drafts.get(currentFile.key)};const result=await command('files.save',file,file.project);const latest=drafts.get(file.key);if(latest?.text===file.text)drafts.delete(file.key);else if(latest)drafts.set(file.key,{...latest,revision:result.revision});if(currentFile?.key===file.key){currentFile={...currentFile,revision:result.revision};error('已保存','success');}return;}
  if(name==='reload-file'){if(!await confirmDialog('重新读取文件','放弃此编辑器内尚未保存的草稿并重新读取？'))return;const path=currentFile.path;drafts.delete(currentFile.key);editor?.getModel()?.dispose();editor?.dispose();editor=null;currentFile=null;return openFile(path);}
 }
 root.addEventListener('click',e=>{const b=e.target.closest('[data-release]');if(b)run(()=>handle(b));});
 api.onReleaseEvent?.(event=>{if(event.type==='output'){const t=terminals.get(event.id);if(t?.pending){t.pending.push(event);return;}if(t&&event.sequence>t.sequence){t.term.write(event.data);t.sequence=event.sequence;}return;}if(event.record){const t=terminals.get(event.id);if(t)t.record=event.record;}if(event.type==='chat'){const key=[...chats.keys()].find(k=>k===event.project_id+':'+event.workspace);if(key)chats.get(key).refresh().then(()=>{if(chat===chats.get(key))renderChat();}).catch(e=>error(e.message));}else if(visible){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>refresh().catch(e=>error(e.message)),200);}});
 const observer=new ResizeObserver(()=>fitTerminals());observer.observe(el('releaseTerminalPanes'));
 el('releaseResize').onpointerdown=e=>{const start=e.clientY,height=el('releaseTerminal').getBoundingClientRect().height;const move=e=>{root.style.setProperty('--release-terminal-height',Math.max(140,Math.min(600,height+start-e.clientY))+'px');fitTerminals();};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);};
 el('releaseResize').onkeydown=e=>{if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();root.style.setProperty('--release-terminal-height',Math.max(140,Math.min(600,el('releaseTerminal').getBoundingClientRect().height+(e.key==='ArrowUp'?20:-20)))+'px');}};
 window.addEventListener('keydown',e=>{if(visible&&(e.ctrlKey||e.metaKey)&&e.code==='Backquote'){e.preventDefault();el('releaseTerminal').classList.toggle('hidden');fitTerminals();}if(visible&&(e.ctrlKey||e.metaKey)&&e.key==='s'&&editor){e.preventDefault();run(()=>handle({dataset:{release:'save-file'}}));}});
 const polling=setInterval(()=>{if(visible)refresh().catch(()=>{});},5000);
 return {show({active:shown,projectId,workset}){visible=shown;if(!shown)return;scopeId=String(projectId||'all');scopeIds=(workset?.project_ids||[]).map(String);const key=scopeId+':'+workset?.id+':'+scopeIds.join(',');if(key!==contextKey){contextKey=key;run(()=>select(scopeId==='all'?'':scopeId));}else if(!all.projects.length)run(refresh);fitTerminals();},reset(){selectionEpoch++;disposeEditors();selected='';contextKey='';detail=null;all={projects:[],records:[]};chat=null;chats.clear();drafts.clear();commitDrafts.clear();for(const t of terminals.values()){t.term.dispose();t.node.remove();}terminals.clear();conversation.render({contextId:'logout',messages:[]});},destroy(){clearInterval(polling);clearTimeout(refreshTimer);observer.disconnect();composer.destroy();}};
}
export function splitPatch(patch){const lines=patch.split('\n');const first=lines.findIndex(l=>l.startsWith('@@ '));if(first<0||lines.some(l=>l.startsWith('GIT binary patch'))||!lines.some(l=>l.startsWith('--- ')))return [];const header=lines.slice(0,first).join('\n')+'\n';const starts=lines.map((l,i)=>l.startsWith('@@ ')?i:-1).filter(i=>i>=0);return starts.map((start,i)=>({label:lines[start],patch:header+lines.slice(start,starts[i+1]??lines.length).join('\n').replace(/\n*$/,'\n')}));}
function language(path){return ({js:'javascript',mjs:'javascript',cjs:'javascript',ts:'typescript',tsx:'typescript',jsx:'javascript',json:'json',md:'markdown',css:'css',html:'html',py:'python',go:'go'})[path.split('.').pop()]||'plaintext';}
function ask(title,label,value=''){return new Promise(resolve=>{const dialog=document.createElement('dialog');dialog.className='release-dialog';dialog.innerHTML=`<form method="dialog"><h2>${esc(title)}</h2><label>${esc(label)}<input name="value" value="${esc(value)}" autofocus></label><div><button value="cancel" class="secondary-button">取消</button><button value="ok" class="primary-button">确定</button></div></form>`;document.body.append(dialog);dialog.addEventListener('close',()=>{const result=dialog.returnValue==='ok'?dialog.querySelector('input').value:null;dialog.remove();resolve(result);},{once:true});dialog.showModal();});}
function confirmDialog(title,message){return new Promise(resolve=>{const dialog=document.createElement('dialog');dialog.className='release-dialog';dialog.innerHTML=`<form method="dialog"><h2>${esc(title)}</h2><p>${esc(message)}</p><div><button value="cancel" class="secondary-button">取消</button><button value="ok" class="primary-button">继续</button></div></form>`;document.body.append(dialog);dialog.addEventListener('close',()=>{const yes=dialog.returnValue==='ok';dialog.remove();resolve(yes);},{once:true});dialog.showModal();});}
function chooseProject(projects){return new Promise(resolve=>{const dialog=document.createElement('dialog');dialog.className='release-dialog';dialog.innerHTML=`<h2>选择操作项目</h2><p>使用已有工作区</p>${projects.map(p=>button('choose',p.name,`data-id="${p.id}"`)).join('')}<form method="dialog"><button class="secondary-button">取消</button></form>`;document.body.append(dialog);let id=null;dialog.onclick=e=>{const b=e.target.closest('[data-id]');if(b){id=b.dataset.id;dialog.close();}};dialog.onclose=()=>{dialog.remove();resolve(id);};dialog.showModal();});}
