window.ReleaseViews=(()=>{
  const M=window.ReleasePrototype;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const label={running:'构建中',success:'成功',failed:'失败',cancelled:'已停止',interrupted:'已中断',draft:'草稿',published:'已发布',prepared:'已准备',healthy:'运行正常',deploying:'部署中'};
  const pill=(text,kind='')=>`<span class="state-pill ${kind}">${esc(text)}</span>`;
  function button(action,text,cls='secondary',p=null,id='',disabled=false){return `<button data-action="${action}" class="${cls}" ${p?`data-project="${p.id}"`:''} ${id!==''?`data-id="${esc(id)}"`:''} ${disabled?'disabled':''}>${text}</button>`;}
  const heading=(title,description,action='')=>`<div class="page-heading"><div><h1>${title}</h1><p>${description}</p></div>${action}</div>`;
  function buildRows(entries,aggregate=false){return entries.map(({p,b})=>`<div class="build-row ${!aggregate&&p.selectedBuild===b.id?'selected':''}"><span class="row-icon">${b.status==='failed'?'⊘':b.status==='running'?'◌':'▣'}</span><div class="row-main"><strong>${aggregate?esc(p.name)+' <span class="record-separator">/</span> ':''}${esc(b.name)} <span class="muted">#${b.id}</span></strong><small>${esc(b.branch)} · ${esc(b.source)}${b.dirty?' + 工作区修改':''} · ${esc(b.at)}</small>${b.status==='running'?`<div class="progress-track"><div style="width:${b.progress}%"></div></div>`:''}</div>${pill(label[b.status],b.status)}<div class="row-actions">${button('build-detail','查看','',p,b.id)}${b.status==='failed'?button('analyze','✧ 分析失败','link',p,b.id):b.status==='success'?button('run-artifact',p.kind==='app'?'运行':'预览','link',p,b.id):button('stop-build','停止','',p,b.id,b.status!=='running')}</div></div>`).join('');}
  function all(){const projects=M.visible(),running=M.active().filter(a=>projects.some(p=>p.id===a.project.id)),entries=projects.flatMap(p=>p.builds.map(b=>({p,b}))).sort((a,b)=>b.b.id-a.b.id);
    return heading('项目集发布工作台',`${esc(M.workset().name)} · ${projects.length} 个项目，沿用已有本地工作区。`,button('choose-build','＋ 新建构建','primary'))+
      `<div class="overview-metrics"><div><span>本机执行中</span><strong>${running.length}</strong><small>查看范围内</small></div><div><span>需要处理</span><strong>${projects.filter(p=>p.builds[0]?.status==='failed').length}</strong><small>最近构建失败</small></div><div><span>可用构建产物</span><strong>${projects.filter(p=>p.builds.some(b=>b.status==='success')).length}</strong><small>拥有成功构建的项目</small></div></div>`+
      `<div class="section-title"><h3>项目快捷操作</h3><span>项目集只改变查看范围</span></div><div class="project-shortcuts">${projects.map(p=>`<article class="project-shortcut"><div class="shortcut-identity"><span class="project-avatar small">${esc(p.name[0])}</span><div><strong>${esc(p.name)}</strong><small>${p.kind==='app'?'Desktop · macOS':'Web 应用'} · 已绑定本机</small></div>${pill('⑂ '+p.branch)}</div><div class="shortcut-path mono" title="${esc(p.path+'/'+p.cwd)}">${esc(p.path+'/'+p.cwd)}</div><div class="toolbar">${button('open-project','进入工作台','secondary',p)}${button('build',M.busy(p)?'构建中':'构建','primary',p,'',M.busy(p))}${button('start-dev','启动','',p)}</div></article>`).join('')}</div>`+
      `<div class="section-title"><h3>最近构建</h3><span>选择记录查看对应项目的日志、Git 和 Agent</span></div>${entries.length?buildRows(entries.slice(0,8),true):'<div class="empty-note">当前产品集没有项目。可通过顶部现有「管理」调整展示范围。</div>'}`;
  }
  function ownership(p){return `<div class="workspace-note"><span>⌁ ${esc(p.path+'/'+p.cwd)}</span><span>已有本地工作区 · ${p.kind==='app'?'macOS arm64':'Web'}</span></div>`;}
  function local(p){const instances=p.instances.filter(i=>i.running);const recent=p.builds[0];return heading(`${esc(p.name)} · 本地运行`,'从当前工作区构建、运行并验证修改。',button('command-details','查看项目命令','secondary',p))+ownership(p)+
    `<div class="actions-grid"><article class="action-card"><div class="card-top"><span class="action-icon">▷</span><span class="shortcut">DEVELOPMENT</span></div><h3>启动开发版</h3><p>${p.kind==='app'?'打开独立开发实例。':'启动本地开发服务与预览。'}</p><div class="command-preview">${esc(p.dev)}</div>${button('start-dev',instances.some(i=>i.type==='dev')?'查看运行实例':'▷ 启动开发版','secondary',p)}</article><article class="action-card featured"><div class="card-top"><span class="action-icon">▣</span><span class="shortcut">LOCAL BUILD</span></div><h3>${p.kind==='app'?'构建安装包':'构建 Web 产物'}</h3><p>保留本次来源代码、输出与产物。</p><div class="command-preview">${esc(p.command)}</div>${button('build',M.busy(p)?'◌ 正在构建…':'↗ 开始构建','primary',p,'',M.busy(p))}</article></div>`+
    (recent?.status==='failed'?`<div class="attention-banner"><div><strong>最近构建 #${recent.id} 失败</strong><p>${esc(recent.error)}</p></div>${button('analyze','✧ 分析失败','secondary',p,recent.id)}</div>`:'')+
    `<div class="section-title"><h3>运行实例</h3><span>${instances.length} 个 · 仅此设备</span></div>${instances.length?instances.map(i=>`<div class="instance-row"><span class="row-icon">◉</span><div class="row-main"><strong>${esc(i.name)}</strong><small>${esc(i.source)} · ${i.type==='dev'?'当前工作区':'固定构建产物'}</small></div>${pill('运行中','running')}<div class="row-actions">${button('instance-preview',p.kind==='app'?'查看窗口':'打开预览','',p,i.id)}${button('instance-log','日志','',p,i.id)}${button('stop-instance','停止','',p,i.id)}</div></div>`).join(''):'<div class="empty-note">尚无运行实例。可以启动开发版，或运行最近一次成功构建。</div>'}
    <div class="section-title"><h3>最近构建</h3>${button('artifacts','全部记录 →','link',p)}</div>${buildRows(p.builds.slice(0,3).map(b=>({p,b})))}`;}
  function git(p){const f=p.files.find(f=>f.id===p.file)||p.files[0],staged=p.files.filter(f=>f.staged).length;return heading('Git 变更',`${esc(p.name)} · 整个源码工作区`,button('review','✧ 检查变更','secondary',p))+
    `<div class="git-summary"><span>⑂ ${esc(p.branch)} · ${esc(p.revision)}</span><span>${p.files.length} 项修改 · ${p.ahead} 个本地提交待推送</span></div><div class="section-title"><h3>工作区变更</h3>${button('stage-all',staged===p.files.length&&staged?'取消全部暂存':'暂存全部','',p,'',!p.files.length||M.busy(p))}</div>`+
    (f?`<div class="git-layout"><div class="file-list"><div class="file-list-title">${p.files.length} 个文件 · ${staged} 已暂存</div>${p.files.map(file=>`<div class="file ${file.id===f.id?'active':''}"><input type="checkbox" data-stage="${file.id}" data-project="${p.id}" aria-label="暂存 ${esc(file.name)}" ${file.staged?'checked':''} ${M.busy(p)?'disabled':''}>${button('file',esc(file.name),'filename mono',p,file.id)}<em>M</em></div>`).join('')}</div><div><div class="diff-header"><span class="mono">${esc(f.name)}</span>${button('ask-diff','✧ 解释此文件','link',p,f.id)}</div><div class="diff-content">${f.lines.map(([kind,line],i)=>`<div class="diff-line ${kind}"><span class="line-number">${i+1}</span>${kind==='add'?'+':kind==='remove'?'−':' '} ${esc(line)}</div>`).join('')}</div></div></div><form id="commit-form" class="commit-box" data-project="${p.id}"><input id="commit-message" aria-label="提交说明" placeholder="提交说明…" value="${esc(p.commitDraft)}"><button type="submit" class="primary" ${!staged||M.busy(p)?'disabled':''}>提交${staged?' ('+staged+')':''}</button></form>`:'<div class="empty-note">✓ 工作区干净，所有修改已提交。</div>')+
    `<div class="commit-actions">${button('push-confirm',`推送${p.ahead?' '+p.ahead+' 个提交':''}`,'secondary',p,'',!p.ahead||M.busy(p))}${button('branch','切换分支','secondary',p)}</div><div class="section-title"><h3>提交记录</h3><span>本地提交与远端推送分别记录</span></div>${p.commits?p.commits.map(c=>`<div class="history-row"><span class="online-dot"></span><code>${c.hash||c.revision}</code><span>${esc(c.message)}</span><small>${c.at}</small></div>`).join(''):`<div class="history-row"><code>${p.revision}</code><span>最近同步的源码基线</span></div>`}`;}
  function artifacts(p){const b=M.currentBuild(p);return heading('构建与产物',`${esc(p.name)} · 每次执行都保留独立来源与结果。`,button('build','＋ 新建构建','primary',p,'',M.busy(p)))+
    (b?`<div class="build-detail"><div class="release-top"><div><h2>${esc(b.name)} #${b.id}</h2><p>${esc(p.name)} · ${esc(b.at)} · ${esc(b.duration||'执行中')}</p></div>${pill(label[b.status],b.status)}</div><dl class="facts"><div><dt>开始时的源码</dt><dd class="mono">${esc(b.source)}${b.dirty?' + 工作区修改':''}</dd></div><div><dt>执行项目</dt><dd>${esc(p.name)}</dd></div><div><dt>工作目录</dt><dd class="mono path-wrap">${esc(b.cwd)}</dd></div><div><dt>实际命令</dt><dd class="mono path-wrap">${esc(b.command)}</dd></div></dl>${b.status==='success'?`<div class="artifact-row"><span class="row-icon">▣</span><div class="row-main"><strong>${esc(b.artifact)}</strong><small>${p.kind==='app'?'本地未签名安装包':'Web 静态构建产物'} · 模拟文件</small></div><div class="row-actions">${button('run-artifact',p.kind==='app'?'▷ 运行验证':'▷ 预览产物','primary',p,b.id)}${button('artifact-directory','产物目录','secondary',p,b.id)}</div></div>`:b.status==='running'?`<div class="progress-track"><div style="width:${b.progress}%"></div></div>`:`<div class="note">${esc(b.error||'执行已停止，日志仍然保留。')}</div>`}<div class="toolbar">${button('build-log','查看日志','secondary',p,b.id)}${b.status==='failed'?button('analyze','✧ 分析失败','primary',p,b.id):''}${b.status==='running'?button('stop-build','停止构建','danger',p,b.id):button('build','重新构建','secondary',p,'',M.busy(p))}${b.status==='success'?button('release','准备发布 →','link',p):''}</div></div>`:'<div class="empty-note">尚无构建记录。</div>')+
    `<div class="section-title"><h3>构建历史</h3><span>当前项目 · ${p.builds.length} 次</span></div>${buildRows(p.builds.map(b=>({p,b})))}`;}
  function release(p){const r=p.release;return heading('版本发布',`${esc(p.name)} · 沿用项目已有发布流程。`,button('prepare-release',r&&r.status!=='published'?'调整发布准备':'准备发布','primary',p,'',r?.status==='running'))+
    `<div class="source-note">来源：GitHub Releases / Actions（模拟） · 最近发布 ${esc(p.latestRelease)}</div>`+
    (r?`<article class="release-card"><div class="release-top"><div><h2>${esc(r.tag)}</h2><p>已有发布引用 · 固定源码 ${esc(r.revision)}</p></div>${pill(r.status==='prepared'?'待运行发布构建':r.status==='running'?'发布构建中':r.status==='draft'?'远端草稿':r.status==='interrupted'?'待核对':r.status==='published'?'已发布':'构建失败',r.status)}</div><div class="release-steps"><div class="release-step done">01 选择已有引用</div><div class="release-step ${['draft','published'].includes(r.status)?'done':''}">02 发布构建</div><div class="release-step ${r.status==='published'?'done':''}">03 确认发布</div><div class="release-step ${p.environment.version===r.version?'done':''}">04 环境交付</div></div><dl class="facts"><div><dt>发布方式</dt><dd>项目已有 workflow</dd></div><div><dt>输出目标</dt><dd>${p.kind==='app'?'签名包 + draft Release':'Web 产物 + draft Release'}</dd></div><div><dt>关联执行</dt><dd>${r.runId||'尚未开始'}</dd></div><div><dt>当前环境</dt><dd>${esc(p.environment.version)}</dd></div></dl><h3>发布说明</h3><p class="pre-wrap">${esc(r.notes)}</p><div class="toolbar">${r.status==='prepared'||r.status==='interrupted'?button('workflow-confirm',r.status==='interrupted'?'核对并重试构建':'运行发布构建','primary',p):r.status==='draft'?button('publish-confirm','确认发布','primary',p):r.status==='published'?button('environments','查看环境 →','primary',p):pill('正在等待 workflow 结果','running')}${button('ask-release','✧ 检查发布准备','secondary',p)}</div></article>`:'<div class="empty-note">选择项目已有的发布引用，运行发布构建，再审阅远端草稿。</div>')+
    `<div class="note">本地工作区的未提交修改不会进入固定引用的发布构建。这里分别展示本地验证、远端构建、版本发布与环境状态。</div>`;}
  function environments(p){const d=p.environment,r=p.release;return heading('环境维护',`${esc(p.name)} · 部署状态与版本发布分别记录。`)+
    `<article class="environment-card"><div class="environment-top"><div><h2>内部测试环境</h2><p>${p.kind==='app'?'测试版本分发服务':'测试 Web 服务'} · 已有项目环境</p></div>${pill(d.status==='failed'?'最近部署失败':d.status==='interrupted'?'结果待核对':label[d.status]||d.status,d.status)}</div><dl class="facts"><div><dt>当前已确认版本</dt><dd>${esc(d.version)}</dd></div><div><dt>最近操作</dt><dd>${esc(d.at)}</dd></div><div><dt>健康状态</dt><dd>${d.status==='healthy'?'模拟检查通过':d.status==='deploying'?'新版本待验证':'保留上次结果 · 待重新检查'}</dd></div><div><dt>待部署版本</dt><dd>${esc(d.pendingVersion||'—')}</dd></div></dl>${d.status==='failed'?'<div class="note">新版本健康检查未通过，当前版本未切换。可以查看日志后重试。</div>':''}<div class="toolbar">${button('deploy-confirm',d.status==='failed'?'重试部署':'部署已发布版本','primary',p,'',r?.status!=='published'||d.status==='deploying')}${button('environment-log','查看日志','secondary',p)}${button('rollback-confirm','回退版本','secondary',p,'',!d.previous||d.status==='deploying')}</div></article><div class="section-title"><h3>维护记录</h3><span>模拟来源结果</span></div>${d.events.length?d.events.map(e=>`<div class="history-row"><span class="online-dot"></span><span>${esc(e.text)}</span><small>${esc(e.at)}</small></div>`).join(''):'<div class="empty-note">暂无本次演示中的维护操作。</div>'}`;}
  return {esc,button,pill,label,all,local,git,artifacts,release,environments,buildRows};
})();
