import { tmpdir } from 'node:os';
import test from 'node:test';
import assert from 'node:assert/strict';
import { realpath, mkdtemp, writeFile, mkdir, readFile, symlink, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { simpleGit } from 'simple-git';
import { createRepositoryService } from '../src/release/repository-service.mjs';
import { readWorkspaceFile, saveWorkspaceFile, listWorkspaceFiles } from '../src/release/workspace-files.mjs';
import { createReleaseCoordinator } from '../src/release/release-coordinator.mjs';
async function fixture(t){const dir=await realpath(await mkdtemp(join(tmpdir(),'arcorbit-release-test-')));t.after(()=>rm(dir,{recursive:true,force:true}));const root=join(dir,'repo');await mkdir(root);const git=simpleGit(root);await git.init();await git.addConfig('user.name','Release Test');await git.addConfig('user.email','test@example.invalid');await writeFile(join(root,'a.txt'),'one\ntwo\nthree\n');await git.add('.');await git.commit('initial');return {dir,root,git};}
test('file writes preserve concurrent edits and reject symlink escape',async t=>{const f=await fixture(t);const a=await readWorkspaceFile(f.root,'a.txt');await writeFile(join(f.root,'a.txt'),'external');await assert.rejects(saveWorkspaceFile(f.root,{...a,text:'overwrite'}),/其他操作/);assert.equal(await readFile(join(f.root,'a.txt'),'utf8'),'external');await writeFile(join(f.dir,'secret'),'private');await symlink(join(f.dir,'secret'),join(f.root,'outside'));await assert.rejects(readWorkspaceFile(f.root,'outside'),/超出/);assert(!(await listWorkspaceFiles(f.root)).some(f=>f.name==='outside'));});
test('partial staging changes only selected patch and commits actual index',async t=>{const f=await fixture(t),service=createRepositoryService();await writeFile(join(f.root,'a.txt'),'ONE\ntwo\nTHREE\n');let s=await service.snapshot(f.root);const patch='diff --git a/a.txt b/a.txt\n--- a/a.txt\n+++ b/a.txt\n@@ -1,3 +1,3 @@\n-one\n+ONE\n two\n three\n';const staged=await service.execute(f.root,'patch',{revision:s.revision,patch});assert.equal(staged.ok,true,staged.error);assert.equal(await f.git.show([':a.txt']),'ONE\ntwo\nthree\n');s=staged.snapshot;const result=await service.execute(f.root,'commit',{message:'partial',revision:s.revision});assert(result.ok,result.error);assert.equal(await f.git.show(['HEAD:a.txt']),'ONE\ntwo\nthree\n');assert.equal(await readFile(join(f.root,'a.txt'),'utf8'),'ONE\ntwo\nTHREE\n');});
test('destructive confirmation binds args and source revision',async t=>{const f=await fixture(t),service=createRepositoryService();await writeFile(join(f.root,'a.txt'),'changed');const input={paths:['a.txt']};const plan=await service.prepare(f.root,'discard',input);await writeFile(join(f.root,'a.txt'),'new edit');await assert.rejects(service.execute(f.root,'discard',{...input,token:plan.token}),/确认/);assert.equal(await readFile(join(f.root,'a.txt'),'utf8'),'new edit');const next=await service.prepare(f.root,'discard',input);assert((await service.execute(f.root,'discard',{...input,token:next.token})).ok);});
test('merge conflict remains visible and abort restores original branch',async t=>{const f=await fixture(t),service=createRepositoryService();const original=(await f.git.branchLocal()).current;await f.git.checkoutLocalBranch('other');await writeFile(join(f.root,'a.txt'),'other');await f.git.add('.');await f.git.commit('other');await f.git.checkout(original);await writeFile(join(f.root,'a.txt'),'main');await f.git.add('.');await f.git.commit('main');const merged=await service.execute(f.root,'merge',{ref:'other'});assert.equal(merged.ok,false);assert.deepEqual(merged.snapshot.conflicted,['a.txt']);assert(merged.snapshot.state.includes('MERGE_HEAD'));const diff=await service.diff(f.root,{path:'a.txt',conflict:true});assert.equal(diff.conflicts.ours,'main');assert.equal(diff.conflicts.theirs,'other');assert((await service.execute(f.root,'abort',{operation:'merge'})).ok);assert.equal(await readFile(join(f.root,'a.txt'),'utf8'),'main');});
test('monorepo directories resolve to one repository identity and stale revisions fail',async t=>{const f=await fixture(t),service=createRepositoryService();await mkdir(join(f.root,'sub'));assert.deepEqual(await service.identity(f.root),await service.identity(join(f.root,'sub')));await writeFile(join(f.root,'new.txt'),'first');const before=await service.snapshot(f.root);await writeFile(join(f.root,'new.txt'),'second');await assert.rejects(service.execute(f.root,'stage',{paths:['new.txt'],revision:before.revision}),/状态已变化/);});
test('Git diff never follows a repository symlink into external file',async t=>{const f=await fixture(t),service=createRepositoryService();await writeFile(join(f.dir,'secret'),'do not expose');await symlink(join(f.dir,'secret'),join(f.root,'link'));const diff=await service.diff(f.root,{path:'link'});assert(!diff.modified.includes('do not expose'));assert.equal(diff.modified,join(f.dir,'secret'));});
test('Release binds Agent tools and executions to original workspace and rejects rebind',async t=>{const f=await fixture(t);let bound=f.root;let options;const c=createReleaseCoordinator({dataDir:join(f.dir,'state'),getPlatform:async()=>({projects:[{id:'11',name:'A',local_project_path:bound}]}),getAccountScope:async()=> 'user',getSettings:async()=>({}),getCodexExecutable:()=> 'codex',createAdapter:()=>({async *runTurn(call){options=call.options;await options.onThreadBound({threadId:'release-thread'});yield {type:'codex.turn.started',turn_id:'turn'};yield {type:'codex.item.completed',params:{item:{type:'agentMessage',id:'reply',text:'Ready'}}};yield {type:'codex.turn.completed',turn:{status:'completed'}};},close(){},async interrupt(){}})});t.after(()=>c.close());await c.chatAction({project_id:'11',action:'send',text:'read project',client_request_id:'request'});for(let n=0;n<100&&!options;n++)await new Promise(r=>setTimeout(r,20));assert(options.dynamicTools.some(t=>t.name==='release_git'));const state=await options.dynamicToolProvider({tool:'release_context',arguments:{}});assert.equal(state.project.path,f.root);bound=f.dir;await assert.rejects(options.dynamicToolProvider({tool:'release_context',arguments:{}}),/已变化/);});
