/* All operations below are bounded simulation; no native commands or remote calls. */
(()=>{
  'use strict';
  const M=window.ReleasePrototype,V=window.ReleaseViews,$=id=>document.getElementById(id),E=V.esc,B=V.button;
  const timers=new Set(),buildTimers=new Map();let maximized=false,toastTimer,renderedOwner='',renderedMessages='',renderedTerminal='';
  const tabs=[['local','本地运行'],['git','Git 变更'],['artifacts','构建与产物'],['release','版本发布'],['environments','环境维护']];
  const later=(fn,ms)=>{const id=setTimeout(()=>{timers.delete(id);fn();},ms);timers.add(id);return id;};
  function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3000);}
  function notify(p,text,view='artifacts',id=null){M.state.notice={projectId:p.id,text,view,id};renderNotice();M.save();}
  function openDialog(title,body,footer='',p=null){const d=$('dialog');d.dataset.project=p?.id||'';d.innerHTML=`<div class="dialog-heading"><h2 id="dialog-title">${title}</h2><button data-action="close-dialog" aria-label="关闭弹窗">×</button></div><div class="dialog-body">${body}</div>${footer?`<div class="dialog-footer">${footer}</div>`:''}`;if(!d.open)d.showModal();}
  const closeDialog=()=>$('dialog').close();
  function saveScroll(){const p=M.current();if(p)p.scroll[p.view]=$('page-content').scrollTop;}
  function focusProject(p,view=null){if(!p)return;saveScroll();if(M.state.scope!=='all'&&M.state.scope!==p.id)M.state.scope=p.id;M.state.focus=p.id;if(view)p.view=view;maximized=false;render();$('page-content').scrollTop=p.scroll[p.view]||0;}
  function goToActivity(p,view,id){M.state.scope=M.workset().projectIds.includes(p.id)?p.id:'all';if(id&&view==='artifacts')p.selectedBuild=Number(id);focusProject(p,view);}
  function renderNotice(){const n=M.state.notice,el=$('activity-notice');el.hidden=!n;if(n){const p=M.find(n.projectId);el.innerHTML=`<span><strong>${E(p.name)}</strong> · ${E(n.text)}</span><div>${B('open-notice','查看结果 →','link',p,n.id||'')}${B('dismiss-notice','×','')}</div>`;}}
  function renderChrome(){const s=M.state,p=M.current();$('worksetSelect').innerHTML=s.worksets.map(w=>`<option value="${w.id}" ${w.id===s.activeWorkset?'selected':''}>${E(w.name)} · ${w.projectIds.length}</option>`).join('');$('productScopeSelect').innerHTML=`<option value="all">项目集全部 · ${M.visible().length}</option>`+M.visible().map(p=>`<option value="${p.id}">${E(p.name)}</option>`).join('');$('productScopeSelect').value=s.scope;$('scopeTitle').textContent=s.scope==='all'?M.workset().name:M.find(s.scope)?.name||M.workset().name;
    $('contextbar').hidden=!p;$('contextbar').innerHTML=p?`<div><span class="project-avatar small">${E(p.name[0])}</span><strong>${E(p.name)}</strong><span class="context-path">${s.scope==='all'?(M.workset().projectIds.includes(p.id)?'所选记录的项目':'本机活动 · 当前产品集之外'):'已有本地工作区'} · ${E(p.path)}</span></div><div>${B('branch','⑂ '+E(p.branch),'branch-button',p)}${s.scope==='all'?B('back-all','返回全部记录 ×','link'):''}</div>`:'';
    $('workspace-tabs').innerHTML=p?tabs.map(([id,text])=>`<button data-action="view" data-project="${p.id}" data-id="${id}" class="${p.view===id?'active':''}" aria-current="${p.view===id?'page':'false'}">${text}${id==='git'&&p.files.length?`<span class="tab-count">${p.files.length}</span>`:''}</button>`).join(''):'';
    $('workbench').classList.toggle('overview-mode',!p);$('workbench').classList.toggle('hide-agent',s.hideAgent);$('workbench').classList.toggle('hide-terminal',s.hideTerminal);$('workbench').classList.toggle('terminal-max',maximized&&!!p);
    $('activity-toggle').textContent=`◷ 本机活动${M.active().length?' · '+M.active().length:''}`;$('git-status').textContent=p?`${p.name} · ⑂ ${p.branch} · ${p.files.length} 项修改`:`${M.workset().name} · 查看 ${M.visible().length} 个项目`;$('execution-status').textContent=`${M.active().length} 项本机活动 · 跨项目保留`;
    $('terminal-toggle').setAttribute('aria-pressed',String(!!p&&!s.hideTerminal));$('agent-toggle').setAttribute('aria-pressed',String(!!p&&!s.hideAgent));renderNotice();
  }
  function renderPage(){const p=M.current(),scroll=$('page-content').scrollTop;$('page-content').innerHTML=p?V[p.view](p):V.all();$('page-content').scrollTop=scroll;}
  function renderAgent(){const p=M.current();if(!p)return;const ownerChanged=renderedOwner!==p.id;const text=JSON.stringify([p.messages,p.agentBusy]);if(ownerChanged||renderedMessages!==text){const el=$('agent-messages'),nearBottom=el.scrollHeight-el.scrollTop-el.clientHeight<55;el.innerHTML=p.messages.map(m=>`<article class="message ${m.role==='agent'?'from-agent':'user'}"><div class="message-label"><b>${m.role==='agent'?'✧ Agent':'G · 你'}</b><span>${m.at||'刚刚'}</span></div>${m.context?`<div class="message-context">⌁ ${E(m.context)}</div>`:''}<div class="message-body">${E(m.text)}</div>${m.actions?`<div class="message-actions">${m.actions.map(([action,label,id])=>B(action,E(label),'',p,id??'')).join('')}</div>`:''}</article>`).join('')+(p.agentBusy?'<div class="message-body muted">✧ 正在整理当前项目上下文…</div>':'');if(nearBottom||ownerChanged)el.scrollTop=el.scrollHeight;renderedMessages=text;}
    $('agent-title').textContent=p.name+' · Agent';$('agent-session').innerHTML=`<span class="online-dot"></span><span class="session-name">固定归属 · ${E(p.name)}</span><span>本机对话</span>`;$('agent-context').innerHTML=`⌁ ${E(p.context?.label||p.name+' · '+p.branch)} ${p.context?B('clear-context','×','',p):''}`;$('agent-input').value=p.chatDraft;$('agent-form').querySelector('[type=submit]').disabled=p.agentBusy;renderedOwner=p.id;
  }
  function renderTerminal(){const p=M.current();if(!p)return;const t=M.session(p);$('terminal-tabs').innerHTML=p.sessions.map(s=>`<button class="${s.id===t.id?'active':''}" data-action="terminal-tab" data-project="${p.id}" data-id="${s.id}">${s.owner==='执行器'?'◌':'⌁'} ${E(s.name)}</button>`).join('');$('terminal-cwd').textContent=p.name+' · '+t.cwd;$('terminal-owner').textContent=t.owner==='执行器'?'执行器控制 · 输出只读':'你控制 · 可输入';const token=JSON.stringify([p.id,t.id,t.lines]);if(token!==renderedTerminal){const el=$('terminal-output'),bottom=el.scrollHeight-el.scrollTop-el.clientHeight<45,same=el.dataset.session===t.id;el.innerHTML=t.lines.map(l=>`<div class="${l.kind||''}">${E(l.text)}</div>`).join('');if(!same||bottom)el.scrollTop=el.scrollHeight;el.dataset.session=t.id;renderedTerminal=token;}$('terminal-input').disabled=t.owner==='执行器';$('terminal-input').value=t.draft||'';$('terminal-input').placeholder=t.owner==='执行器'?'执行中，可新建手动终端':'输入 help 查看模拟命令';
  }
  function render(){renderChrome();renderPage();renderTerminal();renderAgent();M.save();}
  function refresh(p){if(M.current()?.id===p.id){renderPage();renderTerminal();renderAgent();}else if(!M.current())renderPage();renderChrome();M.save();}
  function message(p,role,text,actions=null,context=null){p.messages.push({role,text,actions,context,at:M.clock()});if(M.current()?.id===p.id)renderAgent();M.save();}
  function attach(p,kind,label,id){p.context={kind,label,id};M.state.hideAgent=false;focusProject(p);renderAgent();}
  function ensureSession(p,id,name,owner='你',cwd=p.path+'/'+p.cwd){let t=p.sessions.find(t=>t.id===id);if(!t){t={id,name,owner,cwd,draft:'',history:[],lines:[]};p.sessions.push(t);}t.owner=owner;p.session=id;M.state.hideTerminal=false;return t;}
  function log(p,t,text,kind=''){t.lines.push({text,kind});if(t.lines.length>400)t.lines.splice(0,t.lines.length-400);if(M.current()?.id===p.id)renderTerminal();M.save();}
  function build(p,fail=false){if(!p){chooseProject('build');return;}if(M.busy(p)){toast(p.name+' 已有构建在执行。');return;}const id=M.state.nextBuild++,b={id,projectId:p.id,name:p.kind==='app'?'本地安装包':'生产构建',status:'running',at:M.clock(),source:p.revision,branch:p.branch,dirty:!!p.files.length,command:p.command,cwd:p.path+'/'+p.cwd,artifact:p.kind==='app'?`release/ArcOrbit-local.${id}-arm64.dmg`:`dist/build-${id}/`,kind:p.kind,progress:0,configRevision:1,fail};p.builds.unshift(b);p.selectedBuild=id;const t=ensureSession(p,`${p.id}-build-${id}`,`构建 #${id}`,'执行器',b.cwd);log(p,t,'❯ '+b.command,'command');log(p,t,`项目 ${p.name} · 源码 ${b.source}${b.dirty?' + 工作区修改':''}`,'dim');refresh(p);
    const steps=['检查依赖与项目资源','执行项目检查','组装资源','生成构建产物','验证产物'];let step=0;
    const tick=()=>{if(b.status!=='running')return;step++;b.progress=step*20;log(p,t,`[${step}/5] ${steps[step-1]}…`);if(fail&&step===3){b.status='failed';b.error='资源清单缺少 renderer/styles.css，未生成产物。';b.duration='4 秒 · 退出码 1';t.owner='你';log(p,t,'ERROR missing resource: renderer/styles.css','error');message(p,'agent',`构建 #${id} 失败。你可以附加该记录的命令、目录和错误日志进行分析。`,[['analyze','分析这次失败',id]]);notify(p,`构建 #${id} 失败`,'artifacts',id);}else if(step===5){b.status='success';b.duration='6 秒 · 退出码 0';t.owner='你';log(p,t,'✓ '+b.artifact+'\n构建完成（模拟）','success');notify(p,`构建 #${id} 完成，可${p.kind==='app'?'运行':'预览'}产物`,'artifacts',id);}else{buildTimers.set(p.id,later(tick,1100));}refresh(p);};buildTimers.set(p.id,later(tick,900));
  }
  function stopBuild(p,id){const b=p.builds.find(b=>b.id===Number(id)&&b.status==='running')||p.builds.find(b=>b.status==='running');if(!b)return;b.status='cancelled';b.error='构建已停止，已有日志保留。';clearTimeout(buildTimers.get(p.id));const t=p.sessions.find(t=>t.id===`${p.id}-build-${b.id}`);t.owner='你';log(p,t,'^C\n构建已停止。','dim');refresh(p);}
  function buildLog(p,id){const b=p.builds.find(b=>b.id===Number(id));if(!b)return;p.session=`${p.id}-build-${b.id}`;M.state.hideTerminal=false;focusProject(p);renderTerminal();}
  function analyze(p,id){const b=p.builds.find(b=>b.id===Number(id))||p.builds.find(b=>b.status==='failed');if(!b||b.status!=='failed'){toast('请选择该项目的失败构建。');return;}p.selectedBuild=b.id;focusProject(p,'artifacts');attach(p,'build',`${p.name} · 构建 #${b.id} · 命令与日志`,b.id);message(p,'user','分析这次失败，给我可以检查的修复方案。',null,p.context.label);message(p,'agent','打包资源清单没有包含 renderer/styles.css。\n\n建议把 renderer/** 加入资源规则，再重新构建。修改只保留在当前工作区，供你检查 Diff 后决定是否提交。',p.fixed?[['git','查看修复'],['build','重新构建']]:[['repair','应用修复并查看 Diff']]);buildLog(p,b.id);}
  function repair(p){if(M.busy(p)){toast('当前工作区正在构建，请完成或停止后再修改。');return;}let f=p.files.find(f=>f.id==='config');if(!f){f={id:'config',name:'build-config.json',staged:false};p.files.push(f);}f.staged=false;f.lines=[['context','{'],['remove','  "files": ["src/**", "resources/**"],'],['add','  "files": ['],['add','    "src/**", "resources/**", "renderer/**"'],['add','  ]'],['context','}']];p.fixed=true;p.file='config';message(p,'user','应用修复，让我检查修改。');message(p,'agent','已补齐 renderer/** 规则。修改尚未提交，右侧对话和中央 Diff 都属于 '+p.name+'。',[['build','重新构建'],['stage-all','暂存变更']]);attach(p,'diff',p.name+' · build-config.json','config');focusProject(p,'git');}
  function launch(p,type,id){const b=type==='artifact'?p.builds.find(b=>b.id===Number(id)&&b.status==='success'):null;if(type==='artifact'&&!b)return;let i=p.instances.find(i=>i.running&&i.type===type&&(type==='dev'||i.buildId===b.id));if(!i){i={id:`${p.id}-instance-${Date.now()}`,type,name:p.name+(type==='dev'?' · 开发版':` · 构建 #${b.id}`),buildId:b?.id||null,source:b?.source||p.revision,running:true};p.instances.push(i);const t=ensureSession(p,i.id,type==='dev'?'开发实例':`产物预览 #${b.id}`,'执行器');log(p,t,'❯ '+(type==='dev'?p.dev:p.kind==='app'?'open '+b.artifact:`preview ${b.artifact}`),'command');log(p,t,p.kind==='app'?'✓ 独立测试实例已启动（模拟）':'✓ 本地预览服务已就绪（模拟）','success');}focusProject(p,'local');refresh(p);instancePreview(p,i.id);}
  function instancePreview(p,id){const i=p.instances.find(i=>i.id===id);if(!i)return;openDialog(p.kind==='app'?'运行实例':'本地产物预览',`<div class="artifacts-banner"><span>◉</span><div><h3>${E(i.name)}</h3><p>${i.running?'运行中':'已停止'} · ${p.kind==='app'?'独立测试数据目录':'本地预览服务'}</p></div></div><p>来源 ${E(i.source)} · ${i.type==='dev'?'当前工作区':`构建 #${i.buildId}`}</p><p>此处为模拟预览；真实实现打开对应应用窗口或预览地址。</p>`,B('instance-log','查看日志','secondary',p,id)+B('close-dialog','继续工作','primary'),p);}
  function sendAgent(p,text){text=text.trim();if(!text||p.agentBusy)return;const attached=p.context?{...p.context}:null;p.chatDraft='';p.agentBusy=true;message(p,'user',text,null,attached?.label||p.name+' · '+p.branch);refresh(p);
    later(()=>{p.agentBusy=false;let reply,actions;if(/失败|日志|错误/.test(text)){const b=p.builds.find(b=>b.id===attached?.id&&b.status==='failed')||p.builds.find(b=>b.status==='failed');reply=b?`已经找到 ${p.name} 的失败构建 #${b.id}，可以结合它的命令和资源清单进一步分析。`:'当前项目没有失败构建，可以先检查变更或启动构建。';actions=b?[['analyze','分析失败',b.id]]:[['review','检查变更']];}else if(/发布|版本/.test(text)){reply=`${p.name} 的发布流程使用已存在的固定引用。当前可选 ${p.remoteTag}，源码 ${p.remoteRevision}。\n\n本地修改需要提交、推送并进入新的发布引用后，才会成为正式构建的输入。`;actions=[['prepare-release','查看发布准备'],['git','检查源码']];}else if(/diff|变更|代码|检查/i.test(text)){reply=`当前工作区有 ${p.files.length} 个修改文件。建议检查资源规则，再用项目已有命令 ${p.command} 验证。`;actions=[['git','查看 Git'],['build','构建验证']];}else if(/打包|构建/.test(text)){reply=`将在 ${p.path}/${p.cwd} 运行 ${p.command}。结果固定属于 ${p.name}，切换查看范围不会改变执行目录。`;actions=[['build','开始构建']];}else{reply=`这条消息保留在 ${p.name} 对话中。\n这是模拟 Agent，可继续体验源码检查、构建失败分析和发布准备。`;actions=[['review','检查变更'],['ask-build','准备构建']];}message(p,'agent',reply,actions);if(M.current()?.id!==p.id)notify(p,'Agent 已回复','local');refresh(p);},1000);
  }
  function chooseProject(action){openDialog('选择本次操作的项目','<p>当前查看项目集全部，请明确这次操作使用哪个已有工作区。</p>'+M.visible().map(p=>`<button class="project-choice" data-action="choose-operation" data-next="${action}" data-project="${p.id}"><span class="project-avatar">${E(p.name[0])}</span><div><strong>${E(p.name)}</strong><small>${E(p.path+'/'+p.cwd)}</small></div><span>→</span></button>`).join(''));}
  function activityDialog(){const active=M.active();openDialog('本机活动',`<p>保留所有项目正在执行的操作，包括当前产品集以外的项目。</p>${active.length?active.map(a=>`<button class="project-choice" data-action="open-activity" data-project="${a.project.id}" data-id="${a.id||''}" data-type="${a.type}"><span class="online-dot"></span><div><strong>${E(a.project.name)} · ${E(a.label)}</strong><small>${E(a.project.path)}${M.workset().projectIds.includes(a.project.id)?'':' · 当前产品集之外'}</small></div><span>查看 →</span></button>`).join(''):'<div class="empty-note">没有正在执行的本机操作。</div>'}`);}
  function prepareRelease(p){const old=p.release;if(old?.status==='running')return;openDialog('准备 '+E(p.name)+' 的发布',`<p>使用项目已有发布引用和 workflow。此操作不会创建或移动 tag。</p><label>已有发布引用<select id="release-tag"><option>${E(p.remoteTag)}</option></select></label><label>对应源码<input value="${E(p.remoteRevision)}" readonly></label><label>发布说明<textarea id="release-notes" rows="3">${E(old?.notes||'完善构建与运行体验，包含此发布引用对应的已提交修改。')}</textarea></label><div class="note">${p.files.length?'当前未提交修改不在此发布引用中。':'使用引用所指向的源码，不依赖本地工作区状态。'}${p.ahead?' 本地还有未推送提交。':''}</div>`,B('close-dialog','取消','secondary')+B('save-release','保存准备','primary',p),p);}
  function workflow(p){const r=p.release;if(!r||!['prepared','interrupted'].includes(r.status))return;r.status='running';r.runId='CI-'+M.state.nextBuild++;const t=ensureSession(p,`${p.id}-${r.runId}`,`发布 ${r.runId}`,'执行器');log(p,t,`[workflow] ${r.tag} → ${r.revision}\n等待远端执行结果（模拟）`,'command');refresh(p);later(()=>{r.status='draft';t.owner='你';log(p,t,'✓ 发布构建通过\n✓ 产物已附加到远端草稿（模拟）','success');notify(p,'发布构建完成，远端草稿待审阅','release');refresh(p);},3200);}
  function deploy(p,fail){const d=p.environment,r=p.release;if(!r||r.status!=='published'||d.status==='deploying')return;d.status='deploying';d.pendingVersion=r.version;d.at=M.clock();const target=r.version,t=ensureSession(p,`${p.id}-environment`,'测试环境','执行器');log(p,t,`[deploy] ${target} → 内部测试环境`,'command');refresh(p);later(()=>{t.owner='你';if(fail){d.status='failed';d.events.unshift({text:`部署 ${target} 失败：新版本健康检查未通过，保留 ${d.version}`,at:M.clock()});log(p,t,'ERROR 新版本健康检查失败；当前版本未切换。','error');notify(p,'部署失败，保留原环境版本','environments');}else{d.previous=d.version!==target?d.version:d.previous;d.version=target;d.status='healthy';d.pendingVersion=null;d.events.unshift({text:`部署 ${target} · 模拟健康检查通过`,at:M.clock()});log(p,t,'✓ 部署与健康检查完成（模拟）','success');notify(p,'测试环境部署完成','environments');}refresh(p);},2000);}
  const actions={
    'close-dialog':closeDialog,'dismiss-notice':()=>{M.state.notice=null;renderChrome();M.save();},
    'open-notice':()=>{const n=M.state.notice;if(n)goToActivity(M.find(n.projectId),n.view,n.id);},
    'open-project':(p)=>focusProject(p,'local'),'back-all':()=>{saveScroll();M.state.focus=null;maximized=false;render();$('page-content').scrollTop=0;},
    view:(p,e)=>focusProject(p,e.dataset.id),local:p=>focusProject(p,'local'),git:p=>focusProject(p,'git'),artifacts:p=>focusProject(p,'artifacts'),release:p=>focusProject(p,'release'),environments:p=>focusProject(p,'environments'),
    'toggle-agent':()=>{const p=M.current();if(!p)return chooseProject('show-agent');M.state.hideAgent=!M.state.hideAgent;renderChrome();M.save();},
    'toggle-terminal':()=>{if(!M.current())return chooseProject('show-terminal');M.state.hideTerminal=!M.state.hideTerminal;maximized=false;renderChrome();M.save();},
    'show-agent':p=>{M.state.hideAgent=false;focusProject(p);},'show-terminal':p=>{M.state.hideTerminal=false;focusProject(p);},
    'maximize-terminal':()=>{maximized=!maximized;renderChrome();},'choose-build':()=>chooseProject('build'),
    'choose-operation':(p,e)=>{closeDialog();focusProject(p);actions[e.dataset.next]?.(p,e);},
    'new-terminal':p=>{const id=`${p.id}-shell-${Date.now()}`;ensureSession(p,id,`zsh ${p.sessions.filter(s=>s.name.startsWith('zsh')).length+1}`);render();$('terminal-input').focus();},
    'terminal-tab':(p,e)=>{p.session=e.dataset.id;renderTerminal();M.save();},'clear-terminal':p=>{M.session(p).lines=[];renderTerminal();M.save();},
    build:p=>build(p),'stop-build':(p,e)=>stopBuild(p,e.dataset.id),'build-log':(p,e)=>buildLog(p,e.dataset.id),'build-detail':(p,e)=>{p.selectedBuild=Number(e.dataset.id);focusProject(p,'artifacts');buildLog(p,e.dataset.id);},
    'start-dev':p=>launch(p,'dev'),'run-artifact':(p,e)=>launch(p,'artifact',e.dataset.id),
    'instance-preview':(p,e)=>instancePreview(p,e.dataset.id),'instance-log':(p,e)=>{closeDialog();p.session=e.dataset.id;M.state.hideTerminal=false;focusProject(p,'local');},
    'stop-instance':(p,e)=>{const i=p.instances.find(i=>i.id===e.dataset.id);if(i){i.running=false;const t=p.sessions.find(t=>t.id===i.id);t.owner='你';log(p,t,'^C\n实例已停止。','dim');refresh(p);}},
    'artifact-directory':(p,e)=>{const b=p.builds.find(b=>b.id===Number(e.dataset.id));if(b)openDialog('产物目录',`<p class="mono path-wrap">${E(b.cwd+'/'+b.artifact)}</p><p>构建 #${b.id} · 源码 ${E(b.source)} · ${E(p.name)}</p><div class="note">演示产物位置；正式实现打开文件管理器。</div>`,B('close-dialog','完成','primary'),p);},
    analyze:(p,e)=>analyze(p,e.dataset.id),repair,review:p=>{attach(p,'git',`${p.name} · ${p.files.length} 个修改文件`);focusProject(p,'git');sendAgent(p,'检查当前变更。');},
    'ask-build':p=>{M.state.hideAgent=false;focusProject(p);sendAgent(p,'帮我准备本地构建。');},'ask-diff':(p,e)=>{const f=p.files.find(f=>f.id===e.dataset.id);attach(p,'diff',`${p.name} · ${f.name}`,f.id);sendAgent(p,'解释这个文件的变更。');},'ask-release':p=>{attach(p,'release',`${p.name} · 发布准备`);sendAgent(p,'检查发布准备。');},'clear-context':p=>{p.context=null;renderAgent();M.save();},
    file:(p,e)=>{p.file=e.dataset.id;renderPage();M.save();},'stage-all':p=>{if(M.busy(p))return;const staged=!p.files.every(f=>f.staged);p.files.forEach(f=>f.staged=staged);refresh(p);},
    branch:p=>openDialog('工作分支',`<p>${E(p.name)} · ${p.files.length?'先提交当前修改后切换分支。':'当前工作区干净。'}</p>`+['main','release/v0.9.0'].map(branch=>`<button class="guide-option" data-action="switch-branch" data-project="${p.id}" data-branch="${branch}" ${p.files.length||M.busy(p)?'disabled':''}>⑂ ${branch}${branch===p.branch?' · 当前':''}</button>`).join(''),'',p),
    'switch-branch':(p,e)=>{if(p.files.length||M.busy(p))return;p.branch=e.dataset.branch;closeDialog();refresh(p);},
    'push-confirm':p=>openDialog('推送本地提交',`<p>项目 ${E(p.name)} · 分支 ${E(p.branch)} · ${p.ahead} 个提交。</p><p>模拟推送到已有仓库。推送源码不会创建发布引用或触发正式发布。</p>`,B('close-dialog','取消','secondary')+B('push','确认模拟推送','primary',p),p),
    push:p=>{if(!p.ahead||M.busy(p))return;p.ahead=0;closeDialog();log(p,ensureSession(p,`${p.id}-git`,'Git'),`✓ ${p.name} / ${p.branch} 已推送（模拟）`,'success');refresh(p);},
    'command-details':p=>openDialog('项目已有命令',`<p>${E(p.name)} · 使用已有本地关联</p><label>工作目录<input readonly value="${E(p.path+'/'+p.cwd)}"></label><label>构建<input readonly value="${E(p.command)}"></label><label>开发运行<input readonly value="${E(p.dev)}"></label><p>命令取自项目脚本，此原型沿用已配置操作。</p>`,B('close-dialog','完成','primary'),p),
    activities:activityDialog,'open-activity':(p,e)=>{closeDialog();const type=e.dataset.type;goToActivity(p,type==='build'?'artifacts':type==='release'?'release':type==='environment'?'environments':'local',e.dataset.id);if(type==='build')buildLog(p,e.dataset.id);if(type==='instance'){p.session=e.dataset.id;M.state.hideTerminal=false;render();}if(type==='agent'){M.state.hideAgent=false;render();}},
    'prepare-release':prepareRelease,'save-release':p=>{const notes=$('release-notes').value.trim();if(!notes)return toast('请填写发布说明。');p.release={tag:p.remoteTag,version:p.remoteTag.split('/').pop(),revision:p.remoteRevision,notes,status:'prepared',runId:null};closeDialog();focusProject(p,'release');},
    'workflow-confirm':p=>{const r=p.release;openDialog('运行发布构建',`<dl class="facts"><div><dt>项目</dt><dd>${E(p.name)}</dd></div><div><dt>已有引用</dt><dd>${E(r.tag)}</dd></div><div><dt>源码</dt><dd>${E(r.revision)}</dd></div><div><dt>输出</dt><dd>产物 + 远端发布草稿</dd></div></dl><p>沿用项目 workflow；本原型模拟其进度与结果。</p>`,B('close-dialog','返回','secondary')+B('workflow','确认模拟执行','primary',p),p);},workflow:p=>{closeDialog();workflow(p);},
    'publish-confirm':p=>{if(p.release?.status!=='draft')return;openDialog('发布远端草稿',`<p>${E(p.name)} · ${E(p.release.tag)}</p><p>发布构建 ${E(p.release.runId)} 已通过。发布后版本对目标渠道可见，环境部署仍单独处理。</p>`,B('close-dialog','取消','secondary')+B('publish','确认模拟发布','primary',p),p);},
    publish:p=>{if(p.release?.status!=='draft')return;p.release.status='published';p.latestRelease=p.release.version;closeDialog();refresh(p);},
    'deploy-confirm':p=>{if(p.release?.status!=='published'||p.environment.status==='deploying')return;openDialog('部署到内部测试环境',`<p>项目 ${E(p.name)} · ${E(p.environment.version)} → ${E(p.release.version)}</p><p>健康检查通过后才切换当前版本。</p><label class="checkbox-label"><input id="deploy-failure" type="checkbox"> 体验失败场景：新版本健康检查未通过</label>`,B('close-dialog','取消','secondary')+B('deploy','确认模拟部署','primary',p),p);},deploy:p=>{const fail=$('deploy-failure').checked;closeDialog();deploy(p,fail);},
    'environment-log':p=>{const t=ensureSession(p,`${p.id}-environment`,'测试环境',p.environment.status==='deploying'?'执行器':'你');if(!t.lines.length)log(p,t,`当前已确认版本 ${p.environment.version} · 最近检查 ${p.environment.at}`,'dim');refresh(p);},
    'rollback-confirm':p=>openDialog('回退测试环境',`<p>${E(p.name)} · ${E(p.environment.version)} → ${E(p.environment.previous)}</p>`,B('close-dialog','取消','secondary')+B('rollback','确认模拟回退','primary',p),p),rollback:p=>{const d=p.environment;if(!d.previous||d.status==='deploying')return;d.version=d.previous;d.previous=null;d.status='healthy';d.pendingVersion=null;d.at=M.clock();d.events.unshift({text:`回退至 ${d.version} · 模拟检查通过`,at:d.at});closeDialog();refresh(p);},
    'manage-workset':()=>openDialog('管理 '+E(M.workset().name),`<p>复用现有产品集管理：选择要展示的项目，不改变本地关联或自动执行授权。</p><fieldset class="workset-checks"><legend>展示产品</legend>${M.state.projects.map(p=>`<label><input type="checkbox" name="workset-project" value="${p.id}" ${M.workset().projectIds.includes(p.id)?'checked':''}><span><strong>${E(p.name)}</strong><small>已有本地工作区 · ${E(p.path)}</small></span></label>`).join('')}</fieldset>`,B('close-dialog','取消','secondary')+B('save-workset','保存推进范围','primary')),
    'save-workset':()=>{M.workset().projectIds=[...$('dialog').querySelectorAll('[name=workset-project]:checked')].map(e=>e.value);M.state.scope='all';M.state.focus=null;closeDialog();render();},
    'shell-info':()=>openDialog('现有应用入口','<p>产品反馈、自动领取与左侧其他导航保留为应用壳展示。本原型仅演示 Release 内容及顶部产品观察范围。</p>',B('close-dialog','完成','primary')),
    guide:()=>openDialog('体验新版 Release',`<p>顶部产品集和项目查看沿用已有交互。所有项目已预置本地关联。</p><button class="guide-option" data-action="guide-multi"><strong>01 · A 构建时继续处理 B</strong><small>启动 ArcOrbit 构建 → 顶部查看 Workshop Todo → 本机活动返回 A</small></button><button class="guide-option" data-action="guide-failure"><strong>02 · 从全部记录处理失败</strong><small>选中 ArcOrbit 失败记录 → Agent 分析 → 修复 Diff → 重新构建</small></button><button class="guide-option" data-action="guide-release"><strong>03 · 从远端构建到环境部署</strong><small>Workshop Todo → 已有发布引用 → workflow → 草稿发布 → 部署失败与重试</small></button><div class="note">终端支持 help、pwd、git status、git diff 和当前项目的构建 / 开发命令。面板可折叠、拖动和放大。</div>`),
    'guide-multi':()=>{closeDialog();M.state.activeWorkset='core';M.state.scope='11';focusProject(M.find('11'),'local');build(M.find('11'));toast('现在可从顶部「查看」切换 Workshop Todo，ArcOrbit 继续构建。');},
    'guide-failure':()=>{closeDialog();M.state.activeWorkset='core';M.state.scope='all';const p=M.find('11'),b=p.builds.find(b=>b.status==='failed');if(b)analyze(p,b.id);else{focusProject(p,'local');build(p,true);}},
    'guide-release':()=>{closeDialog();M.state.activeWorkset='core';M.state.scope='12';focusProject(M.find('12'),'release');prepareRelease(M.find('12'));},
    reset:()=>openDialog('重置演示','<p>清除本原型中的操作，恢复预置项目、范围、失败与成功构建。</p>',B('close-dialog','取消','secondary')+B('reset-confirm','重置演示','primary')),
    'reset-confirm':()=>{for(const id of timers)clearTimeout(id);timers.clear();buildTimers.clear();M.reset();maximized=false;renderedOwner='';closeDialog();render();}
  };
  document.addEventListener('click',event=>{const e=event.target.closest('[data-action]');if(!e||e.disabled)return;const p=M.find(e.dataset.project||e.closest('dialog')?.dataset.project)||M.current();actions[e.dataset.action]?.(p,e);});
  $('worksetSelect').addEventListener('change',e=>{saveScroll();M.state.activeWorkset=e.target.value;M.state.scope='all';M.state.focus=null;maximized=false;render();$('page-content').scrollTop=0;});
  $('productScopeSelect').addEventListener('change',e=>{saveScroll();M.state.scope=e.target.value;M.state.focus=null;maximized=false;render();const p=M.current();$('page-content').scrollTop=p?.scroll[p.view]||0;});
  document.addEventListener('change',e=>{if(e.target.matches('[data-stage]')){const p=M.find(e.target.dataset.project);if(M.busy(p))return;const f=p.files.find(f=>f.id===e.target.dataset.stage);f.staged=e.target.checked;refresh(p);}});
  document.addEventListener('input',e=>{const p=M.current();if(!p)return;if(e.target.id==='agent-input')p.chatDraft=e.target.value;if(e.target.id==='commit-message')p.commitDraft=e.target.value;if(e.target.id==='terminal-input')M.session(p).draft=e.target.value;M.save();});
  document.addEventListener('submit',e=>{if(e.target.id!=='commit-form')return;e.preventDefault();const p=M.find(e.target.dataset.project),staged=p.files.filter(f=>f.staged);if(!staged.length||M.busy(p))return;const note=$('commit-message').value.trim();if(!note)return toast('请填写提交说明。');p.revision=Math.random().toString(16).slice(2,9).padEnd(7,'0');p.commits||=[];p.commits.unshift({hash:p.revision,message:note,at:M.clock()});p.ahead++;p.files=p.files.filter(f=>!f.staged);p.commitDraft='';log(p,ensureSession(p,`${p.id}-git`,'Git'),`[${p.branch} ${p.revision}] ${note}\n${staged.length} files changed · 模拟本地提交`,'success');refresh(p);});
  $('agent-form').addEventListener('submit',e=>{e.preventDefault();const p=M.current();if(p)sendAgent(p,$('agent-input').value);});
  $('agent-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();const p=M.current();if(p)sendAgent(p,e.target.value);}});
  $('terminal-form').addEventListener('submit',e=>{e.preventDefault();const p=M.current();if(!p)return;const t=M.session(p),command=$('terminal-input').value.trim();if(!command||t.owner==='执行器')return;t.draft='';t.history.push(command);t.historyIndex=t.history.length;log(p,t,'❯ '+command,'command');if(command==='clear')t.lines=[];else if(command==='pwd')log(p,t,t.cwd);else if(command==='help')log(p,t,`模拟命令：\n  pwd / ls / clear\n  git status / git diff / git log --oneline\n  ${p.command}\n  ${p.dev}\n\n当前项目 ${p.name}，目录固定为 ${t.cwd}`,'dim');else if(command==='ls')log(p,t,'src/  resources/  package.json  '+p.artifact);else if(command==='git status')log(p,t,`On branch ${p.branch}\n${p.files.length?p.files.map(f=>(f.staged?'staged':'modified')+'  '+f.name).join('\n'):'nothing to commit, working tree clean'}\n${p.ahead} commits ahead`);else if(command==='git diff')log(p,t,p.files.length?p.files.map(f=>f.name+'\n'+f.lines.map(([kind,line])=>(kind==='add'?'+':kind==='remove'?'-':' ')+line).join('\n')).join('\n'):'没有未提交变更。');else if(command==='git log --oneline')log(p,t,(p.commits||[]).map(c=>(c.hash||c.revision)+' '+c.message).join('\n')||p.revision);else if(command===p.command)build(p);else if(command===p.dev)launch(p,'dev');else log(p,t,'原型未模拟此命令。输入 help 查看支持范围；不会执行真实 Shell。','dim');refresh(p);});
  $('terminal-input').addEventListener('keydown',e=>{if(!['ArrowUp','ArrowDown'].includes(e.key))return;const p=M.current();if(!p)return;e.preventDefault();const t=M.session(p);t.historyIndex=Math.max(0,Math.min(t.history.length,(t.historyIndex??t.history.length)+(e.key==='ArrowUp'?-1:1)));t.draft=t.history[t.historyIndex]||'';e.target.value=t.draft;M.save();});
  document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.code==='Backquote'){e.preventDefault();actions['toggle-terminal']();}});
  $('dialog').addEventListener('click',e=>{if(e.target!==$('dialog'))return;const r=$('dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();});
  function resizeHandle(id,axis,property,min,max,measure){const el=$(id);el.addEventListener('pointerdown',e=>{e.preventDefault();const start=axis==='y'?e.clientY:e.clientX,initial=measure();el.setPointerCapture(e.pointerId);const move=ev=>document.documentElement.style.setProperty(property,Math.max(min,Math.min(max(),initial+start-(axis==='y'?ev.clientY:ev.clientX)))+'px');const stop=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',stop);el.removeEventListener('pointercancel',stop);};el.addEventListener('pointermove',move);el.addEventListener('pointerup',stop);el.addEventListener('pointercancel',stop);});el.addEventListener('keydown',e=>{const keys=axis==='y'?['ArrowDown','ArrowUp']:['ArrowRight','ArrowLeft'];if(keys.includes(e.key)){e.preventDefault();document.documentElement.style.setProperty(property,Math.max(min,Math.min(max(),measure()+(e.key===keys[1]?20:-20)))+'px');}});}
  resizeHandle('terminal-resizer','y','--terminal-height',130,()=>Math.max(130,$('workbench').clientHeight-150),()=>$('terminal').clientHeight);
  resizeHandle('agent-resizer','x','--agent-width',270,()=>Math.min(500,innerWidth*.43),()=>$('agent').clientWidth);
  render();
})();
