import {app,BrowserWindow} from 'electron';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
const directory=dirname(fileURLToPath(import.meta.url));
app.setPath('userData',mkdtempSync(join(tmpdir(),'release-multi-check-')));
app.disableHardwareAcceleration();
app.whenReady().then(async()=>{
 const win=new BrowserWindow({width:1500,height:1000,show:false,webPreferences:{contextIsolation:true,sandbox:true}}),errors=[];
 win.webContents.on('console-message',(_e,level,msg)=>{if(level>=3)errors.push(msg)});
 const evaluate=code=>win.webContents.executeJavaScript(code);
 const delay=ms=>new Promise(r=>setTimeout(r,ms));
 const click=async selector=>{await evaluate(`{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw new Error('Missing: '+${JSON.stringify(selector)});if(e.disabled)throw new Error('Disabled: '+${JSON.stringify(selector)});e.click();}`);await delay(40);};
 const fill=async(selector,value)=>evaluate(`{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));}`);
 const change=async(selector,value)=>{await evaluate(`{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('change',{bubbles:true}));}`);await delay(50);};
 const text=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).innerText`);
 const submit=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).requestSubmit()`);
 const get=code=>evaluate(`(()=>{const M=window.ReleasePrototype;return (${code})})()`);
 const waitFor=async(code,label)=>{for(let i=0;i<100;i++){if(await get(code))return;await delay(100)}throw new Error('Timeout '+label)};
 const shot=async name=>{await delay(250);writeFileSync(join(directory,name),(await win.webContents.capturePage()).toPNG())};
 try{
  await win.loadFile(join(directory,'index.html'));await delay(250);
  assert.equal(await get('M.state.scope'),'all');assert.equal(await get('M.current()'),null);
  assert.match(await text('#page-content'),/ArcOrbit/);assert.match(await text('#page-content'),/Workshop Todo/);assert.match(await text('#page-content'),/Feedback Console/);
  await shot('preview.png');
  await click('#terminal-toggle');assert.match(await text('#dialog'),/选择本次操作的项目/);await click('#dialog [data-action="choose-operation"][data-project="12"]');
  assert.equal(await get('M.state.scope'),'all');assert.equal(await get('M.current().id'),'12');assert.match(await text('#terminal-cwd'),/Workshop/);
  await click('[data-action="back-all"]');
  await change('#productScopeSelect','11');
  await fill('#terminal-input','draft-for-A');await fill('#agent-input','A 草稿保留');
  await change('#productScopeSelect','12');assert.equal(await evaluate(`document.getElementById('terminal-input').value`),'');assert.equal(await evaluate(`document.getElementById('agent-input').value`),'');
  await fill('#agent-input','B 草稿保留');await change('#productScopeSelect','11');assert.equal(await evaluate(`document.getElementById('terminal-input').value`),'draft-for-A');assert.equal(await evaluate(`document.getElementById('agent-input').value`),'A 草稿保留');
  await fill('#terminal-input','pwd');await submit('#terminal-form');assert.match(await text('#terminal-output'),/Projects\/arckit/);
  await click('#page-content [data-action="build"]');const aBuild=await get('M.find("11").builds[0].id');
  await fill('#agent-input','帮我检查本次构建');await submit('#agent-form');
  await change('#productScopeSelect','12');const bCount=await get('M.find("12").builds.length');
  await click('#page-content [data-action="build"]');const bBuild=await get('M.find("12").builds[0].id');
  await click('[data-action="new-terminal"]');await fill('#terminal-input','pwd');await submit('#terminal-form');assert.match(await text('#terminal-output'),/Projects\/workshop/);
  await waitFor('!M.find("11").agentBusy','A Agent completion');assert.equal(await get('M.find("12").chatDraft'),'B 草稿保留');
  assert.equal(await get('M.find("12").messages.some(m=>m.text.includes("将在 ~/Projects/arckit"))'),false);
  await change('#worksetSelect','web');assert.equal(await get('M.state.scope'),'all');assert.equal(await get('M.current()'),null);
  await click('[data-action="activities"]');assert.match(await text('#dialog'),/ArcOrbit/);assert.match(await text('#dialog'),/当前产品集之外/);
  const worksetBefore=await get('JSON.stringify(M.workset().projectIds)');
  await click('#dialog [data-action="open-activity"][data-project="11"][data-type="build"]');assert.equal(await get('M.current().id'),'11');assert.equal(await get('M.state.activeWorkset'),'web');assert.equal(await get('JSON.stringify(M.workset().projectIds)'),worksetBefore);
  await waitFor('M.find("11").builds[0].status==="success" && M.find("12").builds[0].status==="success"','two independent builds');
  assert.equal(await get('M.find("12").builds.length'),bCount+1);assert.equal(await get('M.find("11").builds[0].cwd'),'~/Projects/arckit/runtime/arcorbit');assert.equal(await get('M.find("12").builds[0].cwd'),'~/Projects/workshop/apps/todo-web');
  await change('#worksetSelect','core');
  await click('#page-content [data-action="analyze"][data-project="11"][data-id="1041"]');assert.equal(await get('M.state.scope'),'all');assert.equal(await get('M.current().id'),'11');assert.match(await text('#agent-context'),/ArcOrbit.*1041/);
  await click('#agent-messages [data-action="repair"]');assert.match(await text('#page-content'),/renderer\/\*\*/);await shot('preview-git.png');
  await click('#page-content [data-action="stage-all"]');await fill('#commit-message','fix: include renderer resources');await submit('#commit-form');assert.equal(await get('M.find("11").files.length'),0);assert.equal(await get('M.find("12").ahead'),0);
  await click('#page-content [data-action="push-confirm"]');await click('#dialog [data-action="push"]');assert.equal(await get('M.find("11").ahead'),0);
  await click('#workspace-tabs [data-id="local"]');await click('#page-content [data-action="build"]');await waitFor('M.find("11").builds[0].status==="success"','clean rebuild');
  await click('#workspace-tabs [data-id="artifacts"]');await click('#page-content [data-action="run-artifact"]');assert.match(await text('#dialog'),/独立测试数据目录/);await click('#dialog [data-action="close-dialog"]');await shot('preview-project.png');
  await click('#page-content [data-action="stop-instance"]');assert.equal(await get('M.find("11").instances.some(i=>i.running)'),false);
  await change('#productScopeSelect','12');await click('#workspace-tabs [data-id="release"]');await click('#page-content [data-action="prepare-release"]');await click('#dialog [data-action="save-release"]');
  await click('#page-content [data-action="workflow-confirm"]');await click('#dialog [data-action="workflow"]');
  await change('#productScopeSelect','11');await waitFor('M.find("12").release.status==="draft"','CI draft');assert.equal(await get('M.find("11").release'),null);
  await change('#productScopeSelect','12');await click('#page-content [data-action="publish-confirm"]');await click('#dialog [data-action="publish"]');
  await click('#workspace-tabs [data-id="environments"]');await click('#page-content [data-action="deploy-confirm"]');await click('#deploy-failure');await click('#dialog [data-action="deploy"]');await waitFor('M.find("12").environment.status==="failed"','deployment failure');assert.equal(await get('M.find("12").environment.version'),'v0.8.2');
  await click('#page-content [data-action="deploy-confirm"]');await click('#dialog [data-action="deploy"]');await waitFor('M.find("12").environment.status==="healthy"','deployment retry');assert.equal(await get('M.find("12").environment.version'),'v0.9.0-rc1');
  await click('#page-content [data-action="rollback-confirm"]');await click('#dialog [data-action="rollback"]');assert.equal(await get('M.find("12").environment.version'),'v0.8.2');
  await click('[data-action="manage-workset"]');await click('[name="workset-project"][value="13"]');await click('#dialog [data-action="save-workset"]');assert.equal(await get('M.visible().length'),2);assert.equal(await get('M.find("13").workspace'),'LOCAL-FEEDBACK');
  await change('#productScopeSelect','11');await click('#workspace-tabs [data-id="local"]');await click('#page-content [data-action="build"]');
  await win.reload();await delay(450);assert.equal(await get('M.find("11").builds[0].status'),'interrupted');assert.equal(await get('M.find("12").environment.version'),'v0.8.2');
  const geometry=[];
  for(const [width,height]of [[1500,1000],[1280,850],[1024,768],[760,800],[390,844]]){win.setSize(width,height);await delay(120);const g=await evaluate(`({width:innerWidth,scroll:document.documentElement.scrollWidth,agentOverflow:document.getElementById('agent-messages').scrollWidth>document.getElementById('agent-messages').clientWidth})`);assert.ok(g.scroll<=g.width,JSON.stringify(g));assert.equal(g.agentOverflow,false);geometry.push(g)}
  assert.deepEqual(errors,[]);
  const result={ok:true,checks:['existing workset and global observation controls','all-scope explicit operation target','per-project terminal and Agent drafts','parallel builds and delayed Agent replies stay in origin','cross-workset activity access without membership changes','failure record → analysis → repair → Git commit → rebuild','artifact runtime lifecycle','remote workflow → draft → publication','failed deployment preserves old version → retry → rollback','existing workset manager only changes observation membership','reload marks interrupted local execution','five viewport sizes'],builds:{aBuild,bBuild},geometry,errors};
  writeFileSync(join(directory,'verification.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));app.exit(0);
 }catch(error){console.error(error);console.error(errors);await shot('verification-failure.png');app.exit(1)}
});
