(() => {
  const $=s=>document.querySelector(s), esc=Conversation.escape;
  let filter='all',search='',tab='overview',lastProduct='',toastTimer;
  Concept.state.ui ||= {productTabs:{},chatOpen:{},lifecycleScope:'all'};
  const ui=()=>Concept.state.ui ||= {productTabs:{},chatOpen:{},lifecycleScope:'all'};
  const icons={products:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',today:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18m-13 5h4"/>',idea:'<path d="M9 18h6m-5 3h4M8 15a7 7 0 1 1 8 0l-1 3H9z"/>',folder:'<path d="M3 6a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>',blank:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6m-12 5h8m-12 4h8"/>',org:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-16a3 3 0 0 1 0 6m3 10v-3a6 6 0 0 0-3-5"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>'};
  const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.products}</svg>`;
  const route=()=>{const bits=location.hash.replace(/^#/,'').split('/');return {page:bits[0]||'products',id:bits[1]||''};};
  const selected=()=>Concept.get(route().id);
  const go=(page,id='')=>{location.hash=page+(id?'/'+id:'');};
  function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2800);}
  const status=p=>!p.added?'添加中':p.step==='failed'?'连接待恢复':p.work==='review'?'需要你验收':p.work==='running'?'正在推进':p.work==='paused'?'已暂停':p.stage==='idea'?'Idea':p.work==='accepted'?'待办已验收':'开发中';
  const attention=()=>Support.responsibilities();
  const button=(id,label,primary=false)=>Conversation.action(id,label,primary);
  function sidebar(page){
    const item=(key,label,glyph,href,count='')=>`<a class="nav-item ${key===page?'active':''}" href="${href}">${icon(glyph)}<span class="nav-text">${label}</span>${count?`<span class="count">${count}</span>`:''}</a>`;
    const scope=ui().lifecycleScope||'all';
    return `<aside class="sidebar"><div class="brand"><span class="brand-mark">A</span><span>ArcOrbit</span></div><nav class="nav-group" aria-label="主导航"><div class="nav-label">PERSONAL</div>${item('today','Today','today','#today',attention().length)}${item('chat','Chat','blank','#chat/'+scope)}<div class="nav-label">PRODUCT</div>${item(['product','products'].includes(page)?page:'products','Product','products','#products')}<div class="nav-label">PRODUCT LIFECYCLE</div>${ProductViews.stages.map(([id,label])=>item(page==='add'&&id==='ideas'?'add':id,label,id==='ideas'?'idea':id==='work'?'blank':id==='automation'?'settings':id==='release'?'folder':'products','#'+id+'/'+scope)).join('')}<div class="nav-label">ORGANIZATION</div><button class="nav-item" data-action="organization">${icon('org')}<span class="nav-text">Organization</span></button>${item('engineering','Engineering','settings','#engineering/'+scope)}</nav><div class="sidebar-bottom"><button class="nav-item" data-action="settings">${icon('settings')}<span class="nav-text">设置</span></button><div class="account"><span class="avatar">G</span><div><strong>Glare</strong><small>个人工作空间</small></div></div></div></aside>`;
  }
  function topbar(breadcrumb,actions=''){return `<div class="topbar"><div class="breadcrumbs">${breadcrumb}</div><div class="actions">${actions}</div></div>`;}
  function card(p){const progress=p.work==='review'?'已有结果，等待你验收':p.work==='running'?'正在完成当前工作':p.step==='failed'?'远程项目已建立，目录待恢复':!p.added?'继续刚才的添加':p.stage==='idea'?'从当前想法继续完善':p.work==='accepted'?'当前工作已验收，可继续下一步':'下一步：让现有能力真实可用';return `<a class="product-card" href="#${p.added?'product':'add'}/${p.id}"><div class="card-top"><span class="product-icon">${esc((p.name||'新').slice(0,1))}</span><span class="badge ${p.work==='review'||p.step==='failed'?'strong':''}">${status(p)}</span></div><h2>${esc(p.name||'未命名 Idea')}</h2><p>${esc(p.description||'从空白开始，想法和材料可以慢慢补充。')}</p><div class="card-progress"><span>${progress}</span><span aria-hidden="true">↗</span></div><div class="card-footer"><span>${esc(p.org||'待定归属')}</span><span>${p.remoteId?'共享项目':'仅此设备'}</span></div></a>`;}
  function portfolio(page){const ideas=page==='ideas',ideaScope=ideas?Concept.get(route().id):null;let items=Concept.state.products.filter(p=>(!ideas||(ideaScope?p.id===ideaScope.id:p.stage==='idea'))&&(!search||(p.name+p.description).toLowerCase().includes(search.toLowerCase())));if(filter==='attention')items=items.filter(p=>attention().some(x=>x.p.id===p.id));if(filter==='active')items=items.filter(p=>p.stage!=='idea');if(filter==='idea')items=items.filter(p=>p.stage==='idea');return topbar(`<strong>${ideas?'Idea':'产品'}</strong><span class="muted">/</span><span>${ideaScope?esc(ideaScope.name):'我的全部产品'}</span>`,ideas?`<label class="scope-picker"><span>产品范围</span><select id="lifecycle-scope" aria-label="生命周期页面的产品范围"><option value="all">全部产品</option>${Concept.state.products.filter(x=>x.added).map(x=>`<option value="${x.id}" ${ideaScope?.id===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>${ideaScope?`<a class="button" href="#product/${ideaScope.id}">返回产品主页 ↗</a>`:''}`:'<span class="muted">个人与团队</span>')+`<div class="page-scroll">${ProductViews.sourceNotice()}<div class="page-heading"><div><div class="eyebrow">${ideas?'EVERY PRODUCT STARTS SOMEWHERE':'YOUR PRODUCTS, MOVING FORWARD'}</div><h1>${ideas?'从一个想法开始':'把产品向前推进。'}</h1><p>${ideas?'想法、设计稿或已有 Demo，都可以成为一个产品的起点。':'看清每个产品的现状，接着处理最需要你的一步。'}</p></div>${button('add','＋ 添加 Idea',true)}</div>${!ideas&&attention().length?`<div class="portfolio-intro"><div><h3>${Support.sources().work?attention().length+' 件事项需要你处理':'待办责任待刷新'}</h3><p>查看具体结果，再把工作交还 ArcOrbit。</p></div><a class="button" href="#today">查看需要我处理的</a></div>`:''}<div class="filter-row"><div class="tabs">${[['all','全部'],...ideas?[]:[['active','推进中'],['idea','Idea'],['attention','需要我']]].map(([id,label])=>`<button class="tab ${filter===id?'active':''}" data-filter="${id}">${label}</button>`).join('')}</div><input id="product-search" class="search" placeholder="搜索产品…" aria-label="搜索产品" value="${esc(search)}"></div><div class="product-grid">${items.map(card).join('')}</div>${!items.length?`<div class="empty"><h2>${search?'没有匹配的产品':'这里还没有产品'}</h2><p>${search?'换个关键词，或者清除筛选。':'可以先保存一个想法，不需要准备文件夹。'}</p>${button(search?'clear-search':'add',search?'清除搜索':'添加 Idea')}</div>`:''}</div>`;}
  function field(p,key,label,type='input',options=null,disabled=false){const value=p[key]||'',dirty=p.dirty.includes(key);return `<label class="field"><span class="field-label"><span>${label}</span>${dirty?'<span>你已修改</span>':''}</span>${type==='select'?`<select id="field-${key}" data-field="${key}" ${disabled?'disabled':''}>${options.map(([v,l])=>`<option value="${v}" ${v===value?'selected':''}>${l}</option>`).join('')}</select>`:type==='textarea'?`<textarea id="field-${key}" data-field="${key}" ${disabled?'disabled':''}>${esc(value)}</textarea>`:`<input id="field-${key}" data-field="${key}" value="${esc(value)}" ${disabled?'disabled':''}>`}</label>`;}
  function source(p){return `<section class="section"><div class="section-head"><h3>已有材料</h3>${p.source?'<span class="badge">已添加</span>':''}</div>${p.source?`<div class="material-row">${icon('folder')}<div><strong>${esc(p.source)}</strong><small>${p.demo?'代码 Demo · 演示材料':'仅使用文件名清单 · 模拟分析'}</small></div></div>`:`<div class="inline-note">${p.sourceKind==='blank'?'空白 Idea，可以稍后补充文件夹或设计材料。':'选择已有文件夹，或直接从一个想法开始。'}</div>`}</section>`;}
  function config(p){const locked=p.step==='executing'||Boolean(p.remoteId);return `<section class="section"><div class="section-head"><div><h3>项目接入</h3><p>可以现在准备，也可以在保存 Idea 后继续</p></div>${p.remoteId?'<span class="badge fill">已关联</span>':'<span class="badge">待确定</span>'}</div>${field(p,'org','ArcOrbit 项目归属','select',[['','请选择归属'],['个人','个人'],['拾光工作室','拾光工作室'],['产品实验室','产品实验室']],locked)}<div class="field-note">${p.remoteId?'远程项目：'+esc(p.remoteId):'创建后，你将成为项目负责人。其他成员通过项目邀请加入。'}</div>${field(p,'repoMode','Git 仓库','select',[['keep','沿用已有仓库'],['new','新建 GitHub 私有仓库'],['later','稍后配置']],locked)}${p.repoMode==='keep'?field(p,'repo','已有仓库地址','input',null,locked):p.repoMode==='new'?`<div class="field-row">${field(p,'gitOwner','GitHub 个人 / 组织','select',[['','选择主体'],['glare','glare（个人）'],['shiguang','shiguang（组织）']],locked)}${field(p,'repoName','仓库名','input',null,locked)}</div><div class="field-note">GitHub 主体单独选择，和 ArcOrbit 组织分别管理。</div>`:''}${field(p,'location','本地开发目录','select',[['existing','使用当前目录'],['copy','复制到指定目录'],['later','稍后连接']],p.step==='executing'||p.bound)}${p.location!=='later'?field(p,'path','目录位置','input',null,p.step==='executing'||p.bound):''}<div class="field-note">${p.location==='copy'?'保留原材料，在目标位置建立工作副本。':p.location==='later'?'不影响保存 Idea 或建立远程项目。':'此处为后续开发目录；材料来源仍单独保留。'}</div></section>`;}
  function addContent(p){const busy=Concept.current(p).busy;return `<section class="object-pane"><div class="object-scroll"><div class="section"><div class="eyebrow">A STARTING POINT FOR YOUR PRODUCT</div><h1>添加 Idea</h1><p class="muted">给出已有的，剩下的一起完善。</p></div>${p.step==='empty'?`<section class="section"><div class="source-options"><button class="source-button" data-action="choose-folder">${icon('folder')}<strong>从文件夹开始</strong><small>代码、Demo、原型或设计材料</small></button><button class="source-button" data-action="blank">${icon('blank')}<strong>创建空白 Idea</strong><small>无需文件夹，先留下一个起点</small></button></div><div class="actions"><button class="text-button" data-action="demo-folder">使用 Demo 文件夹体验完整流程 →</button></div></section>`:''}${source(p)}${p.step!=='empty'?`<section class="section"><div class="section-head"><h3>产品内容</h3><span id="save-status" class="muted">${busy?'整理中 · 可直接修改':'已保存草稿'}</span></div>${field(p,'name','名称','input',null,Boolean(p.remoteId)||p.step==='executing')}${field(p,'description','产品说明','textarea')}${p.step==='analyzing'?'<div class="placeholder-lines" aria-label="正在整理"><span></span><span></span></div>':''}</section>${['ready','confirm','executing','failed','paused','complete'].includes(p.step)?config(p):''}`:''}${p.step==='complete'?`<section class="section inline-note"><strong>项目已接入</strong><p>名称与仓库关系关联到共享项目；材料草稿和对话暂留此设备。</p></section>`:''}</div><footer class="object-footer"><small>${busy?'本机草稿已保存，处理仍在继续':'仅此设备 · 可以稍后继续'}</small><div class="actions">${button('save-idea','先保存 Idea')}${p.step==='complete'?button('enter-product','进入产品',true):p.step!=='empty'?`<button class="button primary" data-action="plan" ${busy||p.step==='failed'?'disabled':''}>${p.step==='confirm'?'查看确认方案':'接入项目'}</button>`:''}</div></footer><input id="folder-input" type="file" webkitdirectory multiple hidden></section>`;}
  function addPage(p){return topbar(`<a href="#products">产品</a><span class="muted">/</span><strong>添加 Idea</strong>`,`<span class="badge">${status(p)}</span>${button('save-exit','保存并返回')}`)+`<div class="split-workspace">${addContent(p)}${Conversation.render(p)}</div>`;}
  function resultList(p){return `<ul class="result-list"><li><span>✓</span><div><strong>本机草稿已保存</strong><small>说明、材料与对话保留在此设备</small></div></li><li><span>${p.remoteId?'✓':'○'}</span><div><strong>${p.remoteId?'远程项目已关联':'尚未建立远程项目'}</strong><small>${esc(p.remoteId?p.org+' / '+p.remoteId:'可以在准备好后继续接入')}</small></div></li><li><span>${p.bound?'✓':'○'}</span><div><strong>${p.bound?'本地工作区已连接':'本地工作区待连接'}</strong><small>${esc(p.bound?p.path:'这不影响继续整理产品')}</small></div></li></ul>`;}
  function workCard(p){if(p.work==='none')return `<div class="work-card"><h3>接下来，想让产品有什么变化？</h3><p>可以在右侧表达目标，或先让 ArcOrbit 基于现状提出建议。</p><div class="actions">${button('start-work','一起确定下一步',true)}</div></div>`;const review=p.work==='review',done=p.work==='accepted',running=p.work==='running',paused=p.work==='paused',feedback=p.id==='p-feedback';return `<div class="work-card"><span class="badge ${review?'strong':done?'fill':''}">${review?'等待你验收':done?'已验收':running?'正在推进':paused?'已暂停':'待确认范围'}</span><h3>${feedback?'反馈图片直接查看':'记账数据持久化'}</h3><p>${feedback?'评论中直接展示缩略图，点击查看原图，加载失败后可重试。':'保存新增账单，刷新后恢复记录，并处理初次使用时的空数据。'}</p>${review||done?`<ul class="result-list"><li><span>✓</span><div><strong>${feedback?'缩略图与原图浏览':'新增记录与刷新恢复'}</strong><small>行为检查通过 · 模拟结果</small></div></li><li><span>✓</span><div><strong>${feedback?'加载失败恢复':'空数据初始化'}</strong><small>行为检查通过 · 模拟结果</small></div></li></ul>`:''}<div class="actions">${review?button('accept','验收通过',true)+button('feedback','提出问题'):done?button('new-goal','讨论下一目标'):running?button('stop','停止处理'):paused?button('resume','继续处理',true):button('run-work','确认范围并开始',true)}</div></div>`;}
  const viewHelpers=()=>({topbar,button,field,source,resultList,workCard,status});
  function productPage(p){tab=ui().productTabs[p.id]||'overview';return ProductViews.detail(p,tab,viewHelpers(),Boolean(ui().chatOpen[p.id]));}
  function today(){return TodayViews.render(viewHelpers());}
  function render(){
    const r=route(),p=Concept.get(r.id),focus=document.activeElement,focusId=focus?.id,selection=focus&&'selectionStart'in focus?[focus.selectionStart,focus.selectionEnd]:null;
    const scrolls=[...document.querySelectorAll('.object-scroll,.page-scroll,.conversation-surface')].map(el=>({className:el.className,top:el.scrollTop,bottom:el.scrollHeight-el.scrollTop-el.clientHeight<60}));
    const opened=[...document.querySelectorAll('[data-message] details[open]')].map(el=>el.closest('[data-message]').dataset.message);
    if(p&&lastProduct!==p.id){lastProduct=p.id;tab=ui().productTabs[p.id]||'overview';scrolls.length=0;}
    if(p)ProductViews.defaults(p);
    let html;if(['products','ideas'].includes(r.page))html=portfolio(r.page);else if(r.page==='today')html=today();else if(p&&r.page==='add')html=addPage(p);else if(p&&r.page==='product')html=productPage(p);else if(['work','automation','release','operations','feedback','chat','engineering'].includes(r.page))html=ProductViews.stagePage(r.page,p,viewHelpers());else html=topbar('<strong>没有找到这个产品</strong>')+'<div class="empty"><p>产品可能已从演示数据中重置。</p><a class="button" href="#products">返回产品</a></div>';
    $('#app').innerHTML=sidebar(r.page)+`<main class="main">${html}</main>`;
    for(const s of scrolls){const el=[...document.querySelectorAll('.object-scroll,.page-scroll,.conversation-surface')].find(e=>e.className===s.className);if(el)el.scrollTop=el.classList.contains('conversation-surface')&&s.bottom?el.scrollHeight:s.top;}
    if(!scrolls.length&&$('#chatTranscript'))$('#chatTranscript').scrollTop=$('#chatTranscript').scrollHeight;
    for(const id of opened){const el=document.querySelector(`[data-message="${id}"] details`);if(el)el.open=true;}
    if(focusId){const next=document.getElementById(focusId);if(next){next.focus({preventScroll:true});if(selection&&typeof next.setSelectionRange==='function')try{next.setSelectionRange(...selection);}catch{}}}
    if(Concept.saveError)toast('浏览器未允许持久保存；当前数据仅在本页有效。');
  }
  function modal(title,body,actions='<button class="button primary" data-action="close-dialog">知道了</button>'){const d=$('#dialog');d.innerHTML=`<h2 id="dialog-title">${title}</h2>${body}<div class="actions">${actions}</div>`;d.showModal();}
  function send(){const p=selected(),input=$('#chatInput');if(p&&input&&input.value.trim()){Concept.send(p,input.value);render();const out=$('#chatTranscript');if(out)out.scrollTop=out.scrollHeight;}}
  document.addEventListener('click',event=>{
    const el=event.target.closest('[data-action],[data-tab],[data-filter],[data-prompt],[data-asset]');if(!el)return;
    const p=selected();
    if(el.dataset.filter){filter=el.dataset.filter;render();return;}
    if(el.dataset.tab){tab=el.dataset.tab;if(p)ui().productTabs[p.id]=tab;Concept.save();render();return;}
    if(el.dataset.asset&&p){const titles={definition:'产品定义',design:'交互与设计',decisions:'重要决策'};modal(titles[el.dataset.asset],`<p>所属产品：${esc(p.name)}</p><p>${esc(el.dataset.asset==='definition'?p.description:el.dataset.asset==='design'?(p.source?'来源材料：'+p.source:'尚未添加设计材料'):(p.principles||'尚未记录重要决策'))}</p><p>资料沿用仓库中的原有文档。当前内容可能包含本机草稿，提交成功后才会共享。</p>`);return;}
    if(el.dataset.prompt){if(p){Concept.send(p,el.dataset.prompt);render();}return;}
    const id=el.dataset.action;
    if(p?.conversations.some(c=>c.busy)&&['history','start-work','feedback-to-work','continue-intake'].includes(id)){toast('当前事项正在处理，停止后可以切换协作事项。');return;}
    if(id==='add'){const draft=Concept.create();go('add',draft.id);return;}
    if(id==='close-dialog'){$('#dialog').close();return;}
    if(id==='reset-demo'){Concept.reset();filter='all';search='';$('#dialog').close();go('products');render();toast('演示数据已重置');return;}
    if(id==='organization'){modal('组织 · 配套管理','<p>拾光工作室 · 你是管理员</p><p>产品实验室 · 你是成员</p><p>此概念稿聚焦产品推进；组织成员与项目权限继续由现有治理能力管理。</p>');return;}
    if(id==='settings'){modal('运行环境 · 配套能力','<p>Codex 与项目环境由 ArcOrbit 管理。空白 Idea 可以使用内部工作目录启动协作。</p><p>这里是概念说明，没有连接真实 Codex 或更改本机设置。</p>');return;}
    if(id==='clear-search'){search='';filter='all';render();return;}
    if(SupportUI.action(id,p,{modal,render,toast,ui}))return;
    if(!p)return;
    switch(id){
      case 'choose-folder':$('#folder-input').click();break;
      case 'demo-folder':Concept.analyze(p,'pocket-ledger',true);break;
      case 'blank':Concept.blank(p);setTimeout(()=>$('#field-name')?.focus(),0);break;
      case 'send':send();break;
      case 'save-idea':case 'save-exit':Concept.saveIdea(p);go(id==='save-exit'?'products':'product',id==='save-exit'?'':p.id);toast('Idea 已保存在本机');break;
      case 'plan':Concept.plan(p);setTimeout(()=>{if($('#chatTranscript'))$('#chatTranscript').scrollTop=$('#chatTranscript').scrollHeight;},0);break;
      case 'revise':p.step='ready';Concept.append(p,'system','你选择继续修改接入方案。');Concept.emit(p.id);$('#field-org')?.focus();break;
      case 'confirm':case 'retry':Concept.execute(p);break;
      case 'stop':Concept.stop(p);break;
      case 'resume':Concept.resume(p);break;
      case 'skip-binding':p.location='later';Concept.execute(p);break;
      case 'enter-product':p.added=true;Concept.save();go('product',p.id);break;
      case 'continue-intake':p.currentConversation='intake';Concept.save();go('add',p.id);break;
      case 'start-work':Concept.startWork(p);go('work',p.id);render();break;
      case 'run-work':Concept.workRun(p);break;
      case 'accept':Concept.accept(p);break;
      case 'toggle-product-chat':ui().chatOpen[p.id]=!ui().chatOpen[p.id];if(ui().chatOpen[p.id]&&!p.conversations.some(c=>c.busy))p.currentConversation=Concept.productConversation(p).id;Concept.save();render();break;
      case 'new-iteration':modal('设定当前迭代',`<label class="field"><span>迭代名称</span><input id="iteration-name" value="${esc(p.iterationName||'')}"></label><label class="field"><span>迭代目标</span><textarea id="iteration-goal">${esc(p.iterationGoal||'')}</textarea></label><p>新迭代会使用独立的待办标签。保存后可在 Work 关联工作，再将计划提交到仓库。</p>`,`<button class="button" data-action="close-dialog">取消</button><button class="button primary" data-action="save-iteration">保存本机草稿</button>`);break;
      case 'save-iteration':{const name=$('#iteration-name').value.trim(),goal=$('#iteration-goal').value.trim();if(!name){$('#iteration-name').focus();return;}if(p.iterationName){p.iterationHistory||=[];p.iterationHistory.unshift({name:p.iterationName,goal:p.iterationGoal,tag:p.iterationTag});}Concept.edit(p,'iterationName',name);Concept.edit(p,'iterationGoal',goal);Concept.edit(p,'iterationTag','iteration:'+crypto.randomUUID().slice(0,8));$('#dialog').close();render();toast('迭代草稿已保存在本机；待办尚未关联');break;}
      case 'history':p.currentConversation='intake';ui().chatOpen[p.id]=true;Concept.emit(p.id);break;
      case 'feedback':if(!$('#chatInput')){modal('提出验收问题','<p>这里继续使用原有 Work 的验收问题操作。原型只演示页面归属与导航关系。</p>');break;}$('#chatInput').value='验收发现：';$('#chatInput').focus();Concept.current(p).draft=$('#chatInput').value;Concept.save();break;
      case 'feedback-to-work':Concept.startWork(p);go('work',p.id);Concept.append(p,'system','已把示例反馈“刷新后账单丢失”带入当前工作上下文。');Concept.emit(p.id);break;
      case 'new-goal':p.currentConversation=Concept.productConversation(p).id;Concept.current(p).draft='下一步我希望：';ui().chatOpen[p.id]=true;Concept.save();go('product',p.id);render();break;
      case 'invite':modal('项目成员','<p>当前负责人：Glare</p><p>成员通过项目邀请加入。生成邀请不会直接创建成员关系。</p><p>原型不生成实际邀请码，也不会发送邀请。</p>');break;
    }
  });
  document.addEventListener('input',event=>{const el=event.target,p=selected();if(el.id==='feedback-reply'&&p?.feedback){p.feedback.draft=el.value;Concept.save();}else if(el.id==='product-search'){search=el.value;render();}else if(el.id==='chatInput'&&p){Concept.current(p).draft=el.value;Concept.save();}else if(el.dataset.field&&p){Concept.draftField(p,el.dataset.field,el.value);}});
  document.addEventListener('change',event=>{
    const el=event.target,p=selected();
    if(el.id==='failure-checkbox'){Concept.setFailure(el.checked);return;}
    if(el.id==='today-scope'){ui().todayScope=el.value;Concept.save();render();return;}
    if(el.dataset.source){Support.sources()[el.dataset.source]=!el.checked;Concept.save();render();return;}
    if(el.id==='readonly-repo'){Concept.state.demoRepoReadOnly=el.checked;Concept.save();return;}
    if(el.id==='conflict-repo'){const target=selected()||Concept.get('p-ledger');Support.defaults(target);target.docs.conflict=el.checked;target.docs.remoteVision='让个人和家庭共同管理开支，优先照顾家庭协作。';if(!target.docs.base)target.docs.base={};Concept.emit(target.id);return;}
    if(el.id==='lifecycle-scope'){ui().lifecycleScope=el.value;Concept.save();go(route().page,el.value);return;}
    if(!p)return;
    if(el.dataset.field){Concept.edit(p,el.dataset.field,el.value);return;}
    if(el.id==='conversation-select'){if(p.conversations.some(c=>c.busy)){el.value=p.currentConversation;toast('停止当前处理后可以切换协作事项。');return;}p.currentConversation=el.value;Concept.emit(p.id);return;}
    if(el.id==='folder-input'&&el.files.length){const name=el.files[0].webkitRelativePath.split('/')[0];Concept.analyze(p,name,false);}
  });
  document.addEventListener('keydown',event=>{if(event.target.id==='chatInput'&&event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();send();}});
  $('#demo-options').addEventListener('click',()=>modal('演示选项',`<p>这是本地交互模拟：不会调用真实 Agent，不创建远程项目，不上传或修改所选文件。</p><label><input id="failure-checkbox" type="checkbox" ${Concept.state.failBinding?'checked':''}> 下一次本地目录连接失败</label><hr><p>来源与共享状态演示</p>${[['work','待办 / 项目服务暂不可用'],['feedback','反馈服务暂不可用'],['github','GitHub 暂不可用']].map(([key,label])=>`<label><input type="checkbox" data-source="${key}" ${!Support.sources()[key]?'checked':''}> ${label}</label>`).join('')}<label><input id="readonly-repo" type="checkbox" ${Concept.state.demoRepoReadOnly?'checked':''}> 资料分支不可直接写入</label><label><input id="conflict-repo" type="checkbox" ${(selected()||Concept.get('p-ledger')).docs?.conflict?'checked':''}> 当前产品仓库资料已有新版本</label><p>推荐联动指令：<br>改名为「口袋记账」，仓库沿用<br>放到拾光工作室<br>复制到 ~/Projects/pocket-ledger</p><p>可测试停止、继续、返回列表与刷新恢复。</p>`,`<button class="button" data-action="reset-demo">重置演示数据</button><button class="button primary" data-action="close-dialog">返回体验</button>`));
  document.addEventListener('concept-change',event=>{if(event.detail.id===route().id||['products','ideas','today'].includes(route().page))render();});
  window.addEventListener('hashchange',()=>{if(ProductViews.stages.some(([key])=>key===route().page)){ui().lifecycleScope=route().id||'all';Concept.save();}if(['products','ideas'].includes(route().page)){filter='all';search='';}render();});
  if(!location.hash)location.hash='products';render();
  window.ConceptUI={render,go,toast};
})();
