/* Shared concept message list + composer; mirrors current Chat interaction shape. */
(() => {
  const escape=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const action=(id,label,primary=false)=>`<button class="button ${primary?'primary':''}" data-action="${id}">${label}</button>`;
  function decision(p){
    if(p.currentConversation!=='intake')return '';
    if(p.step==='confirm')return `<div class="decision-card"><span class="badge strong">需要你确认</span><h3>按这份方案接入项目</h3><dl class="key-values"><dt>远程项目</dt><dd>${escape(p.org)} / ${escape(p.name)}</dd><dt>仓库</dt><dd>${p.repoMode==='new'?escape(p.gitOwner+'/'+p.repoName)+' · 新建私有仓库':p.repoMode==='keep'?escape(p.repo):'稍后配置'}</dd><dt>本地目录</dt><dd>${p.location==='later'?'稍后配置':escape(p.path)+(p.location==='copy'?' · 复制到此处':' · 使用现有目录')}</dd><dt>项目成员</dt><dd>你将成为负责人；其他成员后续邀请加入</dd></dl><small>左侧修改会同步更新本方案。</small><div class="actions">${action('confirm','确认并接入',true)}${action('revise','继续修改')}</div></div>`;
    if(p.step==='failed')return `<div class="decision-card"><span class="badge strong">部分完成</span><h3>本地目录尚未连接</h3><p>项目 ${escape(p.remoteId)} 已保存。请修改左侧目录后重试。</p><div class="actions">${action('retry','重试本地连接',true)}${action('skip-binding','稍后连接')}</div></div>`;
    if(p.step==='complete')return `<div class="decision-card"><span class="badge fill">接入完成</span><h3>${escape(p.name)}</h3><p>远程项目已关联 · ${p.bound?'本地工作区已连接':'本地工作区待连接'}</p><div class="actions">${action('enter-product','进入产品',true)}</div></div>`;
    return '';
  }
  function messages(p){const c=Concept.current(p);return c.messages.map(m=>m.role==='tool'?`<article class="chat-message tool" data-message="${m.id}"><details><summary>${escape(m.text)}</summary><p>${escape(m.detail)}</p></details></article>`:`<article class="chat-message ${m.role}" data-message="${m.id}"><div class="chat-message-meta">${m.role==='assistant'?'ArcOrbit':m.role==='user'?'你':'界面操作 / 状态'}</div><div class="chat-message-content">${escape(m.text)}</div></article>`).join('')+decision(p)+(c.busy?'<div class="chat-message system"><span class="pending-dot"></span><small>正在处理，可以停止；你也可以先查看其他产品。</small></div>':'');}
  function welcome(){return `<div class="conversation-welcome"><div class="mark">A</div><h2>从你已有的开始。</h2><p>给我一个文件夹，或说说你想做什么。<br>我会把内容整理在左侧，需要你决定时在这里说明。</p><div class="suggestions"><button class="suggestion" data-prompt="做一个帮助家庭记录日常开支的小产品。">我只有一个想法</button></div></div>`;}
  function render(p){const c=Concept.current(p);return `<aside class="conversation-panel" aria-label="当前产品的协作对话"><div class="conversation-header"><div><h3>一起推进</h3><small>${c.busy?'正在处理':p.step==='paused'||p.work==='paused'?'已暂停，可继续':'对话与左侧内容同步'}</small></div>${p.conversations.length>1?`<select id="conversation-select" aria-label="查看协作事项">${p.conversations.map(x=>`<option value="${x.id}" ${x.id===c.id?'selected':''}>${escape(x.title)}</option>`).join('')}</select>`:'<span class="badge">添加 Idea</span>'}</div><div id="chatTranscript" class="conversation-surface chat-transcript" role="log" aria-live="polite" aria-label="协作消息">${c.messages.length?messages(p):welcome()}</div><footer class="chat-composer"><textarea id="chatInput" rows="3" aria-label="给 ArcOrbit 的要求" placeholder="说说希望产品如何向前推进，也可以修改左侧内容…">${escape(c.draft)}</textarea><div class="chat-composer-foot"><small>Enter 发送 · Shift+Enter 换行</small><div class="composer-actions">${c.busy?action('stop','停止'):p.step==='paused'||p.work==='paused'?action('resume','继续处理'):''}<button id="send-button" class="button primary" data-action="send" ${c.busy?'disabled':''}>发送</button></div></div></footer></aside>`;}
  window.Conversation={escape,action,render,messages};
})();
