/* Product is a projection of existing project, repository and local context. */
(() => {
  const stages=[['ideas','Idea','想法与已有成果'],['work','Work','待办与结果验收'],['automation','Automation','本机执行与介入'],['release','Release','版本发布'],['operations','Operations','运营工作'],['feedback','Feedback','用户反馈']];
  const esc=Conversation.escape, defaults=Support.defaults;
  const link=(page,p,label,cls='button')=>`<a class="${cls}" href="#${page}/${p.id}">${label} ↗</a>`;
  const workLink=p=>`#work/${p.id}/${encodeURIComponent(p.iterationTag||'')}`;
  const lifecycleLinks=p=>stages.map(([id,title,desc])=>`<a class="lifecycle-link" href="#${id}/${p.id}"><strong>${title}<span>↗</span></strong><small>${desc}</small></a>`).join('');
  const docsLabel=p=>p.docs.conflict?'仓库有新版本':p.docs.status==='shared'?'仓库资料已同步':p.repo?'本机草稿 · 待提交':'本机草稿 · 未关联仓库';
  function sourceNotice(){const s=Support.sources();return (!s.work||!s.github||!s.feedback)?`<div class="source-warning">${[!s.work?'待办服务':null,!s.github?'GitHub':null,!s.feedback?'反馈服务':null].filter(Boolean).join('、')}暂不可用。显示最近读取的记录；状态待刷新。<button class="text-button" data-action="refresh-sources">重新读取</button></div>`:'';}
  function docsBar(p){return `<div class="document-status"><div><strong>${docsLabel(p)}</strong><small>${p.docs.status==='shared'?'团队资料以仓库版本为准，协作对话留在此设备。':'修改已保存在此设备，提交成功后才会共享。'}</small></div><div class="actions">${p.repo?`<button class="button" data-action="review-docs">${p.docs.conflict?'核对差异':p.docs.status==='shared'?'查看资料版本':'查看并提交'}</button>`:`<button class="button" data-action="${p.remoteId?'connect-repo':'continue-intake'}">${p.remoteId?'关联已有仓库':'继续接入'}</button>`}</div></div>`;}
  function iteration(p){return `<div class="iteration-summary"><div class="section-head"><div><span class="eyebrow">CURRENT ITERATION</span><h2>${esc(p.iterationName||'尚未设定迭代')}</h2></div><button class="text-button" data-tab="iterations">管理迭代 →</button></div><p>${esc(p.iterationGoal||'先明确接下来想达成的变化。')}</p><div class="summary-foot"><span>${Support.progress(p)}</span>${p.remoteId&&p.iterationTag?`<a class="text-link" href="${workLink(p)}">查看本迭代待办 ↗</a>`:'<small>关联项目和待办后显示进度</small>'}</div></div>`;}
  function overview(p){return `${sourceNotice()}${docsBar(p)}<div class="product-home-grid"><div><section class="section"><div class="section-head"><h3>产品理念</h3><button class="text-button" data-tab="vision">查看与完善 →</button></div><p class="vision-statement">${esc(p.vision||p.description||'这个产品希望给用户带来什么？')}</p><small>${p.audience?'目标用户：'+esc(p.audience):'可以先补充目标用户和核心价值。'}</small></section><section class="section">${iteration(p)}</section><section class="section"><div class="section-head"><h3>当前进展</h3><span class="muted">读取关联来源</span></div><div class="summary-row"><div><span class="badge">待办</span><strong>${!p.remoteId?'接入项目后安排工作':p.work==='review'?'1 项等待你验收':p.work==='accepted'?'当前待办已验收':p.work==='none'?'尚未安排待办':'待推进：'+Support.taskTitle(p)}</strong><small>${Support.sources().work?'具体范围与验收在 Work 处理':'最近记录 · 当前状态待刷新'}</small></div>${link('work',p,'进入 Work','text-link')}</div><div class="summary-row"><div><span class="badge">反馈</span><strong>${p.feedback?(p.feedback.unread?'有一条新消息':'当前没有未读消息'):'暂无已读取的反馈'}</strong><small>消息已读与问题解决分别记录</small></div>${link('feedback',p,'查看反馈','text-link')}</div><div class="summary-row"><div><span class="badge">GitHub</span><strong>${p.releases.length?'最近发布：'+esc(p.releases[0].name):p.repo?'尚无发布记录':'尚未关联仓库'}</strong><small>发布记录来自仓库；运行与上线情况另行确认</small></div>${link('release',p,'查看版本','text-link')}</div><div class="summary-row"><div><span class="badge">此设备</span><strong>${p.work==='running'?'当前事项正在执行':p.work==='paused'?'执行已暂停':'当前没有活动执行'}</strong><small>${p.bound?'已连接本地工作目录':'尚未连接本地工作目录'}</small></div>${link('automation',p,'查看执行','text-link')}</div></section></div><aside class="product-side"><section class="section"><div class="section-head"><h3>核心资产</h3><button class="text-button" data-tab="assets">全部 →</button></div>${[['definition','产品定义','说明与行为规则'],['design','交互与设计','仓库文档与原始材料'],['decisions','重要决策','约束与决策依据']].map(([id,t,d])=>`<button class="asset-link" data-asset="${id}"><strong>${t}</strong><small>${d}</small></button>`).join('')}</section><section class="section"><h3>产品关系</h3><dl class="key-values"><dt>项目</dt><dd>${esc(p.remoteId||'本机 Idea')}</dd><dt>组织</dt><dd>${esc(p.org||'待定')}</dd><dt>成员</dt><dd>${esc(p.members)}</dd><dt>仓库</dt><dd>${esc(p.repo||'未关联')}</dd></dl><button class="text-button" data-tab="connections">查看项目关系 →</button></section><section class="section inline-note"><strong>${p.remoteId?'共享项目 · 本机工作环境':'仅此设备'}</strong><p>${p.remoteId?'项目成员、仓库权限和本机目录分别管理。':'这个 Idea 还没有远程项目，资料与对话暂留在本机。'}</p></section></aside></div><section class="section"><h3>Product Lifecycle</h3><div class="lifecycle-grid">${lifecycleLinks(p)}</div></section>`;}
  function releaseList(p){return p.repo?(p.releases.length?p.releases.map(v=>`<div class="timeline-item"><strong>${esc(v.name)}</strong><p>${esc(v.kind)} · ${esc(v.date)} · GitHub 示例记录</p></div>`).join(''):'<p class="muted">仓库还没有发布记录。当前迭代可继续推进。</p>'):'<p class="muted">关联仓库后显示发布记录。</p>';}
  function content(p,tab,h){
    if(tab==='overview')return overview(p);
    if(tab==='vision')return `${sourceNotice()}${docsBar(p)}<section class="section"><div class="section-head"><div><h2>产品理念</h2><p>先在本机完善，再提交为共享的产品资料。</p></div><span class="badge">仓库资料</span></div><div class="editor-column">${h.field(p,'vision','希望带来的长期价值','textarea')}${h.field(p,'audience','目标用户')}${h.field(p,'principles','产品原则与边界','textarea')}<button class="button" data-action="suggest-vision">让 Agent 整理理念草稿</button></div></section>`;
    if(tab==='iterations')return `${sourceNotice()}${docsBar(p)}<section class="section"><div class="section-head"><div><h2>版本与迭代</h2><p>计划保存在仓库，工作通过待办标签关联。</p></div>${h.button('new-iteration','设定新迭代')}</div><div class="product-home-grid"><div>${h.field(p,'iterationName','当前迭代')}${h.field(p,'iterationGoal','迭代目标','textarea')}<div class="iteration-summary"><span class="badge">${esc(p.iterationTag||'尚未设定关联标签')}</span><h3>${Support.progress(p)}</h3><p>仅统计带有此标签的当前项目待办。</p><div class="actions">${p.remoteId&&p.iterationTag?`<a class="button" href="${workLink(p)}">查看本迭代待办 ↗</a>`:h.button(p.remoteId?'new-iteration':'continue-intake',p.remoteId?'设定迭代':'继续项目接入')}</div></div><div class="inline-note section">更改目标不会自动移动待办。关联工作、执行与验收继续在 Work 和 Automation 中完成。</div>${(p.iterationHistory||[]).length?`<section class="section"><h3>历史计划</h3>${p.iterationHistory.map(x=>`<div class="summary-row"><div><strong>${esc(x.name)}</strong><small>${esc(x.goal)}</small></div></div>`).join('')}</section>`:''}</div><aside class="product-side"><h3>仓库发布记录</h3><div class="timeline">${releaseList(p)}</div>${link('release',p,'进入 Release','text-link')}<div class="inline-note section">迭代完成与版本发布分别记录。</div></aside></div></section>`;
    if(tab==='assets')return `${sourceNotice()}${docsBar(p)}<section class="section"><h2>核心资产</h2><p class="muted">沿用仓库中的已有资料，保留版本历史。</p><div class="asset-grid section">${[['definition','产品定义','产品说明与行为规则'],['design','交互与设计','设计文档与材料目录'],['decisions','重要决策','产品边界与决策依据']].map(([id,t,d])=>`<button class="asset-card" data-asset="${id}"><span class="badge">${p.repo?'仓库资料':'本机材料'}</span><h3>${t}</h3><p>${d}</p><span class="text-link">查看内容 →</span></button>`).join('')}</div><section class="section">${h.field(p,'description','产品说明','textarea')}</section>${h.source(p)}</section>`;
    return `${sourceNotice()}<section class="section"><h2>产品关系</h2><p class="muted">共享身份、资料位置和本机工作环境。</p><div class="connection-grid"><div class="work-card"><span class="badge">团队共享</span><h3>${esc(p.remoteId||'尚未接入项目')}</h3><p>${esc(p.org||'归属待定')} · ${esc(p.members)}</p><div class="actions">${p.remoteId?h.button('organization','管理项目成员'):h.button('continue-intake','继续接入',true)}</div></div><div class="work-card"><span class="badge">仓库资料</span><h3>${p.repo?'已关联 GitHub':'仓库尚未关联'}</h3><p>${esc(p.repo||'可以先使用待办和反馈，资料留在本机。')}</p><small>${docsLabel(p)}</small>${p.remoteId&&!p.repo?`<div class="actions">${h.button('connect-repo','关联已有仓库')}</div>`:''}</div><div class="work-card"><span class="badge">仅此设备</span><h3>${p.bound?'工作目录已连接':'工作目录未连接'}</h3><p>${esc(p.path||'需要执行时再准备本机工作环境。')}</p><small>对话、编辑草稿和运行详情保留在此设备。</small><div class="actions">${h.button('history','查看接入记录')}</div></div></div></section>`;
  }
  function detail(p,tab,h,chatOpen){defaults(p);return h.topbar(`<a href="#products">Product</a><span class="muted">/</span><strong>${esc(p.name)}</strong>`,`<span class="badge">${p.remoteId?'共享项目':'仅此设备'}</span>${h.button('toggle-product-chat',chatOpen?'收起协作':'产品协作')}`)+`<div class="${chatOpen?'split-workspace product-with-chat':'product-full'}"><section class="object-pane"><div class="product-heading"><div><span class="eyebrow">PRODUCT HOME</span><h1>${esc(p.name||'未命名产品')}</h1><p>${esc(p.description||'从这个起点持续完善产品。')}</p></div><span class="badge">${h.status(p)}</span></div><nav class="object-tabs">${[['overview','总览'],['vision','理念'],['iterations','版本迭代'],['assets','核心资产'],['connections','产品关系']].map(([id,label])=>`<button class="object-tab ${tab===id?'active':''}" data-tab="${id}">${label}</button>`).join('')}</nav><div class="object-scroll">${content(p,tab,h)}</div></section>${chatOpen?Conversation.render(p):''}</div>`;}
  function stagePage(page,p,h){
    const title=stages.find(x=>x[0]===page)?.[1]||({chat:'Chat',engineering:'Engineering'}[page]||page);
    const projects=Concept.state.products.filter(x=>x.added);
    const scope=`<label class="scope-picker"><span>产品范围</span><select id="lifecycle-scope" aria-label="生命周期页面的产品范围"><option value="all" ${!p?'selected':''}>全部产品</option>${projects.map(x=>`<option value="${x.id}" ${p?.id===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>`;
    const top=h.topbar(`<strong>${title}</strong><span class="muted">/</span><span>${p?esc(p.name):'全部产品'}</span>`,`${scope}${p?link('product',p,'返回产品主页'):''}`);
    const note=`<div class="bridge-note"><span class="badge strong">原有 ${title} 页面 · 跳转示意</span><p>现有页面继续保留；此处仅演示上下文与结果回流。操作与数据均为模拟。</p></div>`;
    if(!p)return top+`<div class="page-scroll">${note}<h2>选择一个产品</h2>${projects.map(x=>`<div class="summary-row"><strong>${esc(x.name)}</strong>${link(page,x,'进入 '+title)}</div>`).join('')}</div>`;
    defaults(p);
    const shell=body=>top+`<div class="page-scroll">${note}${sourceNotice()}<div class="context-ribbon"><strong>${esc(p.name)}</strong>${link('product',p,'返回产品主页','text-link')}</div>${body}</div>`;
    if(['work','feedback'].includes(page)&&!p.remoteId)return shell(`<div class="empty"><h2>先关联共享项目</h2><p>这个 Idea 目前保存在本机。接入项目后可以使用待办与反馈。</p>${h.button('continue-intake','继续 Idea 接入',true)}</div>`);
    if(page==='work'){
      const tag=decodeURIComponent(location.hash.split('/')[2]||''),match=!tag||Support.matched(p,tag);
      return shell(`<div class="existing-surface"><div class="section-head"><h2>Work</h2><span class="badge">${tag?'标签：'+esc(tag):'当前产品全部待办'}</span></div>${tag&&!match?`<div class="empty"><h3>本迭代尚未关联待办</h3><p>项目已有工作不会自动归入新迭代。</p><a class="button" href="#work/${p.id}">查看项目全部待办</a></div>`:`<div class="existing-columns"><section class="existing-list"><h3>当前产品的工作</h3><div class="work-card"><span class="badge">${esc(p.taskId?'#'+p.taskId:'尚无待办')}</span><h3>${Support.taskTitle(p)}</h3><small>${esc(p.taskTags.join(' · ')||'未关联迭代')}</small></div>${p.iterationTag&&p.work!=='none'&&!Support.matched(p)?`<button class="button" data-action="tag-work" ${!Support.sources().work?'disabled':''}>关联到当前迭代</button>`:''}</section><section><h3>事项详情</h3><fieldset class="source-actions" ${!Support.sources().work?'disabled':''}>${h.workCard(p)}</fieldset><div class="actions">${link('automation',p,'查看 Automation')}${link('feedback',p,'查看关联反馈')}</div></section></div>`}</div>`);
    }
    if(page==='automation')return shell(`<div class="existing-surface"><h2>此设备的执行</h2><p class="muted">${p.work==='running'?'正在执行':p.work==='paused'?'执行已暂停':'当前没有活动执行'} · 当前设备</p><div class="actions">${link('work',p,p.work==='review'?'返回 Work 验收':'查看关联 Work')}${p.work==='running'?h.button('stop','停止模拟执行'):p.work==='paused'?h.button('resume','继续模拟执行'):''}</div></div><div class="stage-conversation">${Conversation.render(p)}</div>`);
    if(page==='feedback'){
      const f=p.feedback;
      return shell(`<div class="existing-surface"><h2>用户反馈</h2>${f?`<div class="work-card"><span class="badge">反馈 #${esc(f.id)} · ${f.unread?'有新消息':'消息已读'}</span><h3>${esc(f.title)}</h3><p>${esc(f.message)}</p><div class="actions"><button class="button" data-action="read-feedback" ${!Support.sources().feedback||!f.unread?'disabled':''}>标为已读</button></div><div class="section"><h3>沟通记录</h3>${f.replies.map(x=>`<div class="inline-note">你：${esc(x)}</div>`).join('')}<label class="field"><span>回复用户</span><textarea id="feedback-reply" placeholder="说明处理进展，或补充需要确认的信息…">${esc(f.draft||'')}</textarea></label><button class="button primary" data-action="reply-feedback" ${!Support.sources().feedback?'disabled':''}>发送回复（模拟）</button></div><div class="summary-row"><div><strong>关联待办 #${esc(f.taskId)}</strong><small>${p.work==='accepted'?'待办已验收，发布情况另行确认':p.work==='review'?'待办已完成，等待验收':'继续跟进关联待办'}</small></div>${link('work',p,'查看待办')}</div></div>`:'<div class="empty">这个项目暂无反馈示例。</div>'}</div>`);
    }
    if(page==='release')return shell(`<div class="existing-surface"><h2>仓库发布记录</h2><div class="timeline">${releaseList(p)}</div><div class="inline-note">待办验收不会自动生成版本发布。发布准备继续在原 Release 页面处理。</div></div>`);
    return shell(`<div class="existing-surface"><h2>${page==='operations'?'运营工作入口':title}</h2><p class="muted">${page==='operations'?'运营任务可以由现有 Work 跟进。本轮没有接入流量、营收或线上健康数据。':'原有能力与独立页面继续保留。'}</p><div class="actions">${link('work',p,'查看相关工作')}${link('product',p,'返回产品')}</div></div>`);
  }
  window.ProductViews={stages,defaults,detail,stagePage,lifecycleLinks,docsBar,sourceNotice};
})();
