const {app,BrowserWindow}=require('electron');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
app.setPath('userData',fs.mkdtempSync('/tmp/arcorbit-interaction-states-'));
app.disableHardwareAcceleration();
app.whenReady().then(async()=>{
 const win=new BrowserWindow({show:false,width:1440,height:1000,webPreferences:{sandbox:true}});
 const errors=[],requests=[],checks=[];
 win.webContents.on('console-message',(_e,level,text)=>{if(level>=3&&!text.includes('Content Security Policy'))errors.push(text);});
 win.webContents.session.webRequest.onBeforeRequest((d,cb)=>{if(/^https?:/.test(d.url))requests.push(d.url);cb({cancel:/^https?:/.test(d.url)});});
 const run=code=>win.webContents.executeJavaScript(code);
 const click=s=>run('document.querySelector('+JSON.stringify(s)+').click()');
 const input=(s,v)=>run('{const el=document.querySelector('+JSON.stringify(s)+');el.value='+JSON.stringify(v)+';el.dispatchEvent(new Event("input",{bubbles:true}));}');
 const submit=s=>run('document.querySelector('+JSON.stringify(s)+').requestSubmit()');
 const scenario=n=>run('window.WorkScenarios.apply('+JSON.stringify(n)+')');
 const wait=()=>new Promise(r=>setTimeout(r,100));
 try{
  await win.loadFile(path.join(__dirname,'default.html'),{query:{autoplay:'off',scenarioTools:'on'}});
  assert.equal(await run('window.WorkModel.key'),'arcorbit-interaction-project-workbench-v1-scenarios');
  const count=await run('window.WorkModel.state.tasks.length');
  await click('[data-action=new]');await input('[name=intent]','重试也只创建一个事情');
  await scenario('failure');await submit('[data-form=new]');
  assert.match(await run('document.querySelector(".form-error").textContent'),/提交失败/);
  assert.equal(await run('window.WorkModel.state.tasks.length'),count);
  await submit('[data-form=new]');assert.equal(await run('window.WorkModel.state.tasks.length'),count+1);
  checks.push('failed creation retains input; retry creates exactly one task');
  await input('.composer textarea','离线保留同一份草稿');
  const messages=await run('window.WorkModel.current().messages.length');
  await scenario('offline');await submit('.composer');
  assert.equal(await run('window.WorkModel.current().messages.length'),messages);
  assert.equal(await run('document.querySelector(".composer textarea").value'),'离线保留同一份草稿');
  await scenario('recover');await submit('.composer');
  assert.ok(await run('window.WorkModel.current().messages.length')>messages);
  checks.push('offline send preserves draft and recovers in same task');
  await click('.message-popover [data-action=close-chat]');await click('[data-action=edit]');
  await input('dialog [name=body]','保留权限失败时的输入');await scenario('permission');await submit('[data-form=edit]');
  assert.match(await run('document.querySelector(".form-error").textContent'),/权限/);
  await scenario('recover');await submit('[data-form=edit]');
  assert.equal(await run('window.WorkModel.current().body'),'保留权限失败时的输入');
  checks.push('permission denial preserves edit and recovers');
  await click('[data-action=edit]');await input('dialog [name=body]','冲突后明确确认的目标');
  await scenario('conflict');await submit('[data-form=edit]');
  assert.match(await run('document.querySelector(".form-error").textContent'),/新的进展/);
  assert.equal(await run('document.querySelector("[name=body]").value'),'冲突后明确确认的目标');
  await click('[data-action=reconcile-version]');
  assert.match(await run('document.querySelector(".form-error").textContent'),/保留权限失败时的输入/);
  await submit('[data-form=edit]');assert.equal(await run('window.WorkModel.current().body'),'冲突后明确确认的目标');
  checks.push('conflict exposes latest facts and requires explicit resubmission');
  await input('.composer textarea','输入法组合中的文本');
  const before=await run('window.WorkModel.current().messages.length');
  await run('document.querySelector(".composer textarea").dispatchEvent(new CompositionEvent("compositionstart",{bubbles:true}));document.querySelector(".composer textarea").dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",metaKey:true,bubbles:true}));window.WorkPrototype.tick();');
  assert.equal(await run('window.WorkModel.current().messages.length'),before);
  assert.equal(await run('document.querySelector(".composer textarea").value'),'输入法组合中的文本');
  await run('document.querySelector(".composer textarea").dispatchEvent(new CompositionEvent("compositionend",{bubbles:true}));');
  checks.push('IME composition cannot submit or replace input');
  await run('document.querySelector(".sidebar-bottom .legacy-pages > button").focus()');
  await click('.sidebar-bottom .legacy-pages > button');
  const links=await run('[...document.querySelectorAll(".sidebar-bottom .legacy-menu a")].map(a=>a.getAttribute("href"))');
  assert.equal(links.length,11);for(const href of links)assert.ok(fs.existsSync(path.resolve(__dirname,href)),href);
  await run('document.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true}))');
  assert.equal(await run('document.querySelector(".sidebar-bottom .legacy-menu").hidden'),true);
  assert.equal(await run('document.activeElement.getAttribute("aria-label")'),'全部页面');
  checks.push('11 local legacy destinations resolve; Escape restores trigger focus');
  for(const mode of ['paused','stopped','failed','external']){
   await scenario(mode);const thread=await run('window.WorkModel.current().thread');
   const action=mode==='paused'?'resume':mode==='external'?'recheck':'recover';
   await click('[data-action='+action+']');
   assert.equal(await run('window.WorkModel.current().mode'),'auto');assert.equal(await run('window.WorkModel.current().thread'),thread);
  }
  checks.push('pause/stop/failure/external-wait recovery keep thread identity');
  const title=await run('window.WorkModel.displayTitle("👨‍👩‍👧‍👦".repeat(70))');
  assert.equal([...new Intl.Segmenter('zh-CN',{granularity:'grapheme'}).segment(title)].length,64);assert.ok(title.endsWith('…'));
  await scenario('empty');assert.equal(await run('window.WorkModel.visible().length'),0);await click('[data-action=clear-filters]');assert.ok(await run('window.WorkModel.visible().length')>0);
  checks.push('grapheme-safe title and empty-filter recovery');
  win.setContentSize(390,950);await wait();assert.ok(await run('document.documentElement.scrollWidth<=innerWidth'));
  assert.equal(await run('getComputedStyle(document.querySelector(".compact-pages")).display'),'block');
  win.setContentSize(1440,1000);win.webContents.setZoomFactor(2);await wait();assert.ok(await run('document.documentElement.scrollWidth<=innerWidth'));
  checks.push('narrow navigation access and 200 percent zoom without page overflow');
  assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
  const report={ok:true,checks,errors,externalRequests:requests,scope:'Local prototype only; no real backend/native-window verification.'};
  fs.writeFileSync(path.join(__dirname,'verification-states.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));app.exit(0);
 }catch(error){console.error(error);app.exit(1);}
});
