const { app, BrowserWindow } = require('electron');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
app.setPath('userData', fs.mkdtempSync(path.join(os.tmpdir(), 'arcorbit-account-')));
app.disableHardwareAcceleration();
app.whenReady().then(async () => {
  const win = new BrowserWindow({ width: 1500, height: 1000, show: false, webPreferences: { sandbox: true, contextIsolation: true } });
  const errors = [], requests = [], checks = [];
  win.webContents.on('console-message', (_e, level, text) => { if (level >= 3 && !text.includes('Content Security Policy')) errors.push(text); });
  win.webContents.session.webRequest.onBeforeRequest((d, cb) => { if (/^https?:/.test(d.url)) requests.push(d.url); cb({ cancel: /^https?:/.test(d.url) }); });
  const run = code => win.webContents.executeJavaScript(code);
  const wait = (ms = 350) => new Promise(resolve => setTimeout(resolve, ms));
  const click = async selector => { await run(`(()=>{const el=document.querySelector(${JSON.stringify(selector)}); if(!el||el.disabled)throw Error('Missing/disabled '+${JSON.stringify(selector)});el.focus();el.click();})()`); await wait(); };
  const input = async (id, value) => run(`(()=>{const el=document.getElementById(${JSON.stringify(id)});el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  const text = id => run(`document.getElementById(${JSON.stringify(id)}).textContent`);
  const shot = async name => { fs.mkdirSync(path.join(__dirname, 'previews'), { recursive: true }); fs.writeFileSync(path.join(__dirname, 'previews', name + '.png'), (await win.webContents.capturePage()).toPNG()); };
  try {
    await win.loadFile(path.join(__dirname, 'default.html'), { query: { autoplay: 'off' } });
    assert.deepEqual(await run('[...document.querySelectorAll(".page-navigation h2")].map(el=>el.textContent)'), ['PERSONAL', 'PRODUCT', 'PRODUCT LIFECYCLE', 'ORGANIZATION']);
    assert.deepEqual(await run('[...document.querySelectorAll(".page-navigation .page-nav-group:first-child a")].map(el=>el.textContent)'), ['Today', 'Chat', 'Thing']);
    await wait(100); await shot('navigation-categories');
    await click('.account-trigger');
    assert.equal(await run('document.querySelector("#account-dialog").open'), true);
    const production = fs.readFileSync(path.resolve(__dirname, '../../../runtime/arcorbit/desktop/renderer/index.html'), 'utf8');
    const section = production.slice(production.indexOf('<div class="settings-sections">'), production.indexOf('<div id="platformActionOverlay"'));
    const required = [...section.matchAll(/<(?:input|select|button)\b[^>]*\bid="([^"]+)"/g)].map(m => m[1]);
    assert.ok(required.length >= 25);
    for (const id of required) assert.equal(await run(`!!document.getElementById(${JSON.stringify(id)})`), true, id);
    checks.push('Four existing navigation groups, Chat/Thing peers, all production account input/select/button IDs present');
    await shot('account-settings');
    await input('taskSourceAuthMode', 'bearer');
    assert.equal(await run('document.getElementById("tokenAuthFields").hidden'), false);
    await input('taskSourceToken', 'local-fixture-token');
    await input('taskSourceAuthMode', 'headers');
    assert.equal(await run('document.getElementById("headerAuthFields").hidden'), false);
    await input('taskSourceSessionId', 'local-fixture-session');
    await input('codexProxyUrl', 'http://127.0.0.1:8899');
    await input('codexChatModel', 'custom-model');
    await input('codexChatEffort', 'custom-effort');
    await click('#codexYoloMode');
    await click('#refreshCodexModelsButton');
    assert.equal(await run('document.getElementById("codexChatModel").value'), 'custom-model');
    await click('#saveCodexSettingsButton');
    assert.equal(await run('window.WorkModel.state.accountSettings.codexChatModel'), 'custom-model');
    assert.equal(await run('window.WorkModel.state.accountSettings.codexProxyUrl'), 'http://127.0.0.1:7890');
    assert.equal(await run('window.WorkModel.state.accountSettings.codexYoloMode'), true);
    checks.push('Model refresh preserves manual draft; Codex-only save excludes proxy/task-source changes');
    await run('window.WorkModel.state.failNext=true');
    await click('#saveSettingsButton');
    assert.match(await text('accountResult'), /失败/);
    assert.equal(await run('document.getElementById("codexProxyUrl").value'), 'http://127.0.0.1:8899');
    await run('window.WorkModel.state.offline=true');
    await click('#saveSettingsButton');
    assert.match(await text('accountResult'), /已保存.*同步未完成/);
    assert.equal(await run('window.WorkModel.state.accountSettings.codexProxyUrl'), 'http://127.0.0.1:8899');
    assert.equal(await run('JSON.stringify(localStorage).includes("local-fixture-token") || JSON.stringify(localStorage).includes("local-fixture-session")'), false);
    await click('#workbenchSyncSettings');
    assert.match(await text('accountResult'), /同步失败/);
    await run('window.WorkModel.state.offline=false');
    await click('#workbenchSyncSettings');
    assert.match(await text('accountResult'), /已同步/);
    checks.push('General save retains input on failure, distinguishes persisted settings from failed sync, excludes fixture secrets from persistence');
    await click('#accountClose');
    assert.equal(await run('document.activeElement.matches(".account-trigger")'), true);
    await click('.account-trigger');
    assert.equal(await run('document.getElementById("codexProxyUrl").value'), 'http://127.0.0.1:8899');
    await click('#logoutButton');
    assert.equal(await run('document.getElementById("logoutConfirmation").hidden'), false);
    await click('#cancelLogout');
    assert.match(await text('authStatusPill'), /已登录/);
    await click('#logoutButton');
    await click('#confirmLogout');
    await run('document.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true}))');
    assert.equal(await run('document.getElementById("account-dialog").open'), true);
    await click('[data-auth-type=sms]');
    assert.equal(await text('authTargetLabel'), '手机号');
    await input('authTarget', '+86 13800000000');
    await click('#sendVerificationButton');
    assert.equal(await run('document.getElementById("sendVerificationButton").disabled'), true);
    await input('authCode', '000000');
    await click('#loginButton');
    assert.match(await text('authFeedback'), /不正确/);
    await input('authCode', '123456');
    await click('#loginButton');
    assert.equal(await text('authStatusPill'), '已登录');
    checks.push('Active-execution logout cancellation/confirmation, non-dismissable logged-out gate, SMS flow, cooldown, invalid-code recovery');
    await run('window.AccountPrototype.scenario("expired")');
    await click('[data-auth-type=email]');
    await input('authTarget', 'user@example.com');
    await input('authCode', '123456');
    await click('#loginButton');
    await run('window.AccountPrototype.scenario("catalog-unavailable")'); await wait();
    assert.match(await text('codexCatalogFeedback'), /暂无/);
    assert.equal(await run('document.getElementById("codexChatModel").value'), 'custom-model');
    checks.push('Expired-account email recovery and unavailable catalog preserve custom model');
    for (const width of [1500, 900, 760, 390]) {
      win.setContentSize(width, 950); await wait(80);
      const geometry = await run('(()=>{const d=document.getElementById("account-dialog"),r=d.getBoundingClientRect();return {left:r.left,right:r.right,width:innerWidth,client:d.clientWidth,scroll:d.scrollWidth}})()');
      assert.ok(geometry.left >= 0 && geometry.right <= geometry.width && geometry.scroll <= geometry.client + 1, JSON.stringify(geometry));
      if (width === 390) await shot('account-mobile');
    }
    win.setContentSize(1440, 1000); win.webContents.setZoomFactor(2); await wait();
    assert.equal(await run('document.getElementById("account-dialog").scrollWidth <= document.getElementById("account-dialog").clientWidth+1'), true);
    checks.push('Account dialog fits 390–1500px and 200% zoom');
    assert.deepEqual(errors, []); assert.deepEqual(requests, []);
    const report = { ok: true, checks, productionControlIds: required, errors, externalRequests: requests, scope: 'Local fixtures only; real auth, token storage, runtime shutdown and sync not executed.' };
    fs.writeFileSync(path.join(__dirname, 'verification-account.json'), JSON.stringify(report, null, 2) + '\n');
    console.log(JSON.stringify(report)); app.exit(0);
  } catch (error) { console.error(error); await shot('account-failure'); app.exit(1); }
});
