const {app,BrowserWindow}=require('electron');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const crypto=require('node:crypto');
const legacy=path.join(__dirname,'../_explorations/project-workbench-v2/options/original');
function snapshot(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?snapshot(path.join(dir,e.name)):[[path.join(dir,e.name),crypto.createHash('sha256').update(fs.readFileSync(path.join(dir,e.name))).digest('hex')]]);}
const legacyBefore=snapshot(legacy);
app.setPath('userData',fs.mkdtempSync(path.join(os.tmpdir(),'arcorbit-desk-v2-')));app.disableHardwareAcceleration();
app.whenReady().then(async()=>{
 const win=new BrowserWindow({width:1500,height:1000,show:false,webPreferences:{sandbox:true,contextIsolation:true}}),errors=[],requests=[],geometry=[];
 win.webContents.on('console-message',(_e,level,text)=>{if(level>=3&&!text.includes('Content Security Policy'))errors.push(text);});
 win.webContents.session.webRequest.onBeforeRequest((d,cb)=>{if(/^https?:/.test(d.url))requests.push(d.url);cb({cancel:/^https?:/.test(d.url)});});
 const run=code=>win.webContents.executeJavaScript(code);const get=code=>run(`(()=>{const M=window.WorkModel;return (${code})})()`);const delay=ms=>new Promise(r=>setTimeout(r,ms));
 const click=async s=>{await run(`(()=>{const e=[...document.querySelectorAll(${JSON.stringify(s)})].find(e=>!e.closest('[inert]')&&getComputedStyle(e).display!=='none');if(!e)throw Error('Missing '+${JSON.stringify(s)});if(e.disabled)throw Error('Disabled '+${JSON.stringify(s)});e.click()})()`);await delay(35);};
 const fill=(s,v)=>run(`(()=>{const e=document.querySelector(${JSON.stringify(s)});e.value=${JSON.stringify(v)};e.dispatchEvent(new Event('input',{bubbles:true}))})()`);
 const change=async(s,v)=>{await run(`(()=>{const e=document.querySelector(${JSON.stringify(s)});e.value=${JSON.stringify(v)};e.dispatchEvent(new Event('change',{bubbles:true}))})()`);await delay(30);};
 const submit=async s=>{await run(`document.querySelector(${JSON.stringify(s)}).requestSubmit()`);await delay(40);};
 fs.mkdirSync(path.join(__dirname,'previews'),{recursive:true});
 const shot=async name=>{await run('document.querySelector("#toast").style.visibility="hidden"');await delay(100);fs.writeFileSync(path.join(__dirname,'previews',name+'.png'),(await win.webContents.capturePage()).toPNG());await run('document.querySelector("#toast").style.visibility=""');};
 const noLab=async()=>assert.equal(await run(`/演示|模拟|探索|示例|原型|本轮/.test(document.body.innerText)`),false);
 const choose=async(id)=>{await click(`[data-action=select][data-task="${id}"]`);};
 const layout=async()=>run(`(()=>{const rect=s=>{const r=document.querySelector(s).getBoundingClientRect();return {left:r.left,right:r.right,width:r.width}};return {nav:rect('.sidebar'),center:rect('.detail-host'),list:rect('.task-browser')}})()`);
 try{
  await win.loadFile(path.join(__dirname,'default.html'),{query:{autoplay:'off'}});await delay(150);
  await noLab();assert.equal(await run('document.querySelectorAll(".messages").length'),0);assert.equal(await get('M.key'),'arcorbit-interaction-project-workbench-v1');
  let g=await layout();assert.ok(g.nav.right<=g.center.left&&g.center.right<=g.list.left);assert.ok(g.center.width>g.list.width);assert.equal(await run('document.querySelectorAll(".surface-tabs").length'),0);const detailTop=await run('document.querySelector(".work-scroll").getBoundingClientRect().top');assert.ok(detailTop<220,'Detail content begins at '+detailTop);await shot('detail');assert.equal(await run('document.querySelectorAll(".plan-disclosure").length'),0);assert.equal(await get('Object.hasOwn(M.current(),"plan")'),false);
  assert.equal(await run('document.querySelectorAll(".topbar [data-action=new]").length'),0);assert.equal(await run('document.querySelectorAll(".list-create-footer [data-action=new]").length'),1);
  await click('[data-action=runtime-status]');assert.equal(await run('document.querySelector("dialog").open'),false);assert.match(await run('document.querySelector(".runtime-popover").innerText'),/所有项目/);assert.match(await run('document.querySelector(".runtime-popover").innerText'),/需要处理/);await shot('runtime-status');await run('window.WorkPrototype.render()');assert.ok(await get('M.state.runOpen'));await run('document.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true}))');assert.equal(await get('M.state.runOpen'),false);
  await fill('#search','离线');await click('[data-action=runtime-status]');await click('[data-action=runtime-select][data-task="103"]');assert.equal(await get('M.current().id'),'103');assert.equal(await get('M.state.scope'),'all');assert.equal(await get('M.state.query'),'');assert.equal(await get('M.state.surface'),'detail');assert.equal(await get('M.state.runOpen'),false);
  await click('[data-action=runtime-status]');await click('.work-titlebar h2');assert.equal(await get('M.state.runOpen'),false);
  await run('window.savedRuntimeTasks=structuredClone(window.WorkModel.state.tasks);window.WorkModel.state.tasks.forEach(t=>t.mode="manual");window.WorkPrototype.render()');await click('[data-action=runtime-status]');assert.match(await run('document.querySelector(".runtime-popover").innerText'),/当前没有自动执行/);await shot('runtime-idle');await click('[data-action=runtime-settings]');assert.match(await run('document.querySelector("dialog").innerText'),/执行与连接/);await click('dialog [data-action=close]');await run('window.WorkModel.state.tasks=window.savedRuntimeTasks;delete window.savedRuntimeTasks;window.WorkPrototype.render()');await choose('101','orbit');
  assert.equal(await run('document.querySelector(".detail-tabs").innerText.includes("属性与协作")'),false);
  await click('[data-action=properties]');assert.match(await run('document.querySelector("dialog").innerText'),/推进方式/);await shot('properties');await click('dialog [data-action=close]');
  await click('[data-action=edit-criteria]');await fill('dialog [name=criteria]','方向键切换事情，Enter 进入详情，Esc 返回列表\n切换事情后，输入草稿和列表位置保持\n输入文字时，方向键不触发事情切换');await submit('dialog [data-form=criteria]');
  await click('[data-tab=attributes]');await click('[data-action=add-material]');await fill('dialog [name=name]','补充操作说明');await fill('dialog [name=content]','输入框获得焦点时保留原生文本编辑行为。');await submit('dialog [data-form=material]');assert.equal(await get('M.current().materials.length'),2);await click('[data-action=toggle-context][data-index="1"]');assert.equal(await get('M.current().materials[1].included'),false);await click('[data-action=view-material][data-index="1"]');assert.match(await run('document.querySelector("dialog").innerText'),/原生文本编辑/);await click('dialog [data-action=close]');
  await click('[data-action=comment]');await fill('dialog [name=comment]','输入框中的方向键应只移动光标。');await submit('dialog [data-form=comment]');await click('[data-action=comment-agreement]');await submit('dialog [data-form=agreement]');await click('[data-action=adopt-agreement]');assert.ok(await get('M.current().agreements.at(-1).accepted'));await shot('collaboration');
  await click('[data-action=comment-agent]');assert.match(await run('document.querySelector(".composer textarea").value'),/移动光标/);assert.equal(await get('M.current().messages.length'),0);await click('.message-popover [data-action=close-chat]');
  await click('[data-tab=scene]');assert.match(await run('document.querySelector(".work-scroll").innerText'),/输入框中的方向键/);await click('[data-action=new-child]');await fill('dialog [name=child]','检查输入框内的方向键行为');await submit('dialog [data-form=child]');assert.equal(await get('M.current().id'),'101');assert.ok(await get('M.state.tasks.some(t=>t.parent==="101")'));
  await click('[data-tab=results]');await click('[data-action=add-output]');await fill('dialog [name=name]','键盘导航检查清单');await fill('dialog [name=content]','输入框、列表和详情焦点分别检查。');await submit('dialog [data-form=output]');await click('[data-action=view-output]');assert.match(await run('document.querySelector("dialog").innerText'),/分别检查/);await click('dialog [data-action=close]');
  await click('[data-tab=activity]');await shot('activity');await click('[data-action=activity-filter][data-filter=collaboration]');assert.match(await run('document.querySelector(".event-list").innerText'),/添加资料/);
  await choose('105');await click('[data-tab=results]');await shot('results');await run('document.querySelector(".work-scroll").scrollTop=400');await shot('acceptance');await run('document.querySelector(".work-scroll").scrollTop=0');assert.equal(await run('document.querySelector("[data-action=accept]").disabled'),true);await click('[data-action=view-output]');await shot('result-document');await click('dialog [data-action=close]');
  await choose('104','todo');await shot('decision');await choose('103','feedback');await shot('running');assert.equal(await get('M.current().progress.plan.length'),4);await click('.plan-disclosure summary');await shot('current-plan');await run('window.WorkPrototype.render()');assert.equal(await run('document.querySelector(".plan-disclosure").open'),true);
  const previousNext=await get('M.current().progress.next');await click('[data-action=adjust-direction]');await fill('dialog [name=next]','先检查失效资源提示，暂缓其他修改');await fill('dialog [name=plan]','区分访问受限与网络失败\n整理提示内容供确认');await submit('dialog [data-form=direction]');assert.equal(await get('M.current().mode'),'auto');assert.equal(await get('M.current().progress.next'),previousNext);assert.ok(await get('Boolean(M.current().pendingDirection)'));await shot('pending-direction');await run('window.WorkPrototype.tick()');assert.equal(await get('M.current().progress.next'),'先检查失效资源提示，暂缓其他修改');assert.equal(await get('M.current().progress.plan.length'),2);assert.equal(await get('M.current().mode'),'auto');assert.equal(await get('Boolean(M.current().pendingDirection)'),false);await shot('adjusted-direction');
  await choose('102','orbit');await click('[data-tab=results]');assert.match(await run('document.querySelector(".work-scroll").innerText'),/离线恢复方案 · 初稿/);await shot('analysis-results');await click('[data-tab=scene]');assert.equal(await run('document.querySelectorAll(".plan-disclosure").length'),0);await shot('analysis-overview');await click('.work-actions [data-action=analyze]');assert.equal(await get('M.state.surface'),'chat');assert.equal(await get('M.current().mode'),'discussion');assert.equal(await run('document.querySelector("dialog").open'),false);assert.equal(await run('document.querySelector(".detail-host .messages")!==null'),true);g=await layout();assert.ok(g.center.right<=g.list.left);assert.equal(await run('document.querySelector(".detail-base").inert'),true);const popupBounds=await run('(()=>{const a=document.querySelector(".detail-host").getBoundingClientRect(),b=document.querySelector(".message-popover").getBoundingClientRect();return {contained:b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom};})()');assert.ok(popupBounds.contained);await noLab();await shot('messages');await click('[data-action=message-agreement][data-index="1"]');await fill('dialog [name=agreement]','重新联网后，先核对状态再提交。');await submit('dialog [data-form=agreement]');await click('.message-popover [data-action=close-chat]');await click('[data-tab=attributes]');await click('[data-action=adopt-agreement][data-index="2"]');await click('[data-action=message-context][data-index="1"]');assert.equal(await run('document.querySelector(".message-highlight").dataset.messageIndex'),'1');
  await fill('.composer textarea','保留离线期间未发送的内容。');await submit('.composer');const thread=await get('M.current().thread');await click('.message-popover [data-action=close-chat]');assert.equal(await get('M.state.surface'),'detail');assert.equal(await run('document.querySelectorAll(".messages").length'),0);await click('.work-actions [data-action=auto]');await noLab();await click('[data-action=confirm-auto]');assert.equal(await get('M.current().mode'),'auto');assert.equal(await get('M.current().thread'),thread);
  await choose('101');await click('.work-actions [data-action=auto]');await click('[data-action=confirm-auto]');assert.equal(await get('M.current().mode'),'queued');await click('[data-action=runtime-status]');assert.match(await run('document.querySelector(".runtime-popover").innerText'),/等待执行/);await shot('runtime-queue');await click('[data-action=close-runtime]');
  await choose('103','feedback');const runtimeThread=await get('M.current().thread');await fill('.composer textarea','只调整图片加载，不修改反馈原文。');await submit('.composer');assert.equal(await get('M.current().pending.length'),1);assert.equal(await get('M.state.surface'),'detail');
  await click('[data-action=chat]');assert.equal(await run('document.querySelector("dialog").open'),false);await run('window.WorkPrototype.tick()');assert.equal(await get('M.current().pending.length'),0);assert.equal(await get('M.state.surface'),'chat');
  await click('.work-actions [data-action=pause]');assert.equal(await get('M.current().mode'),'paused');assert.equal(await get('M.state.surface'),'chat');assert.equal(await run('document.querySelector("dialog").open'),false);await noLab();await shot('auto-intervention');await click('.message-popover [data-action=close-chat]');await click('[data-action=adjust-direction]');await fill('dialog [name=next]','先确认图片失败时的提示文案');await fill('dialog [name=plan]','');await submit('dialog [data-form=direction]');assert.equal(await get('M.current().mode'),'paused');assert.deepEqual(await get('M.current().progress.plan'),[]);assert.equal(await run('document.querySelectorAll(".plan-disclosure").length'),0);await shot('paused-direction');await click('[data-action=chat]');
  await fill('.composer textarea','暂停后尚未发送的讨论');await choose('106');await choose('103');assert.equal(await get('M.state.surface'),'detail');assert.equal(await run('document.querySelector(".composer textarea").value'),'暂停后尚未发送的讨论');await click('[data-action=chat]');await submit('.composer');assert.equal(await get('M.current().mode'),'paused');await click('.work-actions [data-action=resume]');assert.equal(await get('M.current().mode'),'auto');assert.equal(await get('M.current().thread'),runtimeThread);assert.equal(await get('M.state.surface'),'chat');
  const count=await get('M.state.tasks.length');await click('[data-action=new]');await fill('dialog [name=intent]','整理下周的反馈处理计划');await change('dialog [name=project]','orbit');await noLab();await shot('new-work');await submit('dialog [data-form=new]');assert.equal(await get('M.state.tasks.length'),count+1);assert.equal(await get('M.current().assignee'),'我');assert.equal(await get('M.current().status'),'review');assert.equal(await get('M.state.surface'),'chat');assert.equal(await run('document.querySelector("dialog").open'),false);const created=await get('M.current().id');assert.deepEqual(await get('M.current().progress.plan'),[]);assert.equal(await get('Object.hasOwn(M.current(),"plan")'),false);
  await fill('.composer textarea','这条草稿暂时不发送');await run('window.WorkPrototype.tick()');assert.equal(await run('document.querySelector(".composer textarea").value'),'这条草稿暂时不发送');
  await win.reload();await delay(150);assert.equal(await get('M.state.surface'),'detail');assert.equal(await get('M.state.tasks.length'),count+1);assert.equal(await get('M.current().id'),created);assert.equal(await run('document.querySelector(".composer textarea").value'),'这条草稿暂时不发送');
  await fill('#search','离线');assert.equal(await get('M.visible().length'),1);await fill('#search','');await change('#state-filter','completed');assert.ok(await get('M.visible().every(t=>t.status==="completed")'));await change('#state-filter','all');
  await choose('105','orbit');await click('.work-actions [data-action=issue]');await fill('dialog [name=issue]','检查低分辨率窗口下输入区域是否遮挡内容');await submit('dialog [data-form=issue]');assert.equal(await run('document.querySelector("[data-action=accept]").disabled'),true);await click('[data-action=resolve-issue]');assert.equal(await run('document.querySelector("[data-action=accept]").disabled'),true);for(const i of [0,1,2])await click('[data-criterion="'+i+'"]');await click('.work-actions [data-action=accept]');assert.equal(await get('M.current().status'),'accepted');
  await choose('104','todo');await click('[data-action=decision]');await click('[data-action=confirm-decision]');assert.equal(await get('M.current().mode'),'auto');
  await choose(created,'orbit');await click('[data-action=edit]');await fill('dialog [name=body]','整理下周反馈计划，优先检查阻塞问题');await submit('dialog [data-form=edit]');assert.match(await get('M.current().body'),/优先检查/);
  for(const name of ['filters','model']){await click(`[data-action="${name}"]`);await noLab();await click('dialog [data-action=close]');}
  await click('[data-action=chat]');for(const width of [1500,1280,1024,760,390]){win.setSize(width,950);await delay(100);const geo=await run(`({width:innerWidth,scroll:document.documentElement.scrollWidth,center:document.querySelector('.detail-host').getBoundingClientRect().width,messages:document.querySelector('.messages').getBoundingClientRect().width})`);assert.ok(geo.scroll<=geo.width,JSON.stringify(geo));assert.ok(geo.center>250,JSON.stringify(geo));geometry.push(geo);await click('[data-action=runtime-status]');const popup=await run('(()=>{const r=document.querySelector(".runtime-popover").getBoundingClientRect();return {left:r.left,right:r.right,bottom:r.bottom,width:innerWidth,height:innerHeight}})()');assert.ok(popup.left>=0&&popup.right<=popup.width&&popup.bottom<=popup.height,JSON.stringify(popup));if(width===390)await shot('narrow-runtime');await click('[data-action=close-runtime]');assert.equal(await get('M.state.surface'),'chat');if(width===760){await click('[data-action=toggle-list]');assert.equal(await run('getComputedStyle(document.querySelector(".task-browser")).display'),'flex');await shot('narrow-list');assert.equal(await run('(()=>{const r=document.querySelector(".list-create-footer button").getBoundingClientRect();return r.height>=35&&r.bottom<=innerHeight})()'),true);await click('.task-browser [data-action=toggle-list]');}if(width===390)await shot('narrow-messages');}
  await click('.message-popover [data-action=close-chat]');
  for(const width of [1500,1024,760,390]){win.setSize(width,950);await delay(70);for(const tab of ['scene','attributes','results','activity']){await choose(tab==='results'?'105':'101','orbit');await click('[data-tab="'+tab+'"]');const g=await run('({width:innerWidth,scroll:document.documentElement.scrollWidth,content:document.querySelector(".work-scroll").clientWidth,overflow:document.querySelector(".work-scroll").scrollWidth})');assert.ok(g.scroll<=g.width&&g.overflow<=g.content+1,JSON.stringify({tab,...g}));if(width===390){await run('document.querySelector(".work-scroll").scrollTop=0');await shot('narrow-'+tab);}}}
  win.setSize(1500,1000);await choose('103','feedback');await click('[data-action=chat]');await run(`(()=>{const t=window.WorkModel.current();t.messages=Array.from({length:35},(_,i)=>({role:i%2?'agent':'user',text:'协作记录 '+i+'：保留当前阅读位置，检查已有目标与结果。'}));window.WorkPrototype.render();})()`);await run('document.querySelector(".messages").scrollTop=160');const before=await run('document.querySelector(".messages").scrollTop');await run('window.WorkPrototype.render({follow:true})');assert.equal(await run('document.querySelector(".messages").scrollTop'),before);
  await run('document.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true}))');assert.equal(await get('M.state.surface'),'detail');assert.equal(await run('document.querySelectorAll(".message-popover").length'),0);
  await run('(()=>{const t=window.WorkModel.current();t.body="长内容\\n".repeat(100);window.WorkPrototype.render();})()');await run('document.querySelector(".work-scroll").scrollTop=250');const detailScroll=await run('document.querySelector(".work-scroll").scrollTop');await click('[data-action=chat]');await run('window.WorkPrototype.render()');await click('.message-popover [data-action=close-chat]');assert.equal(await run('document.querySelector(".work-scroll").scrollTop'),detailScroll);
  assert.deepEqual(legacyBefore,snapshot(legacy));assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
  const report={ok:true,checks:['global status popup, idle/settings, queue and cross-project navigation','status popover closes independently, fits mobile widths and updates on render','create action only in list footer','no fixed plans for new work or analysis; optional task-specific plan','plan change applies at execution boundary and does not complete task','optional plan can be cleared while keeping execution paused','expanded plan survives rerender','detail categories and compact properties','materials and context membership','comments to Agent draft and adopted agreements','message source navigation','shared criteria and acceptance guard','stage outputs and document previews','child work and filtered events','legacy version files unchanged','separate local storage','project / center / right list geometry','message popup constrained to center; task list remains available','compact header without surface tabs; messages opt-in','analysis → Auto retains identity','queue and running intervention','pause and explicit resume','new conversation creates one self-assigned work','per-task drafts survive tick and reload','search and state filters','acceptance issues','decision and edit','no demonstration wording in product UI','narrow layouts and list drawer','message and detail reading positions retained; Escape closes popup'],geometry,errors,externalRequests:requests,scope:'Local interactive prototype only. All execution and responses are simulated; no product backend or real Agent.'};fs.writeFileSync(path.join(__dirname,'verification.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));app.exit(0);
 }catch(error){console.error(error);console.error(errors);await shot('verification-failure');app.exit(1);}
});
