(() => {
 const M=window.WorkModel;
 const esc = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const icons={plus:'M12 5v14M5 12h14',arrow:'M5 12h14m-6-6 6 6-6 6',chevron:'m9 5 7 7-7 7',chat:'M20 11.5a8 8 0 0 1-8 8H5l-3 2v-10a9 9 0 0 1 18 0Z',mic:'M9 5a3 3 0 0 1 6 0v7a3 3 0 0 1-6 0ZM5 10v2a7 7 0 0 0 14 0v-2M12 19v3m-4 0h8',play:'m8 5 11 7-11 7Z',pause:'M8 5v14M16 5v14',close:'m6 6 12 12M18 6 6 18',check:'m5 12 4 4L19 6',grid:'M3 3h7v7H3ZM14 3h7v7h-7ZM3 14h7v7H3ZM14 14h7v7h-7Z',list:'M9 5h12M9 12h12M9 19h12M3 5h1M3 12h1M3 19h1',clock:'M12 8v5l3 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z',settings:'M4 7h16M4 17h16M8 4v6M16 14v6',external:'M14 3h7v7m0-7-11 11M10 3H3v18h18v-7',search:'M16 16l5 5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z'};
 const icon=(name)=>`<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round">${`<path d="${icons[name]||icons.grid}"/>`}</svg>`;
 const button=(action,text,cls='',extra='')=>`<button type="button" data-action="${action}" class="${cls}" ${extra}>${text}</button>`;
 const tag=t=>`<span class="status status-${esc(t.status)} status-${esc(t.mode)}"><i></i>${esc(M.states[t.status])}</span>`;
 const taskMeta=t=>`<span>${esc(M.project(t.project).name)}</span><span>#${t.id}</span><span>执行人 ${esc(t.assignee)}</span>`;
 const scopeName=()=>M.state.scope==='all'?'所有项目':M.project(M.state.scope).name;
 function nav(){return `<aside class="sidebar"><a class="brand" href="../platform-workspace/default.html"><span class="brand-mark">a</span><strong>ArcOrbit</strong></a><nav class="page-navigation" aria-label="主导航"></nav><div class="sidebar-bottom"><div class="connection"><i class="${M.state.offline?'offline':''}"></i>${M.state.offline?'离线 · 已保留此设备内容':'已保存到此设备'}</div><button type="button" class="account-bottom account-trigger" data-account-open aria-label="个人中心：账户与 Runtime"><span class="avatar">G</span><span>Glare<small>Workshop 账户</small></span>${icon('settings')}</button></div></aside>`;}
 function runtimeGroups(){return [['attention','需要处理',['decision','paused','external','failed','stopped']],['running','正在执行',['auto']],['queued','等待执行',['queued']]].map(([id,title,modes])=>({id,title,tasks:M.state.tasks.filter(t=>modes.includes(t.mode)&&!['completed','accepted','cancelled'].includes(t.status))}));}
 function runtimeStatus(){const groups=runtimeGroups(),n=id=>groups.find(x=>x.id===id).tasks.length;const labels=[n('running')?`${n('running')} 执行中`:'',n('queued')?`${n('queued')} 排队`:'',n('attention')?`${n('attention')} 待处理`:''].filter(Boolean);return `<div class="runtime-status-host">${button('runtime-status',`<i class="runtime-dot ${n('attention')?'attention':n('running')?'running':''}"></i><span>${M.state.offline?'运行状态 · 连接中断':labels.join(' · ')||'运行状态 · 空闲'}</span>${icon('chevron')}`,'runtime-trigger',`aria-haspopup="dialog" aria-expanded="${!!M.state.runOpen}" aria-controls="runtime-popover" title="查看所有项目的本机运行状态"`)}${M.state.runOpen?`<section id="runtime-popover" class="runtime-popover" role="dialog" aria-labelledby="runtime-title" tabindex="-1"><header><div><h2 id="runtime-title">运行状态</h2><p>所有项目 · 此设备</p></div>${button('close-runtime',icon('close'),'icon-button','aria-label="关闭运行状态"')}</header><div class="runtime-body" data-scroll-key="runtime-status">${M.state.offline?'<p class="runtime-empty">连接已中断，以下为此设备保留的状态。</p>':''}${groups.filter(g=>g.tasks.length).map(g=>`<section class="runtime-group"><h3>${g.title}<span>${g.tasks.length}</span></h3>${g.tasks.map(t=>`<button type="button" class="runtime-item" data-action="runtime-select" data-task="${t.id}"><div><strong>${esc(t.title)}</strong><small>${esc(M.project(t.project).name)} · ${esc(M.modes[t.mode])}</small><p>${esc(t.mode==='decision'?t.decision:t.mode==='external'?t.external||'等待外部条件':t.mode==='queued'?'等待工作区或执行位置':t.mode==='paused'?'已暂停，准备好后可继续':t.mode==='failed'?'执行需要核对并恢复':t.mode==='stopped'?'执行已停止，工作记录保留':window.WorkProgress.ensure(t).current)}</p></div>${icon('chevron')}</button>`).join('')}</section>`).join('')||'<div class="runtime-empty"><strong>当前没有自动执行中的事情</strong><p>可以从事情详情开始 Auto，或在执行设置中管理自动领取。</p></div>'}</div><footer><span>点选事情，查看进展或介入</span>${button('runtime-settings','执行设置','text-button')}</footer></section>`:''}</div>`;}
 function header(){return `<header class="topbar"><div class="breadcrumb"><strong>Thing</strong></div><div class="top-actions">${button('toggle-list',icon('list')+'事情列表','quiet list-toggle','aria-label="打开或收起事情列表"')}${runtimeStatus()}</div></header>`;}
 function stateFilter(){return `<select id="state-filter" aria-label="事情状态"><option value="all">全部状态</option><option value="attention" ${M.state.filter==='attention'?'selected':''}>需要我关注</option>${Object.entries(M.states).map(([id,name])=>`<option value="${id}" ${M.state.filter===id?'selected':''}>${name}</option>`).join('')}</select>`;}
 function filters(){return `<div class="query-bar"><div class="search-field">${icon('search')}<input id="search" aria-label="搜索事情" placeholder="搜索事情…" value="${esc(M.state.query)}"></div></div>`;}

 function row(t){const label=`${t.title} · ${M.project(t.project).name} · #${t.id} · ${M.states[t.status]} · ${M.modes[t.mode]}`;return `<button type="button" class="task-row ${M.state.selected===t.id?'active':''}" data-action="select" data-task="${t.id}" title="${esc(label)}" aria-label="${esc(label)}" aria-current="${M.state.selected===t.id?'true':'false'}"><span class="task-symbol ${t.status==='accepted'?'complete':''}">${t.status==='accepted'?icon('check'):icon(t.mode==='auto'?'play':'list')}</span><strong class="row-name">${esc(t.title)}</strong>${M.state.scope==='all'?`<span class="row-project" aria-hidden="true">${M.project(t.project).initial}</span>`:''}${tag(t)}</button>`;}
 function empty(){return `<div class="empty-state">${icon('search')}<h3>这里暂时没有事情</h3><p>调整筛选，或通过列表底部发起事情。</p>${button('clear-filters','清除筛选')}</div>`;}
 function listView(){return `<section class="list-layout ${M.state.listOpen?'list-open':''}"><div class="detail-host">${M.current()?detail(M.current()):emptyDetail()}</div><aside class="task-browser" aria-label="事情列表"><div class="section-heading"><h1>事情 <span>${M.visible().length}</span></h1><div class="list-controls">${stateFilter()}${button('filters',icon('settings'),'icon-button','aria-label="更多筛选" title="更多筛选" aria-haspopup="dialog" aria-expanded="false"')}${button('toggle-list',icon('close'),'icon-button close-list','aria-label="收起事情列表"')}</div></div>${filters()}<div class="task-rows" data-scroll-key="list:${M.state.scope}:${M.state.filter}">${M.visible().map(row).join('')||empty()}</div><footer class="list-create-footer">${button('new',icon('plus')+'发起事情','primary')}</footer></aside></section>`;}
 function emptyDetail(){return `<div class="empty-state large">${icon('spark')}<h2>选择一件事情，继续推进。</h2><p>目标、成果和协作记录，会一起留在这里。</p></div>`;}
 function actions(t){
  if(t.mode==='auto')return button('chat',icon('chat')+'交流','')+button('pause',icon('pause')+'暂停并讨论','')+button('stop','停止执行','quiet');
  if(t.mode==='queued')return button('chat','补充要求')+button('unqueue','撤回 Auto','quiet');
  if(t.mode==='paused')return button('resume',icon('play')+'继续 Auto','primary')+button('chat','继续讨论')+button('stop','停止执行','quiet');
  if(t.mode==='decision')return button('decision','处理决定','primary')+button('chat','先讨论');
  if(t.mode==='external')return button('recheck','条件已就绪，重新检查','primary')+button('chat','补充说明');
  if(['failed','stopped'].includes(t.mode))return button('recover','恢复本次执行','primary')+button('chat','说明情况');
  if(t.status==='completed')return button('accept','验收通过','primary',!window.WorkDetails.canAccept(t)?'disabled title="请确认验收标准并处理未解决问题"':'')+button('issue','提出验收问题');
  if(t.status==='accepted')return '<span class="subtle">验收已完成，结果保留可查</span>';
  if(t.status==='cancelled')return '<span class="subtle">事情已取消，可在属性中纠偏</span>';
  if(t.status==='blocked')return button('unblock','恢复为待处理','primary')+button('chat','补充信息');
  return button('auto',icon('play')+'开始 Auto','primary')+button('analyze',icon('spark')+'先分析');
 }
 const D=window.WorkDetails.views({esc,icon,button,tag});
 const {scene,attributes,results,activity}=D;
 function composer(t,inDialog=false){let placeholder=t.mode==='auto'?'补充要求，下一执行边界生效…':t.mode==='paused'?'讨论调整方向，准备好后再继续 Auto…':'补充目标、询问进展或改变方向…';const disabled=['completed','accepted','cancelled'].includes(t.status);return `<form class="composer" data-form="message" data-owner="${t.id}"><div class="composer-context"><span>${icon('spark')} ${esc(t.title)}</span>${!inDialog?button('chat',icon('chat')+'查看消息','text-button'):''}</div><div class="composer-input"><textarea aria-label="向当前事情补充要求" name="message" rows="2" placeholder="${placeholder}" ${disabled?'disabled':''}>${esc(t.draft)}</textarea><div class="send-actions">${button('voice',icon('mic'),'icon-button','aria-label="语音输入暂不可用" title="语音输入暂不可用" disabled')}<button type="submit" class="send-button" ${disabled?'disabled':''} aria-label="发送要求">${icon('arrow')}</button></div></div><div class="composer-foot"><span>${disabled?'已收束 · 可查看记录，或从验收入口继续':t.mode==='auto'?'追加说明不会暂停 Auto':'⌘ / Ctrl + Enter 发送'}</span>${button('model',`${esc(t.model)} / ${esc(t.level)}`,'text-button')}</div></form>`;}
 function messages(t){return `<div class="message-center" data-current-messages="${t.id}"><div class="conversation-info">${icon('chat')}<span>这件事情的持续协作</span><span class="conversation-info-right">${t.messages.length} 条消息</span></div>${t.pending.length?`<div class="pending-inline">${icon('clock')} ${t.pending.length} 条补充要求已接收，将在下一步生效</div>`:''}<div class="messages" data-scroll-key="messages:${t.id}">${t.messages.length?t.messages.map((m,i)=>`<div data-message-index="${i}" class="message ${m.role==='user'?'user':'agent'}"><div class="message-label">${m.role==='user'?'<span class="avatar small-avatar">G</span>你':`<span class="agent-avatar">${icon('spark')}</span>ArcOrbit Agent`}</div><p>${esc(m.text)}</p>${button('message-agreement','保存为约定','text-button message-save',`data-index="${i}"`)}</div>`).join(''):`<div class="chat-empty">${icon('chat')}<h3>围绕这件事，一起往前走。</h3><p>目标与相关内容已经在这里。<br>可以直接提出问题，或补充你的想法。</p></div>`}</div></div>`;}
 function messagePopup(t){return `<div class="message-scrim" data-action="close-chat" aria-hidden="true"></div><section class="message-popover" role="dialog" aria-labelledby="message-popup-title" tabindex="-1"><header class="message-popup-header"><div class="popup-heading"><h2 id="message-popup-title">${icon('chat')}协作消息</h2>${button('close-chat',icon('close'),'icon-button','aria-label="关闭消息" title="关闭消息 · Esc"')}</div><div class="popup-subject"><span>#${t.id} · ${esc(t.title)}</span>${tag(t)}</div><div class="work-actions popup-actions">${actions(t)}</div></header>${messages(t)}${composer(t,true)}</section>`;}
 function detail(t){const isChat=M.state.surface==='chat';return `<div class="detail-scene" data-current-task="${t.id}"><article class="work-detail detail-base" ${isChat?'inert aria-hidden="true"':''}><header class="work-header"><div class="work-meta">${taskMeta(t)}<span class="meta-priority">${esc(t.priority==='无优先级'?t.priority:t.priority+'优先级')}</span>${tag(t)}${button('properties',icon('settings')+'属性','text-button property-trigger')}</div><div class="work-titlebar"><h2>${esc(t.title)}</h2><div class="work-actions">${actions(t)}</div></div></header><nav class="detail-tabs" aria-label="事情内容">${[['scene','概览'],['attributes','资料与协作'],['results','成果与验收'],['activity','活动']].map(([id,label])=>button('tab',label,M.state.tab===id?'active':'',`data-tab="${id}"`)).join('')}</nav><div class="work-scroll" data-scroll-key="detail:${t.id}:${M.state.tab}">${({scene,attributes,results,activity}[M.state.tab]||scene)(t)}</div>${isChat?'<div class="background-composer" aria-hidden="true"></div>':composer(t)}</article>${isChat?messagePopup(t):''}</div>`;}

 function render(){const app=document.getElementById('app');app.className='app-shell project-desk';app.innerHTML=`${nav()}<main class="main-shell">${header()}<div class="workspace">${listView()}</div></main>`;}
 window.WorkViews={esc,icon,button,tag,render,composer,scopeName,properties:D.properties};
})();
