#!/usr/bin/env python3
"""Generate deterministic visual projections and validate references/contrast. Requires PyYAML."""
from pathlib import Path
import argparse, json, re
import yaml
ROOT = Path(__file__).resolve().parent

def read(path):
    return yaml.safe_load(path.read_text())

def build():
    tokens = read(ROOT / 'design-tokens.yaml')
    flat = {}
    def flatten(obj, path=''):
        if isinstance(obj, dict):
            if 'value' in obj:
                flat[path] = obj['value']
            else:
                for k,v in obj.items():
                    if k not in ('metadata','description'):
                        flatten(v, f'{path}.{k}'.strip('.'))
        elif isinstance(obj, (str,int,float)):
            flat[path] = obj
    flatten(tokens)
    def resolve(value, stack=()):
        if isinstance(value,str) and re.fullmatch(r'\{[^}]+\}',value):
            key=value[1:-1]
            if key in stack: raise ValueError(f'Circular reference: {key}')
            return resolve(flat[key], (*stack,key))
        return value
    resolved={k:resolve(v) for k,v in flat.items()}
    catalog=read(ROOT/'component-catalog.yaml'); components={}
    for file in catalog['includes']:
        obj=read(ROOT/file)['components']
        if components.keys() & obj.keys(): raise ValueError('Duplicate component')
        components.update(obj)
    def lookup(key):
        obj=tokens
        for part in key.split('.'): obj=obj[part]
        return obj
    for name,obj in components.items():
        for required in ('role','variants','sizes','states','token_refs'): assert required in obj,(name,required)
        for ref in obj['token_refs']: lookup(ref)
        for ref in re.findall(r'\{([a-zA-Z0-9_.]+)\}',json.dumps(obj,ensure_ascii=False)): lookup(ref)
    def css_value(k,v):
        if isinstance(v,(int,float)):
            if k.startswith('layer.') or k.endswith('.weight'): return str(v)
            if k.endswith('duration_ms'): return f'{v}ms'
            return f'{v}px'
        return str(v)
    def rule(selector, values):
        return selector+' {\n'+''.join(f'  --{k.replace(".","-").replace("_","-")}: {css_value(k,v)};\n' for k,v in values.items())+'}\n'
    css='/* Generated by build-preview.py; edit YAML sources. */\n'+rule(':root',resolved)
    themes={}
    for p in sorted((ROOT.parent/'themes').glob('*.yaml')):
        theme=read(p); overrides=theme['overrides']
        for k in overrides: assert k in flat,k
        vals={k:resolve(v) for k,v in overrides.items()}
        themes[theme['metadata']['name']]={**resolved,**vals}
        css+=rule('[data-theme="'+theme['metadata']['name']+'"]', vals)
    def luminance(color):
        c=[int(color[i:i+2],16)/255 for i in (1,3,5)]
        c=[v/12.92 if v<=.04045 else ((v+.055)/1.055)**2.4 for v in c]
        return sum(a*b for a,b in zip(c,[.2126,.7152,.0722]))
    pairs=[('semantic.text','semantic.canvas',4.5),('semantic.muted','colors.ink.50',4.5),
           ('semantic.nav_text','semantic.sidebar',4.5),('semantic.nav_selected_text','semantic.nav_selected',4.5),
           ('semantic.control_border','semantic.canvas',3),('semantic.focus','semantic.canvas',3),
           ('semantic.focus','semantic.sidebar',3)]
    pairs += [('colors.accent.on','colors.accent.'+s,4.5) for s in ('base','hover','pressed')]
    pairs += [('colors.'+x+'.'+f,'colors.'+x+'.soft',4.5) for x,f in [('success','base'),('accepted','base'),('warning','strong'),('danger','base'),('info','base'),('accent','strong')]]
    pairs += [('colors.ink.600','colors.ink.100',4.5),('colors.paper','colors.danger.base',4.5),('semantic.disabled_text','semantic.disabled_bg',4.5)]
    results=[]
    for theme,vals in themes.items():
        for fg,bg,threshold in pairs:
            a,b=sorted((luminance(vals[fg]),luminance(vals[bg])))
            ratio=(b+.05)/(a+.05)
            assert ratio>=threshold,(theme,fg,bg,ratio,threshold)
            results.append({'theme':theme,'foreground':fg,'background':bg,'ratio':round(ratio,2),'minimum':threshold})
    data={'tokens':resolved,'themes':list(themes),'components':components,'contrast':results}
    return {'generated-tokens.css':css,'preview-data.js':'// Generated by build-preview.py.\nwindow.visualData = '+json.dumps(data,ensure_ascii=False,indent=2)+';\n'},len(components),results

if __name__=='__main__':
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    files,count,results=build()
    for name,body in files.items():
        p=ROOT/name
        if args.check: assert p.exists() and p.read_text()==body, f'Regenerate {name}'
        else: p.write_text(body)
    print(f'{count} components; {len(results)} contrast checks passed; generated files '+('current' if args.check else 'written'))
