// Generated by build-preview.py.
window.visualData = {
  "tokens": {
    "colors.ink.950": "#0D1119",
    "colors.ink.900": "#121722",
    "colors.ink.800": "#1D2431",
    "colors.ink.700": "#313A49",
    "colors.ink.600": "#465267",
    "colors.ink.500": "#566174",
    "colors.ink.400": "#596579",
    "colors.ink.300": "#B6BDC8",
    "colors.ink.200": "#D7DCE4",
    "colors.ink.150": "#E4E7EC",
    "colors.ink.100": "#ECEFF3",
    "colors.ink.75": "#F2F4F7",
    "colors.ink.50": "#F7F8FA",
    "colors.paper": "#FFFFFF",
    "colors.accent.strong": "#9B572D",
    "colors.accent.base": "#F4B77D",
    "colors.accent.hover": "#EFAC6B",
    "colors.accent.soft": "#FFF4E9",
    "colors.accent.faint": "#FFFAF5",
    "colors.accent.pressed": "#E6A15F",
    "colors.accent.on": "#332C26",
    "colors.info.base": "#1D60B5",
    "colors.info.soft": "#E8F2FF",
    "colors.accepted.base": "#096B62",
    "colors.accepted.soft": "#DFF7F2",
    "colors.success.base": "#196C47",
    "colors.success.soft": "#E4F6ED",
    "colors.warning.strong": "#A45A14",
    "colors.warning.base": "#975411",
    "colors.warning.soft": "#FFF0D8",
    "colors.danger.base": "#B93240",
    "colors.danger.soft": "#FDE9EA",
    "typography.family.interface": "-apple-system, BlinkMacSystemFont, Segoe UI, PingFang SC, Microsoft YaHei, sans-serif",
    "typography.family.mono": "SFMono-Regular, Consolas, monospace",
    "typography.display.size": 28,
    "typography.display.line_height": 34,
    "typography.display.weight": 700,
    "typography.title.size": 20,
    "typography.title.line_height": 28,
    "typography.title.weight": 700,
    "typography.heading.size": 16,
    "typography.heading.line_height": 22,
    "typography.heading.weight": 700,
    "typography.body.size": 14,
    "typography.body.line_height": 22,
    "typography.body.weight": 400,
    "typography.conversation.size": 15,
    "typography.conversation.line_height": 24,
    "typography.conversation.weight": 400,
    "typography.label.size": 13,
    "typography.label.line_height": 18,
    "typography.label.weight": 600,
    "typography.caption.size": 12,
    "typography.caption.line_height": 18,
    "typography.caption.weight": 400,
    "typography.micro.size": 11,
    "typography.micro.line_height": 16,
    "typography.micro.weight": 700,
    "spacing.1": 2,
    "spacing.2": 4,
    "spacing.3": 8,
    "spacing.4": 12,
    "spacing.5": 16,
    "spacing.6": 20,
    "spacing.7": 24,
    "spacing.8": 32,
    "layout.sidebar_width": 228,
    "layout.titlebar_height": 40,
    "layout.workbench_topbar_height": 54,
    "layout.workbench_search_height": 31,
    "layout.readable_width": 760,
    "layout.list_drawer_breakpoint": 760,
    "layout.commandbar_height": 54,
    "layout.inspector_width": 312,
    "layout.compact_control_height": 32,
    "layout.control_height": 36,
    "layout.compact_row_height": 40,
    "layout.row_height": 44,
    "layout.min_window_width": 390,
    "layout.min_window_height": 720,
    "corner_radius.small": 6,
    "corner_radius.medium": 10,
    "corner_radius.large": 16,
    "corner_radius.pill": 999,
    "shadows.small": "0 1px 2px rgba(22,28,38,.06), 0 4px 12px rgba(22,28,38,.05)",
    "shadows.large": "0 24px 80px rgba(13,17,25,.25), 0 4px 16px rgba(13,17,25,.12)",
    "animation.fast.duration_ms": 120,
    "animation.fast.easing": "cubic-bezier(.2,.8,.2,1)",
    "animation.normal.duration_ms": 160,
    "animation.normal.easing": "cubic-bezier(.2,.8,.2,1)",
    "animation.deliberate.duration_ms": 240,
    "animation.deliberate.easing": "cubic-bezier(.2,.8,.2,1)",
    "semantic.canvas": "#FFFFFF",
    "semantic.sidebar": "#F7F8FA",
    "semantic.chrome": "#F7F8FA",
    "semantic.elevated": "#FFFFFF",
    "semantic.text": "#121722",
    "semantic.muted": "#465267",
    "semantic.nav_text": "#465267",
    "semantic.nav_selected_text": "#121722",
    "semantic.nav_selected": "#FFF4E9",
    "semantic.divider": "#E4E7EC",
    "semantic.control_border": "#7A8492",
    "semantic.focus": "#9B572D",
    "semantic.disabled_text": "#566174",
    "semantic.disabled_bg": "#ECEFF3",
    "semantic.scrim": "rgba(13,17,25,.24)",
    "focus.width": 2,
    "focus.offset": 2,
    "layer.content": 0,
    "layer.sticky": 10,
    "layer.popover": 20,
    "layer.message_overlay": 30,
    "layer.dialog": 40
  },
  "themes": [
    "dark",
    "legacy-mixed",
    "light"
  ],
  "components": {
    "AppShell": {
      "role": "建立明暗事情台与兼容控制台外壳；业务内容的优先级保持一致",
      "variants": {
        "project_workbench": {
          "sidebar": "{semantic.sidebar}",
          "workspace": "{semantic.canvas}",
          "topbar": "{layout.workbench_topbar_height}",
          "legacy_commandbar": "shared_global_context"
        },
        "command_center": {
          "sidebar": "{semantic.sidebar}",
          "workspace": "{colors.ink.75}"
        },
        "workbench": {
          "sidebar": "{semantic.sidebar}",
          "workspace": "{colors.paper}"
        },
        "window_chrome_macos": {
          "surface": "{semantic.chrome}",
          "controls": "native_traffic_lights",
          "placement": "top_left_navigation",
          "titlebar": "absent",
          "green_action": "system_full_screen",
          "hover_panel": "system_window_layout",
          "drag_region": "noninteractive_top_space"
        },
        "window_chrome_windows_linux": {
          "surface": "{semantic.chrome}",
          "controls": [
            "minimize",
            "maximize",
            "restore",
            "close"
          ],
          "placement": "top_right",
          "titlebar": "absent",
          "drag_region": "noninteractive_top_space"
        }
      },
      "sizes": {
        "desktop": {
          "sidebar": "{layout.sidebar_width}",
          "titlebar": "absent",
          "commandbar": "{layout.commandbar_height}"
        }
      },
      "states": [
        "loading",
        "ready",
        "degraded",
        "maximized",
        "full_screen"
      ],
      "token_refs": [
        "colors.ink.900",
        "colors.ink.75",
        "layout.sidebar_width",
        "layout.titlebar_height",
        "layout.commandbar_height"
      ],
      "accessibility": {
        "requirement": "macOS 保留系统原生 traffic lights 和系统布局面板；Windows/Linux 右侧窗口控件各有 46×40px 操作容器及与当前动作一致的名称和提示；控件不参与拖动，最大化状态变化同步投影为还原动作"
      }
    },
    "NavigationRow": {
      "role": "表达项目范围、任务状态和本地 Runtime 入口",
      "variants": {
        "default": {
          "foreground": "{semantic.nav_text}",
          "background": "transparent"
        },
        "selected": {
          "foreground": "{semantic.nav_selected_text}",
          "background": "{semantic.nav_selected}",
          "indicator": "{colors.accent.base}"
        },
        "attention": {
          "foreground": "{colors.warning.strong}",
          "badge": "{colors.warning.base}"
        },
        "status_filter": {
          "foreground": "{colors.ink.600}",
          "background": "{colors.ink.50}",
          "badge": "{colors.accent.soft}",
          "badge_position": "overlay_top_right"
        }
      },
      "sizes": {
        "compact": {
          "height": "{layout.control_height}",
          "padding_x": "{spacing.4}",
          "typography": "{typography.label}"
        }
      },
      "states": [
        "default",
        "hover",
        "selected",
        "disabled",
        "attention"
      ],
      "token_refs": [
        "colors.accent.hover",
        "colors.warning.base",
        "typography.label",
        "corner_radius.small"
      ],
      "accessibility": {
        "requirement": "当前项同时使用文字、选中表面和指示条；状态数量以不占标题布局空间的右上角角标呈现且包含在可访问名称中；每项可聚焦并以 Enter 或 Space 激活"
      }
    },
    "Icon": {
      "role": "以统一轮廓矢量图形表达操作、对象和状态，不使用字符或 Emoji 替代生产图标",
      "variants": {
        "action": {
          "foreground": "{colors.ink.600}",
          "canvas": 16
        },
        "navigation": {
          "foreground": "currentColor",
          "canvas": 18
        },
        "semantic": {
          "foreground": "currentColor",
          "canvas": 16
        }
      },
      "sizes": {
        "compact": {
          "canvas": 16,
          "container": "{layout.compact_control_height}"
        },
        "standard": {
          "canvas": 18,
          "container": "{layout.control_height}"
        }
      },
      "states": [
        "default",
        "hover",
        "active",
        "focus",
        "disabled"
      ],
      "token_refs": [
        "colors.ink.600",
        "layout.compact_control_height",
        "layout.control_height"
      ],
      "accessibility": {
        "requirement": "装饰图标对辅助技术隐藏；独立图标操作提供可访问名称和悬停提示"
      }
    },
    "Button": {
      "role": "表达主操作、次操作、低风险导航和破坏操作",
      "variants": {
        "primary": {
          "foreground": "{colors.accent.on}",
          "background": "{colors.accent.base}",
          "border": "transparent"
        },
        "secondary": {
          "foreground": "{colors.ink.700}",
          "background": "{colors.paper}",
          "border": "{semantic.control_border}"
        },
        "ghost": {
          "foreground": "{semantic.text}",
          "background": "transparent",
          "border": "transparent"
        },
        "destructive": {
          "foreground": "{colors.paper}",
          "background": "{colors.danger.base}",
          "border": "{colors.danger.base}"
        }
      },
      "sizes": {
        "compact": {
          "height": "{layout.control_height}",
          "padding_x": "{spacing.4}",
          "typography": "{typography.label}"
        },
        "standard": {
          "height": 38,
          "padding_x": "{spacing.5}",
          "typography": "{typography.label}"
        }
      },
      "states": [
        "default",
        "hover",
        "active",
        "focus",
        "disabled",
        "busy"
      ],
      "token_refs": [
        "colors.accent.base",
        "colors.danger.base",
        "semantic.control_border",
        "corner_radius.small",
        "animation.fast"
      ],
      "accessibility": {
        "focus": "2px 不透明 semantic.focus 轮廓并保留 2px offset；所有状态遵守 state-contract.md"
      }
    },
    "StatusPill": {
      "role": "用文本和语义色表达七种服务器任务状态",
      "variants": {
        "pending_review": {
          "foreground": "{colors.ink.600}",
          "background": "{colors.ink.100}"
        },
        "pending": {
          "foreground": "{colors.warning.strong}",
          "background": "{colors.warning.soft}"
        },
        "in_progress": {
          "foreground": "{colors.accent.strong}",
          "background": "{colors.accent.soft}"
        },
        "completed": {
          "foreground": "{colors.success.base}",
          "background": "{colors.success.soft}"
        },
        "accepted": {
          "foreground": "{colors.accepted.base}",
          "background": "{colors.accepted.soft}"
        },
        "cancelled": {
          "foreground": "{colors.danger.base}",
          "background": "{colors.danger.soft}"
        },
        "blocked": {
          "foreground": "{colors.warning.strong}",
          "background": "{colors.warning.soft}",
          "border": "{colors.warning.base}"
        }
      },
      "sizes": {
        "compact": {
          "height": 24,
          "padding_x": "{spacing.3}",
          "typography": "{typography.label}"
        }
      },
      "states": [
        "default",
        "stale",
        "conflict"
      ],
      "token_refs": [
        "colors.ink.100",
        "colors.warning.soft",
        "colors.accent.soft",
        "colors.success.soft",
        "colors.accepted.soft",
        "colors.danger.soft"
      ],
      "accessibility": {
        "requirement": "标签始终显示状态文本，颜色不作为唯一信息"
      }
    },
    "WorkbenchHeader": {
      "role": "表达项目范围与此设备运行概况，不重复旧工具栏",
      "variants": {
        "default": {
          "surface": "{semantic.canvas}",
          "border": "{semantic.divider}"
        }
      },
      "sizes": {
        "standard": {
          "height": "{layout.workbench_topbar_height}",
          "typography": "{typography.label}"
        }
      },
      "states": [
        "default",
        "disconnected"
      ],
      "token_refs": [
        "layout.workbench_topbar_height",
        "typography.label",
        "semantic.canvas",
        "semantic.divider"
      ]
    },
    "TaskListRow": {
      "role": "单行识别事情与状态，详情负责完整目标",
      "variants": {
        "default": {
          "surface": "{semantic.canvas}",
          "foreground": "{semantic.text}"
        },
        "selected": {
          "surface": "{colors.accent.soft}",
          "indicator": "{colors.accent.base}"
        }
      },
      "sizes": {
        "standard": {
          "min_height": "{layout.row_height}",
          "typography": "{typography.body}"
        }
      },
      "states": [
        "default",
        "hover",
        "selected",
        "focus",
        "loading",
        "empty",
        "stale"
      ],
      "token_refs": [
        "layout.row_height",
        "typography.body",
        "colors.accent.soft",
        "colors.accent.base"
      ]
    },
    "FormField": {
      "role": "呈现标签、输入、帮助与就地错误",
      "variants": {
        "default": {
          "surface": "{semantic.canvas}",
          "border": "{semantic.control_border}"
        },
        "error": {
          "border": "{colors.danger.base}",
          "message": "{colors.danger.base}"
        }
      },
      "sizes": {
        "standard": {
          "min_height": "{layout.control_height}",
          "typography": "{typography.body}"
        },
        "workbench_search": {
          "height": "{layout.workbench_search_height}",
          "typography": "{typography.body}",
          "scope": "project_workbench_filter"
        }
      },
      "states": [
        "default",
        "hover",
        "focus",
        "filled",
        "disabled",
        "readonly",
        "error",
        "busy"
      ],
      "token_refs": [
        "layout.control_height",
        "layout.workbench_search_height",
        "semantic.control_border",
        "colors.danger.base",
        "typography.body"
      ]
    },
    "Composer": {
      "role": "保留草稿、上下文与清晰的发送或停止动作",
      "variants": {
        "default": {
          "surface": "{semantic.canvas}",
          "border": "{semantic.control_border}"
        },
        "error": {
          "message": "{colors.danger.base}"
        }
      },
      "sizes": {
        "standard": {
          "padding": "{spacing.5}",
          "radius": "{corner_radius.large}",
          "typography": "{typography.conversation}"
        }
      },
      "states": [
        "empty",
        "draft",
        "focus",
        "sending",
        "streaming",
        "paused",
        "error",
        "disabled"
      ],
      "token_refs": [
        "semantic.canvas",
        "semantic.control_border",
        "typography.conversation",
        "corner_radius.large",
        "spacing.5"
      ]
    },
    "RuntimePopover": {
      "role": "所有项目此设备范围的运行概况，不替代事情详情",
      "variants": {
        "default": {
          "surface": "{semantic.elevated}",
          "shadow": "{shadows.small}"
        }
      },
      "sizes": {
        "standard": {
          "padding": "{spacing.5}",
          "radius": "{corner_radius.medium}"
        }
      },
      "states": [
        "idle",
        "running",
        "queued",
        "attention",
        "disconnected",
        "loading",
        "error"
      ],
      "token_refs": [
        "semantic.elevated",
        "shadows.small",
        "spacing.5",
        "corner_radius.medium"
      ],
      "accessibility": {
        "requirement": "保持交互定义的分组、局部滚动、关闭与焦点返回"
      }
    },
    "ArtifactEvidence": {
      "role": "区分成果、Agent 声明、检查证据和用户验收",
      "variants": {
        "artifact": {
          "surface": "{semantic.canvas}",
          "border": "{semantic.divider}"
        },
        "addition": {
          "foreground": "{colors.success.base}",
          "surface": "{colors.success.soft}",
          "marker": "+"
        },
        "deletion": {
          "foreground": "{colors.danger.base}",
          "surface": "{colors.danger.soft}",
          "marker": "−"
        }
      },
      "sizes": {
        "standard": {
          "padding": "{spacing.5}",
          "typography": "{typography.body}"
        }
      },
      "states": [
        "available",
        "unverified",
        "verified",
        "failed",
        "external_wait",
        "accepted"
      ],
      "token_refs": [
        "semantic.canvas",
        "semantic.divider",
        "typography.body",
        "colors.success.base",
        "colors.success.soft",
        "colors.danger.base",
        "colors.danger.soft"
      ]
    },
    "ContextChip": {
      "role": "标识附件、共同约定或引用来源",
      "variants": {
        "default": {
          "surface": "{colors.ink.50}",
          "foreground": "{semantic.muted}"
        }
      },
      "sizes": {
        "standard": {
          "min_height": "{layout.compact_control_height}",
          "typography": "{typography.label}"
        }
      },
      "states": [
        "default",
        "hover",
        "focus",
        "unavailable",
        "selected"
      ],
      "token_refs": [
        "colors.ink.50",
        "semantic.muted",
        "layout.compact_control_height",
        "typography.label"
      ],
      "accessibility": {
        "requirement": "可移除时提供独立名称和键盘入口，来源失效显示文本"
      }
    },
    "LoginGate": {
      "role": "在启动恢复和未登录状态建立轻量、聚焦且不可绕过的认证画布",
      "variants": {
        "restoring": {
          "canvas": "{colors.ink.75}",
          "content": "{colors.ink.900}"
        },
        "logged_out": {
          "canvas": "{colors.ink.75}",
          "panel": "{colors.paper}"
        }
      },
      "sizes": {
        "desktop": {
          "panel_width": 440,
          "panel_padding": "{spacing.7}",
          "radius": "{corner_radius.large}"
        }
      },
      "states": [
        "restoring",
        "logged_out",
        "verification_sent",
        "signing_in",
        "error"
      ],
      "token_refs": [
        "colors.ink.75",
        "colors.ink.50",
        "colors.paper",
        "colors.accent.soft",
        "colors.accent.faint",
        "colors.ink.900",
        "corner_radius.large",
        "shadows.large"
      ],
      "accessibility": {
        "requirement": "浅色画布与正文保持 AA 对比度；进度与错误状态不只依赖颜色"
      }
    },
    "AccountPanel": {
      "role": "在独立认证页和设置覆盖层表达 Workshop 登录输入、会话状态与退出边界",
      "variants": {
        "logged_out": {
          "surface": "{colors.paper}",
          "status": "{colors.ink.500}",
          "primary_action": "{colors.accent.base}"
        },
        "verification_sent": {
          "surface": "{colors.info.soft}",
          "status": "{colors.info.base}",
          "primary_action": "{colors.accent.base}"
        },
        "authenticated": {
          "surface": "{colors.success.soft}",
          "status": "{colors.success.base}",
          "primary_action": "{colors.info.base}"
        },
        "expired": {
          "surface": "{colors.danger.soft}",
          "status": "{colors.danger.base}",
          "primary_action": "{colors.accent.base}"
        }
      },
      "sizes": {
        "standard": {
          "width": 560,
          "padding": "{spacing.7}",
          "field_height": 38,
          "gap": "{spacing.5}"
        }
      },
      "states": [
        "logged_out",
        "sending_code",
        "verification_sent",
        "signing_in",
        "authenticated",
        "refreshing",
        "expired",
        "signing_out"
      ],
      "token_refs": [
        "colors.paper",
        "colors.info.soft",
        "colors.success.soft",
        "colors.danger.soft",
        "colors.accent.base",
        "typography.body",
        "corner_radius.medium",
        "shadows.large"
      ],
      "accessibility": {
        "requirement": "状态同时显示图标、文本和说明；错误紧邻表单；账号可脱敏但 token 永不显示"
      }
    },
    "ConversationSurface": {
      "role": "为 Chat 与 Automation Workbench 提供唯一共享的消息渲染、浏览和滚动视觉层级",
      "variants": {
        "chat": {
          "surface": "{colors.paper}",
          "composer": "fixed",
          "transcript_scroll": "independent"
        },
        "review": {
          "surface": "{colors.paper}",
          "composer": "hidden",
          "transcript_scroll": "independent"
        },
        "intervention": {
          "surface": "{colors.paper}",
          "composer": "fixed",
          "transcript_scroll": "independent"
        },
        "reasoning_disclosure": {
          "surface": "transparent",
          "foreground": "{colors.ink.600}",
          "border": "{colors.ink.150}",
          "typography": "{typography.body}",
          "completed": "collapsed"
        },
        "agent_message": {
          "surface": "transparent",
          "foreground": "{colors.ink.900}",
          "typography": "{typography.conversation}"
        },
        "tool_activity": {
          "surface": "transparent",
          "foreground": "{colors.ink.600}",
          "typography": "{typography.caption}",
          "overflow": "ellipsis"
        },
        "approval_activity": {
          "surface": "{colors.warning.soft}",
          "foreground": "{colors.ink.900}",
          "border": "{colors.warning.base}",
          "typography": "{typography.caption}"
        },
        "user_message": {
          "surface": "{colors.accent.faint}",
          "border": "{colors.accent.soft}",
          "typography": "{typography.conversation}"
        }
      },
      "sizes": {
        "shell": {
          "min_height": 0,
          "left_pane": "stable",
          "center": "flexible",
          "inspector": "{layout.inspector_width}"
        },
        "readable": {
          "max_content_width": 760,
          "message_padding": "{spacing.7}",
          "tool_row_height": "{layout.compact_control_height}",
          "typography": "{typography.conversation}"
        }
      },
      "states": [
        "loading",
        "chat",
        "review",
        "intervention",
        "reasoning_streaming",
        "reasoning_collapsed",
        "approval_waiting",
        "streaming",
        "following_latest",
        "history_position",
        "submitting",
        "accepted",
        "error"
      ],
      "token_refs": [
        "colors.paper",
        "colors.ink.150",
        "colors.ink.600",
        "colors.ink.900",
        "colors.accent.faint",
        "colors.accent.soft",
        "colors.warning.soft",
        "colors.warning.base",
        "typography.caption",
        "typography.conversation"
      ],
      "accessibility": {
        "requirement": "reasoning 使用原生可聚焦展开控件并提供可读标题；空 reasoning 不产生控件；工具与权限状态同时使用图标和文字；工具目标溢出时保留可访问全称；阅读历史时新消息不强制改变滚动位置"
      }
    },
    "MetricCard": {
      "role": "仅在两个以上可比较指标直接支持当前判断时提供态势摘要，不作为页面默认容器",
      "variants": {
        "neutral": {
          "surface": "{colors.paper}",
          "value": "{colors.ink.900}"
        },
        "running": {
          "surface": "{colors.accent.faint}",
          "value": "{colors.accent.strong}"
        },
        "healthy": {
          "surface": "{colors.success.soft}",
          "value": "{colors.success.base}"
        },
        "attention": {
          "surface": "{colors.warning.soft}",
          "value": "{colors.warning.strong}"
        }
      },
      "sizes": {
        "standard": {
          "min_height": 92,
          "padding": "{spacing.5}"
        }
      },
      "states": [
        "default",
        "hover",
        "filtered"
      ],
      "token_refs": [
        "colors.paper",
        "colors.accent.faint",
        "colors.success.soft",
        "colors.warning.soft"
      ]
    },
    "TaskTable": {
      "role": "展示确定性队列、完整状态列表和任务执行资格",
      "variants": {
        "queue": {
          "header": "{colors.ink.50}",
          "current_indicator": "{colors.accent.base}"
        },
        "browser": {
          "header": "{colors.ink.50}",
          "selected": "{colors.accent.faint}"
        }
      },
      "sizes": {
        "dense": {
          "row_height": "{layout.compact_row_height}",
          "header_height": "{layout.control_height}",
          "cell_padding_x": "{spacing.4}",
          "typography": "{typography.body}"
        },
        "standard": {
          "row_height": "{layout.row_height}",
          "header_height": "{layout.control_height}",
          "cell_padding_x": "{spacing.5}",
          "typography": "{typography.body}"
        }
      },
      "states": [
        "loading",
        "ready",
        "empty",
        "selected",
        "stale",
        "conflict",
        "disabled"
      ],
      "token_refs": [
        "colors.ink.50",
        "colors.ink.150",
        "colors.accent.base",
        "colors.accent.faint",
        "typography.caption"
      ],
      "accessibility": {
        "requirement": "可选行进入 Tab 顺序并支持 Enter 与 Space；选中、加载、冲突和禁用状态同时提供文本或可访问名称"
      }
    },
    "RuntimeStage": {
      "role": "投影实际执行活动与结果；阶段名称来自 Agent 事实，不预设 Controller、Worker 或固定阶段",
      "variants": {
        "idle": {
          "indicator": "{colors.ink.300}",
          "foreground": "{colors.ink.600}"
        },
        "active": {
          "indicator": "{colors.accent.base}",
          "foreground": "{colors.ink.900}"
        },
        "complete": {
          "indicator": "{colors.success.base}",
          "foreground": "{colors.success.base}"
        },
        "failed": {
          "indicator": "{colors.danger.base}",
          "foreground": "{colors.danger.base}"
        }
      },
      "sizes": {
        "standard": {
          "height": 44,
          "gap": "{spacing.3}"
        }
      },
      "states": [
        "idle",
        "active",
        "complete",
        "failed",
        "awaiting_human"
      ],
      "token_refs": [
        "colors.accent.base",
        "colors.success.base",
        "colors.danger.base",
        "typography.caption"
      ]
    },
    "AttentionStrip": {
      "role": "提升必须由用户处理的人工事项但不自动打开 Chat",
      "variants": {
        "normal": {
          "surface": "{colors.ink.50}",
          "border": "{colors.ink.150}"
        },
        "required": {
          "surface": "{colors.warning.soft}",
          "border": "{colors.warning.base}"
        },
        "destructive": {
          "surface": "{colors.danger.soft}",
          "border": "{colors.danger.base}"
        }
      },
      "sizes": {
        "standard": {
          "min_height": 52,
          "padding": "{spacing.5}"
        }
      },
      "states": [
        "empty",
        "required",
        "submitting",
        "accepted",
        "error"
      ],
      "token_refs": [
        "colors.warning.soft",
        "colors.warning.base",
        "colors.danger.soft",
        "shadows.small"
      ]
    },
    "RecoveryCard": {
      "role": "展示远端与本地事实差异、冻结范围、责任方和恢复动作",
      "variants": {
        "warning": {
          "surface": "{colors.warning.soft}",
          "marker": "{colors.warning.base}"
        },
        "critical": {
          "surface": "{colors.danger.soft}",
          "marker": "{colors.danger.base}"
        },
        "informational": {
          "surface": "{colors.info.soft}",
          "marker": "{colors.info.base}"
        }
      },
      "sizes": {
        "standard": {
          "padding": "{spacing.6}",
          "radius": "{corner_radius.medium}"
        }
      },
      "states": [
        "open",
        "retrying",
        "resolved",
        "external_wait"
      ],
      "token_refs": [
        "colors.warning.soft",
        "colors.danger.soft",
        "colors.info.soft",
        "corner_radius.medium"
      ]
    },
    "AutomationExecutionOverview": {
      "role": "在 Workbench 侧栏一次展示完整执行时间、Gap 总数、逐 Gap 工作与 Automation 专属证据",
      "variants": {
        "summary": {
          "surface": "{colors.ink.50}",
          "foreground": "{colors.ink.900}",
          "border": "{colors.ink.150}"
        },
        "gap_completed": {
          "indicator": "{colors.success.base}",
          "foreground": "{colors.ink.700}"
        },
        "gap_active": {
          "indicator": "{colors.accent.base}",
          "foreground": "{colors.ink.900}"
        },
        "gap_waiting": {
          "indicator": "{colors.warning.base}",
          "foreground": "{colors.warning.strong}"
        },
        "gap_failed": {
          "indicator": "{colors.danger.base}",
          "foreground": "{colors.danger.base}"
        }
      },
      "sizes": {
        "compact": {
          "row_min_height": "{layout.row_height}",
          "gap": "{spacing.3}",
          "typography": "{typography.caption}"
        }
      },
      "states": [
        "loading",
        "running",
        "awaiting_human",
        "completed",
        "interrupted",
        "failed"
      ],
      "token_refs": [
        "colors.ink.50",
        "colors.ink.150",
        "colors.ink.700",
        "colors.ink.900",
        "colors.success.base",
        "colors.accent.base",
        "colors.warning.base",
        "colors.warning.strong",
        "colors.danger.base",
        "typography.caption"
      ],
      "accessibility": {
        "requirement": "完整时间、轮数与每个 Gap 状态均显示文本；颜色和图标不作为唯一信息；Gap 列表可键盘浏览并定位关联 Agent 消息"
      }
    }
  },
  "contrast": [
    {
      "theme": "dark",
      "foreground": "semantic.text",
      "background": "semantic.canvas",
      "ratio": 14.64,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "semantic.muted",
      "background": "colors.ink.50",
      "ratio": 8.23,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "semantic.nav_text",
      "background": "semantic.sidebar",
      "ratio": 9.48,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "semantic.nav_selected_text",
      "background": "semantic.nav_selected",
      "ratio": 11.21,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "semantic.control_border",
      "background": "semantic.canvas",
      "ratio": 4.57,
      "minimum": 3
    },
    {
      "theme": "dark",
      "foreground": "semantic.focus",
      "background": "semantic.canvas",
      "ratio": 9.82,
      "minimum": 3
    },
    {
      "theme": "dark",
      "foreground": "semantic.focus",
      "background": "semantic.sidebar",
      "ratio": 10.17,
      "minimum": 3
    },
    {
      "theme": "dark",
      "foreground": "colors.accent.on",
      "background": "colors.accent.base",
      "ratio": 7.79,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "colors.accent.on",
      "background": "colors.accent.hover",
      "ratio": 7.05,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "colors.accent.on",
      "background": "colors.accent.pressed",
      "ratio": 6.3,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "colors.success.base",
      "background": "colors.success.soft",
      "ratio": 7.51,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "colors.accepted.base",
      "background": "colors.accepted.soft",
      "ratio": 7.09,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "colors.warning.strong",
      "background": "colors.warning.soft",
      "ratio": 7.92,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "colors.danger.base",
      "background": "colors.danger.soft",
      "ratio": 6.55,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "colors.info.base",
      "background": "colors.info.soft",
      "ratio": 6.78,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "colors.accent.strong",
      "background": "colors.accent.soft",
      "ratio": 7.52,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "colors.ink.600",
      "background": "colors.ink.100",
      "ratio": 6.82,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "colors.paper",
      "background": "colors.danger.base",
      "ratio": 8.24,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "semantic.disabled_text",
      "background": "semantic.disabled_bg",
      "ratio": 6.82,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "semantic.text",
      "background": "semantic.elevated",
      "ratio": 12.25,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "semantic.muted",
      "background": "semantic.canvas",
      "ratio": 9.15,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "semantic.muted",
      "background": "semantic.elevated",
      "ratio": 7.65,
      "minimum": 4.5
    },
    {
      "theme": "dark",
      "foreground": "semantic.focus",
      "background": "semantic.elevated",
      "ratio": 8.21,
      "minimum": 3
    },
    {
      "theme": "dark",
      "foreground": "semantic.control_border",
      "background": "semantic.elevated",
      "ratio": 3.82,
      "minimum": 3
    },
    {
      "theme": "dark",
      "foreground": "semantic.nav_text",
      "background": "semantic.nav_selected",
      "ratio": 7.0,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "semantic.text",
      "background": "semantic.canvas",
      "ratio": 17.93,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "semantic.muted",
      "background": "colors.ink.50",
      "ratio": 7.42,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "semantic.nav_text",
      "background": "semantic.sidebar",
      "ratio": 9.48,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "semantic.nav_selected_text",
      "background": "semantic.nav_selected",
      "ratio": 15.57,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "semantic.control_border",
      "background": "semantic.canvas",
      "ratio": 3.79,
      "minimum": 3
    },
    {
      "theme": "legacy-mixed",
      "foreground": "semantic.focus",
      "background": "semantic.canvas",
      "ratio": 4.64,
      "minimum": 3
    },
    {
      "theme": "legacy-mixed",
      "foreground": "semantic.focus",
      "background": "semantic.sidebar",
      "ratio": 3.86,
      "minimum": 3
    },
    {
      "theme": "legacy-mixed",
      "foreground": "colors.accent.on",
      "background": "colors.accent.base",
      "ratio": 7.79,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "colors.accent.on",
      "background": "colors.accent.hover",
      "ratio": 7.05,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "colors.accent.on",
      "background": "colors.accent.pressed",
      "ratio": 6.3,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "colors.success.base",
      "background": "colors.success.soft",
      "ratio": 5.71,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "colors.accepted.base",
      "background": "colors.accepted.soft",
      "ratio": 5.69,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "colors.warning.strong",
      "background": "colors.warning.soft",
      "ratio": 4.62,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "colors.danger.base",
      "background": "colors.danger.soft",
      "ratio": 5.02,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "colors.info.base",
      "background": "colors.info.soft",
      "ratio": 5.48,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "colors.accent.strong",
      "background": "colors.accent.soft",
      "ratio": 5.1,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "colors.ink.600",
      "background": "colors.ink.100",
      "ratio": 6.84,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "colors.paper",
      "background": "colors.danger.base",
      "ratio": 5.84,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "semantic.disabled_text",
      "background": "semantic.disabled_bg",
      "ratio": 5.42,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "semantic.text",
      "background": "semantic.elevated",
      "ratio": 17.93,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "semantic.muted",
      "background": "semantic.canvas",
      "ratio": 7.89,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "semantic.muted",
      "background": "semantic.elevated",
      "ratio": 7.89,
      "minimum": 4.5
    },
    {
      "theme": "legacy-mixed",
      "foreground": "semantic.focus",
      "background": "semantic.elevated",
      "ratio": 4.64,
      "minimum": 3
    },
    {
      "theme": "legacy-mixed",
      "foreground": "semantic.control_border",
      "background": "semantic.elevated",
      "ratio": 3.79,
      "minimum": 3
    },
    {
      "theme": "legacy-mixed",
      "foreground": "semantic.nav_text",
      "background": "semantic.nav_selected",
      "ratio": 8.23,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "semantic.text",
      "background": "semantic.canvas",
      "ratio": 17.93,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "semantic.muted",
      "background": "colors.ink.50",
      "ratio": 7.42,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "semantic.nav_text",
      "background": "semantic.sidebar",
      "ratio": 7.42,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "semantic.nav_selected_text",
      "background": "semantic.nav_selected",
      "ratio": 16.54,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "semantic.control_border",
      "background": "semantic.canvas",
      "ratio": 3.79,
      "minimum": 3
    },
    {
      "theme": "light",
      "foreground": "semantic.focus",
      "background": "semantic.canvas",
      "ratio": 5.53,
      "minimum": 3
    },
    {
      "theme": "light",
      "foreground": "semantic.focus",
      "background": "semantic.sidebar",
      "ratio": 5.21,
      "minimum": 3
    },
    {
      "theme": "light",
      "foreground": "colors.accent.on",
      "background": "colors.accent.base",
      "ratio": 7.79,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "colors.accent.on",
      "background": "colors.accent.hover",
      "ratio": 7.05,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "colors.accent.on",
      "background": "colors.accent.pressed",
      "ratio": 6.3,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "colors.success.base",
      "background": "colors.success.soft",
      "ratio": 5.71,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "colors.accepted.base",
      "background": "colors.accepted.soft",
      "ratio": 5.69,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "colors.warning.strong",
      "background": "colors.warning.soft",
      "ratio": 4.62,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "colors.danger.base",
      "background": "colors.danger.soft",
      "ratio": 5.02,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "colors.info.base",
      "background": "colors.info.soft",
      "ratio": 5.48,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "colors.accent.strong",
      "background": "colors.accent.soft",
      "ratio": 5.1,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "colors.ink.600",
      "background": "colors.ink.100",
      "ratio": 6.84,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "colors.paper",
      "background": "colors.danger.base",
      "ratio": 5.84,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "semantic.disabled_text",
      "background": "semantic.disabled_bg",
      "ratio": 5.42,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "semantic.text",
      "background": "semantic.elevated",
      "ratio": 17.93,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "semantic.muted",
      "background": "semantic.canvas",
      "ratio": 7.89,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "semantic.muted",
      "background": "semantic.elevated",
      "ratio": 7.89,
      "minimum": 4.5
    },
    {
      "theme": "light",
      "foreground": "semantic.focus",
      "background": "semantic.elevated",
      "ratio": 5.53,
      "minimum": 3
    },
    {
      "theme": "light",
      "foreground": "semantic.control_border",
      "background": "semantic.elevated",
      "ratio": 3.79,
      "minimum": 3
    },
    {
      "theme": "light",
      "foreground": "semantic.nav_text",
      "background": "semantic.nav_selected",
      "ratio": 7.27,
      "minimum": 4.5
    }
  ]
};
