const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='arcorbit-exploration-chat-todo-v1';
function initial(){return {current:'chat1',tasks:[{id:'T101',title:'修复会话切换时的滚动跳动',body:'切回会话时恢复原阅读位置。',status:'待处理'},{id:'T102',title:'完善离线草稿恢复',body:'应用重启后保留未发送内容。',status:'Automation 执行中'}],sessions:[{id:'chat1',title:'Chat 的阅读体验',task:null,draft:'',scroll:0,messages:[{role:'user',text:'切换会话时，希望保留原来的阅读位置。另外可以补一个回到最新的按钮。'},{role:'agent',text:'可以分开处理：\n1. 恢复每段会话的阅读位置。\n2. 有新消息时显示“回到最新”。\n先明确滚动恢复的规则，再决定执行范围。'}]}]};}
let state;try{state=JSON.parse(localStorage.getItem(key))||initial()}catch{state=initial()}
let trigger,mode,sourceText='',busy=false;const current=()=>state.sessions.find(s=>s.id===state.current),task=()=>state.tasks.find(t=>t.id===current().task);
function save(){localStorage.setItem(key,JSON.stringify(state))}function note(s){$('#notice').textContent=s}function capture(){current().draft=$('#draft').value;current().scroll=$('#messages').scrollTop;save()}
function render(){const s=current(),t=task();$('#title').textContent=s.title;$('#relation').innerHTML=t?`<button id="taskDetail">待办 ${esc(t.id)} · ${esc(t.status)}</button>`:'自由对话 · ArcOrbit';$('#whole').disabled=!!t;$('#whole').textContent=t?'已转为待办':'转为待办';$('#draft').value=s.draft;$('#intent').value='分析';$('#send').disabled=!!t&&t.status.includes('执行中');$('#messages').innerHTML=s.messages.map((m,i)=>`<article class="message ${m.role}"><small>${m.role==='user'?'你':'Agent'}</small><p>${esc(m.text)}</p>${m.card?`<button class="card" data-task="${esc(m.card)}">待办 ${esc(m.card)} · ${esc(state.tasks.find(t=>t.id===m.card)?.title)}<br>打开待办对话 →</button>`:m.role==='agent'?`<button data-extract="${i}">从这条消息新建待办</button>`:''}</article>`).join('');$('#sessionRows').innerHTML=state.sessions.map(s=>`<button data-session="${esc(s.id)}" class="${s.id===state.current?'selected':''}">${esc(s.title)}${s.task?'<small>待办 '+esc(s.task)+'</small>':''}</button>`).join('');$('#messages').scrollTop=s.scroll||0;note(t?.status.includes('执行中')?'此待办正在 Automation 执行。可阅读上下文；请到运行入口暂停后再继续 Chat。':'');save()}
function open(content){trigger=document.activeElement;$('#dialog').innerHTML=content;$('#dialog').showModal()}
function close(){if(busy)return;$('#dialog').close();trigger?.focus()}
$('#dialog').addEventListener('cancel',e=>{e.preventDefault();close()});
function form(kind,text=''){capture();mode=kind;sourceText=text;open(`<h2 id="dialogTitle">${kind==='whole'?'将整段对话转为待办':'在对话中新建待办'}</h2><p>${kind==='whole'?'整段历史保留，创建后在当前对话继续推进这个待办。':'原对话保持不变，新待办有独立对话。'}</p><form id="create"><label>项目<input value="ArcOrbit" readonly></label><label>标题<input id="taskTitle" required maxlength="120" value="${esc(kind==='whole'?current().title:'补充“回到最新”按钮')}"></label><label>待办描述<textarea id="taskBody" required>${esc(text||'明确会话滚动恢复规则，并补充回到最新入口。')}</textarea></label><details><summary>将保存的来源上下文</summary><p>${esc(kind==='whole'?current().messages.map(m=>m.text).join('\n\n'):text||'仅包含以上描述及来源对话链接，不自动带入全部历史。')}</p></details><p class="muted">保存为待评审，不自动启动执行。</p><p id="formError" role="alert" class="error"></p><footer><button type="button" data-close>取消</button><button class="primary" id="createButton">创建待办</button></footer></form>`)}
function openTask(id){capture();let s=state.sessions.find(s=>s.task===id);if(!s){const t=state.tasks.find(t=>t.id===id);s={id:'chat-'+id,title:t.title,task:id,draft:'',scroll:0,messages:[{role:'agent',text:`已载入待办：${t.title}\n${t.body}\n你可以先提问分析，或明确选择执行。`}]};state.sessions.push(s)}state.current=s.id;close();$('#sessions').classList.remove('open');render();$('#draft').focus()}
function picker(){capture();open('<h2 id="dialogTitle">选择已有待办</h2><p>ArcOrbit · 打开关联对话，已有对话会直接恢复。</p><input id="search" aria-label="搜索待办" placeholder="搜索标题或编号"><div id="choices"></div><footer><button data-close>取消</button></footer>');choices('')}
function choices(q){const rows=state.tasks.filter(t=>(t.title+t.id).includes(q));$('#choices').innerHTML=rows.length?rows.map(t=>`<button class="task-choice" data-task="${t.id}">${esc(t.title)}<span class="muted">${t.id} · ${esc(t.status)}${state.sessions.some(s=>s.task===t.id)?' · 继续已有对话':''}</span></button>`).join(''):'<p class="empty">没有匹配的待办。调整搜索词后重试。</p>'}
$('#dialog').addEventListener('input',e=>{if(e.target.id==='search')choices(e.target.value)});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close'))close();if(b.dataset.task)openTask(b.dataset.task);if(b.dataset.extract)form('child',current().messages[Number(b.dataset.extract)].text);if(b.dataset.session){capture();state.current=b.dataset.session;render();$('#sessions').classList.remove('open')}if(b.id==='taskDetail'){const t=task();open(`<h2 id="dialogTitle">${esc(t.title)}</h2><p>${esc(t.id)} · ${esc(t.status)}</p><p>${esc(t.body)}</p><p class="muted">在这里查看目标；完整属性、成果和验收仍归 Work / Thing。</p><footer><button data-close>返回对话</button></footer>`)}});
$('#whole').onclick=()=>form('whole');$('#child').onclick=()=>form('child');$('#existing').onclick=picker;$('#listToggle').onclick=()=>$('#sessions').classList.toggle('open');
$('#dialog').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;$('#createButton').disabled=true;$('#createButton').textContent='创建中…';await new Promise(r=>setTimeout(r,350));if($('#fail').checked){$('#fail').checked=false;busy=false;$('#createButton').disabled=false;$('#createButton').textContent='重试创建';$('#formError').textContent='创建失败，输入已保留。请重试。';return}const t={id:'T'+(103+state.tasks.length-2),title:$('#taskTitle').value.trim(),body:$('#taskBody').value.trim(),status:'待评审',source:current().id,context:mode==='whole'?current().messages.map(m=>m.text):[sourceText]};if(!t.title||!t.body){busy=false;$('#createButton').disabled=false;$('#createButton').textContent='创建待办';$('#formError').textContent='标题和描述不能为空。';return}state.tasks.push(t);if(mode==='whole'){current().task=t.id;current().title=t.title}else current().messages.push({role:'agent',text:'已创建待办，当前讨论可以继续。',card:t.id});busy=false;close();render();note(mode==='whole'?'已转为待办，继续使用当前对话。':'已创建待办；点击消息卡片可进入它的独立对话。')});
$('#draft').oninput=()=>{current().draft=$('#draft').value;save()};$('#messages').onscroll=()=>{current().scroll=$('#messages').scrollTop;save()};
function send(){const s=current(),t=task(),text=$('#draft').value.trim();if(!text||t?.status.includes('执行中'))return;s.messages.push({role:'user',text});s.messages.push({role:'agent',text:$('#intent').value==='执行'?'已收到执行意图。本原型仅展示交互反馈，未运行 Agent，也未改变待办业务状态。':'先分析目标、约束和完成标准。本条为本地模拟回复。'});s.draft='';render();$('#messages').scrollTop=$('#messages').scrollHeight;$('#draft').focus()}
$('#composer').onsubmit=e=>{e.preventDefault();send()};$('#draft').onkeydown=e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)&&!e.isComposing){e.preventDefault();send()}};
$('#new').onclick=()=>{capture();const id='free-'+Date.now();state.sessions.push({id,title:'新对话',task:null,draft:'',scroll:0,messages:[]});state.current=id;render();$('#draft').focus()};$('#reset').onclick=()=>{state=initial();save();render()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#dialog').open){$('#sessions').classList.remove('open');$('#listToggle').focus()}});render();
